### ISSUE TITLE
peerDependencies not linked to root node modules

### ISSUE THREAD

**Issue by mokone91** [pnpm/pnpm#5064] opened 2022-07-20 10:18 UTC
Hi!
I have separate eslint config package used in my projects.
I have added eslint/stylelint to peerDependencies of this package as i want to manage versions on config package.
this packages is added as dependency of root package.json
I have added 'auto-install-peers=true' to .npmrc
So i expect that this peers will be added to root node_modules - but its not...

**Comment by zkochan** [comment] 2022-07-20 14:44
It is a duplicate of #5064

**Closed by zkochan** 2022-07-20 14:44 UTC
Labels: type: bug
