### ISSUE TITLE
Not resolving git commit on install

### ISSUE THREAD

**Issue by snorkelsimon** [pnpm/pnpm#3501] opened 2021-06-03 02:03 UTC
### Code to reproduce the issue:
Install this specific package `pnpm i @celo/phone-number-privacy-common`

### Expected behavior: 
Package to be installed

### Actual behavior:
pnpm throws an error that it cannot resolve a commit, though the commit does exist 
https://github.com/celo-org/blind-threshold-bls-wasm/commit/e1e2f8a1ab5154c2f0b1c55cb0d61fbb1d907208

```
 ERROR  Could not resolve e1e2f8a to a commit of git://github.com/celo-org/blind-threshold-bls-wasm.git.
at resolveRefFromRefs         ../.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:79172  throw new Error(`Could n…
at resolveRef                 ../.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:79166  return resolveRefFromRef…
at processTicksAndRejections  internal/process/task_queues.js:93
at async resolveGit           ../.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:79117  const commit = await res…
at resolve                    ../.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:80203  const resolution = (_a =…
at async run                  ../.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:66289  resolve(await operation);
```
### Additional information:

 - `node -v` prints: v14.16.1
 - Windows, macOS, or Linux?: macOS

.pnpm-debug.log:
```
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 debug pnpm:package-manifest": {
    "initial": {},
    "prefix": "/Users/user"
  },
  "2 debug pnpm:context": {
    "currentLockfileExists": false,
    "storeDir": "/Users/user/.pnpm-store/v3",
    "virtualStoreDir": "/Users/user/node_modules/.pnpm"
  },
  "3 debug pnpm:stage": {
    "prefix": "/Users/user",
    "stage": "resolution_started"
  },
  "4 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/@celo/phone-number-privacy-common/1.0.33",
    "wanted": {
      "dependentId": ".",
      "name": "@celo/phone-number-privacy-common",
      "rawSpec": "latest"
    }
  },
  "5 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/phone-number-privacy-common/1.0.33",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "6 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/@celo/identity/1.0.2",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "@celo/identity",
      "rawSpec": "1.0.2"
    }
  },
  "7 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/identity/1.0.2",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "8 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/@celo/base/1.1.1",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "@celo/base",
      "rawSpec": "1.1.1"
    }
  },
  "9 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/base/1.1.1",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "10 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/@celo/contractkit/1.0.2",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "@celo/contractkit",
      "rawSpec": "1.0.2"
    }
  },
  "11 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/contractkit/1.0.2",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "12 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/btoa/1.2.1",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "btoa",
      "rawSpec": "1.2.1"
    }
  },
  "13 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/btoa/1.2.1",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "14 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/bunyan-debug-stream/2.0.0",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "bunyan-debug-stream",
      "rawSpec": "2.0.0"
    }
  },
  "15 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bunyan-debug-stream/2.0.0",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "16 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/@celo/utils/1.0.2",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "@celo/utils",
      "rawSpec": "1.0.2"
    }
  },
  "17 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/utils/1.0.2",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "18 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/bunyan/1.8.12",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "bunyan",
      "rawSpec": "1.8.12"
    }
  },
  "19 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bunyan/1.8.12",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "20 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/bunyan-gke-stackdriver/0.1.2",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "bunyan-gke-stackdriver",
      "rawSpec": "0.1.2"
    }
  },
  "21 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bunyan-gke-stackdriver/0.1.2",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "22 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/phone-number-privacy-common/1.0.33",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "23 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/btoa/1.2.1",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "24 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bunyan-debug-stream/2.0.0",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "25 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bunyan-gke-stackdriver/0.1.2",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "26 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bunyan/1.8.12",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "27 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/bignumber.js/9.0.1",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "bignumber.js",
      "rawSpec": "^9.0.0"
    }
  },
  "28 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bignumber.js/9.0.1",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "29 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/bignumber.js/9.0.1",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "30 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/is-base64/1.1.0",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "is-base64",
      "rawSpec": "^1.1.0"
    }
  },
  "31 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/is-base64/1.1.0",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "32 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/is-base64/1.1.0",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "33 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/elliptic/6.5.4",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "elliptic",
      "rawSpec": "^6.5.4"
    }
  },
  "34 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/elliptic/6.5.4",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "35 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/dotenv/8.6.0",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "dotenv",
      "rawSpec": "^8.2.0"
    }
  },
  "36 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/dotenv/8.6.0",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "37 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/elliptic/6.5.4",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "38 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/dotenv/8.6.0",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "39 debug pnpm:_dependency_resolved": {
    "resolution": "registry.npmjs.org/libphonenumber-js/1.9.19",
    "wanted": {
      "dependentId": "/@celo/phone-number-privacy-common/1.0.33",
      "name": "libphonenumber-js",
      "rawSpec": "^1.9.11"
    }
  },
  "40 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/libphonenumber-js/1.9.19",
    "requester": "/Users/user",
    "status": "resolved"
  },
  "41 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/libphonenumber-js/1.9.19",
    "requester": "/Users/user",
    "status": "found_in_store"
  },
  "42 debug pnpm:fetching-progress": {
    "attempt": 1,
    "packageId": "registry.npmjs.org/@celo/utils/1.0.2",
    "size": 75179,
    "status": "started"
  },
  "43 debug pnpm:progress": {
    "packageId": "registry.npmjs.org/@celo/utils/1.0.2",
    "requester": "/Users/user",
    "status": "fetched"
  },
  "44 debug pnpm:fetching-progress": {
    "attempt": 1,
    "packageId": "registry.npmjs.org/@celo/contractkit/1.0.2",
    "size": 207863,
    "status": "started"
  },
  "45 error pnpm": {
    "pkgsStack": [
      {
        "id": "registry.npmjs.org/@celo/phone-number-privacy-common/1.0.33",
        "name": "@celo/phone-number-privacy-common",
        "version": "1.0.33"
      }
    ],
    "err": {
      "name": "Error",
      "message": "Could not resolve e1e2f8a to a commit of git://github.com/celo-org/blind-threshold-bls-wasm.git.",
      "stack": "Error: Could not resolve e1e2f8a to a commit of git://github.com/celo-org/blind-threshold-bls-wasm.git.\n    at resolveRefFromRefs (/Users/user/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:79172:17)\n    at resolveRef (/Users/user/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:79166:14)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async resolveGit (/Users/user/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:79117:24)\n    at async Object.resolve (/Users/user/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:80203:236)\n    at async run (/Users/user/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@6.6.2/node_modules/pnpm/dist/pnpm.cjs:66289:23)"
    }
  }
}
```

**Comment by zkochan** [comment] 2021-06-05 20:27
This is a  duplicate of #1127

**Closed** 2021-06-05 20:54 UTC
Labels: type: bug

**Comment by zkochan** [comment] 2021-06-05 23:49
:ship: 6.7.2

**Comment by watery** [comment] 2021-09-23 09:27
@zkochan I think I've hit this on 6.15.1 with dependency `@react-native-picker/picker` declared as:
```
...
"@react-native-picker/picker": "git://github.com/react-native-picker/picker.git#1.1.3",
...

```
Should I open a new issue?

**Comment by watery** [comment] 2021-09-23 09:58
NVM, I think it's not the same as my dependency has a _semver_ in it (I've opened #3789)
