### ISSUE TITLE
EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\pnpm-global'

### ISSUE THREAD

**Issue by TigersWay** [pnpm/pnpm#928] opened 2017-10-31 07:06 UTC
### To reproduce the issue:
```
C:\>npm -g install pnpm
C:\Users\Ben\AppData\Roaming\npm\pnpx -> C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\lib\bin\pnpx.js
C:\Users\Ben\AppData\Roaming\npm\pnpm -> C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\lib\bin\pnpm.js

> drivelist@5.2.6 install C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\drivelist
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds\drivelist-v5.2.6-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Ben\AppData\Roaming\npm-cache\_prebuilds\https-github.com-resin-io-modules-drivelist-releases-download-v5.2.6-drivelist-v5.2.6-node-v57-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Ben\AppData\Roaming\npm-cache\_prebuilds\https-github.com-resin-io-modules-drivelist-releases-download-v5.2.6-drivelist-v5.2.6-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\drivelist\build\Release\drivelist.node
prebuild-install info unpack required C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\drivelist\build\Release\drivelist.node successfully
prebuild-install info install Successfully installed prebuilt binary!
+ pnpm@1.19.3
added 574 packages in 63.807s
```
```
C:\>pnpm -g install less
 ERROR  EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\pnpm-global'
fs.js:648
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\pnpm-debug.log'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.writeFileSync (fs.js:1293:33)
    at process.on (C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\pnpm-file-reporter\lib\index.js:24:12)
    at emitOne (events.js:120:20)
    at process.emit (events.js:210:7)
    at processEmit [as emit] (C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\signal-exit\index.js:149:35)
```
In fact, whatever I try gives the same error!

There is no `C:\Users\Ben\.pnpm-store` folder and `pnpm-debug.log` file is nowhere to be found

### Additional information:

 - `node -v` prints: v8.8.0
 - Windows, OS X, or Linux?: Windows 10 x64

**Comment by zkochan** [comment] 2017-10-31 07:53
non-global installations fail as well?

**Comment by TigersWay** [comment] 2017-11-01 10:20
```
D:\TigersWay\Projects\Learning\justTry>pnpm install gulp --save-dev
Adding 181 packages to node_modules
 WARN  EXDEV: cross-device link not permitted, link 'C:\Users\Ben\.pnpm-store\2\registry.npmjs.org\chalk\1.1.3\node_modules\chalk\license' -> 'D:\TigersWay\Projects\Learning\justTry\node_modules\.registry.npmjs.org\chalk\1.1.3\node_modules\chalk+stage\license'
Falling back to copying packages from store
Relinking D:\TigersWay\Projects\Learning\justTry\node_modules\.registry.npmjs.org\core-util-is\1.0.2\node_modules\core-util-is from
the store
Resolving: total 181, reused 5, downloaded 176, done
Relinking D:\TigersWay\Projects\Learning\justTry\node_modules\.registry.npmjs.org\safe-buffer\5.1.1\node_modules\safe-buffer from the store
Relinking D:\TigersWay\Projects\Learning\justTry\node_modules\.registry.npmjs.org\extend\3.0.1\node_modules\extend from the store
Relinking D:\TigersWay\Projects\Learning\justTry\node_modules\.registry.npmjs.org\mkdirp\0.5.1\node_modules\mkdirp from the store
Relinking D:\TigersWay\Projects\Learning\justTry\node_modules\.registry.npmjs.org\minimist\0.0.8\node_modules\minimist from the store

devDependencies:
+ gulp 3.9.1
```
It seems to be working... But I thought I would find a `.pnpm-store` folder in` D:\`, but there is nothing.

I haven't been working with pnpm for a few weeks...  Did I miss something? ;-)

**Comment by zkochan** [comment] 2017-11-01 11:39
It depends, if your homedir is on disk `D:`, the store will be in the homedir.

Also, you can check the location of the store in the `node_modules/.modules.yaml` file

**Comment by TigersWay** [comment] 2017-11-01 13:48
`node_modules/.modules.yaml` gives `store: 'C:\Users\Ben\.pnpm-store\2'` !

Well, let's try again :-) sorry.

nodejs & npm are one the system drive C:, all projects are somewhere in D:\TigersWay\<some path>, and I am not sure what you call a "homedir".
How should I proceed to re-install and get the "junctions/hard links" benefits?

**Comment by zkochan** [comment] 2017-11-01 14:11
Homedir is `C:\Users\Ben` in your case. pnpm uses [drivelist](https://github.com/resin-io-modules/drivelist) to detect drives. But it is a native, optional dependency. It might have failed on your system.

You can use the [store](https://github.com/pnpm/pnpm#store) config to specify the location of your store on disk `D:`. So you can create a `.npmrc` in your projects root with this content:

```ini
store=D:\.pnpm-store
```

Also, I will create an issue to solve disk-detection w/o drivelist.

**Comment by TigersWay** [comment] 2017-11-05 14:33
I think I understand the `.npmrc` file in the project root. But I am not sure what I should do for the global part.

Anyway in case it is interesting for you, here is the detail - and some drivelist errors - of my last try a few minutes ago :-)
```
D:\>node -v
v9.0.0

D:\>npm -v
5.5.1

D:\>npm -g ls -depth=0
C:\Users\Ben\AppData\Roaming\npm
`-- (empty)

D:\>npm -g config set store D:\.pnpm-store

D:\>npm -g install pnpm
C:\Users\Ben\AppData\Roaming\npm\pnpx -> C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\lib\bin\pnpx.js
C:\Users\Ben\AppData\Roaming\npm\pnpm -> C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\lib\bin\pnpm.js

> drivelist@5.2.6 install C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\drivelist
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds\drivelist-v5.2.6-node-v59-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Ben\AppData\Roaming\npm-cache\_prebuilds\https-github.com-resin-io-modules-drivelist-releases-download-v5.2.6-drivelist-v5.2.6-node-v59-win32-x64.tar.gz
prebuild-install http request GET https://github.com/resin-io-modules/drivelist/releases/download/v5.2.6/drivelist-v5.2.6-node-v59-win32-x64.tar.gz
prebuild-install http 404 https://github.com/resin-io-modules/drivelist/releases/download/v5.2.6/drivelist-v5.2.6-node-v59-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.0.0 runtime=node arch=x64 platform=win32)

C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\drivelist>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ben\AppData\Roaming\npm\node_modules\pnpm\node_modules\drivelist
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: drivelist@5.2.6 (node_modules\pnpm\node_modules\drivelist):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: drivelist@5.2.6 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

```

**Comment by koppor** [comment] 2017-12-06 11:10
## Insecure workaround

Proposed workaround. Since `pnpm install -g` also needs access to `\Program Files\nodejs`, it seems to be most easy to move the nodejs installation.

Sorry for German screenshots - short story: Just give all users write access to the `nodejs` folder:

![grafik](https://user-images.githubusercontent.com/1366654/33658737-0dd58e9c-da7e-11e7-894b-096f0347597c.png)

## Secure workaround - without the ability to add new executables

Alternative - if you don't want to move `\Program Files\nodejs\`.

As admin: `mkdir d:\.pnpm-store\`, `c:`, `cd "\Program Files\nodejs\"`, `mklink /D pnpm-global d:\.pnpm-store\`

## Still open issue

`WARN  EXDEV: cross-device link not permitted, link`. Error not output in human readable form, but just `[object Object]`.

```
$ pnpm install -g github-release-from-changelog
 WARN  Refetching C:\Users\Oliver\.pnpm-store\2\registry.npmjs.org\mime\1.6.0 to store, as it was modified
 WARN  Refetching C:\Users\Oliver\.pnpm-store\2\registry.npmjs.org\netrc\0.1.4 to store, as it was modified
 WARN  Refetching C:\Users\Oliver\.pnpm-store\2\registry.npmjs.org\https-proxy-agent\1.0.0 to store, as it was modified
 WARN  Refetching C:\Users\Oliver\.pnpm-store\2\registry.npmjs.org\extend\3.0.1 to store, as it was modified
Adding 19 packages to node_modules
 WARN  EXDEV: cross-device link not permitted, link 'C:\Users\Oliver\.pnpm-store\2\registry.npmjs.org\github-release-from-changelog\1.3.0\node_modules\github-release-from-changelog\package.json' -> 'C:\Program Files\nodejs\pnpm-global\1\node_modules\.registry.npmjs.org\github-release-from-changelog\1.3.0\node_ modules\github-release-from-changelog+stage\package.json'
Falling back to copying packages from store
 ERROR  [object Object]
Resolving: total 20, reused 11, downloaded 5
```

**Comment by webstractions** [comment] 2017-12-10 19:42
I can confirm that the Insecure Workaround provided by @koppor does work for global packages. Needed that fix just to update `pnpm` to 1.23.2. 

I am wondering how `npm` writes to this folder without having to change folder permissions.

**Comment by Lodin** [comment] 2017-12-15 22:45
@webstractions AFAIK, npm doesn't write anything to `C:\Program Files\nodejs\`. While it is installed to this folder during nodejs installation, it writes all global packages to `C:\Users\<username>\AppData\Roaming\npm\node_modules`, that doesn't require any special permissions.

**Comment by webstractions** [comment] 2017-12-16 00:24
@Lodin That might be true. But I am seeing packages that have been written in `C:\Program Files\nodejs\node_modules\npm\node_modules` folder.

**Comment by Lodin** [comment] 2017-12-16 08:13
@webstractions I see them too, but since I have installed no one of them, I guess they are packages used by npm itself.

**Comment by webstractions** [comment] 2017-12-16 17:11
@Lodin Okay. That makes sense. Consider my brain "fully wrapped" on that point. =)

**Comment by TigersWay** [comment] 2017-12-21 06:16
@zkochan Just checking back again (and more than willing to test anything)...  But it seems we did not make any progress on this line.
Anyone? Anyone succeeded to have everything normally installed on one disk and projects on another?

**Comment by TigersWay** [comment] 2018-01-05 07:03
Stubborn :-) and I had other troubles, I found/choose another path:
`nvm `(https://github.com/coreybutler/nvm-windows) & `npm install -g pnpm --ignore-scripts`

I now have my <D:\.pnpm-store>, hardlinks and junctions, all working!

**Comment by NearAutomata** [comment] 2018-05-20 15:01
I just stumbled upon this issue since I noticed in #1175 that npm writes to `AppData` not like pnpm. Unfortunately neither a soft link, nor a junction `C:\Program Files\nodejs\pnpm-global <<==>> C:\Users\Near\pnpm-global` helped to alleviate this issue since pnpm cannot be executed anymore.

Furthermore I am not likely to take the insecure workaround for obvious reasons. I'll give it a try by running global installations (and `pnpm link` commands) in an elevated cmd. Luckily this doesn't happen too often.

Nevertheless I'd appreciate a change such that global packages are written to `AppData` similar to npm.

**Comment by zkochan** [comment] 2018-06-24 15:04
I think I figured it out, global packages should be installed to `${APPDATA}\npm` but I am not sure about other systems.

**Closed** 2018-06-24 18:35 UTC
Labels: bug/windows, help wanted, in progress

**Comment by zkochan** [comment] 2018-06-24 19:08
:ship: 2.9.0

**Comment by TigersWay** [comment] 2018-07-11 10:34
Global packages should be installed to the <prefix> folder (https://docs.npmjs.com/files/folders#prefix-configuration)
#1264

**Comment by ivahidmontazer** [comment] 2018-12-03 12:02
You need to change your security options for user in **Windows**: 
Right Click

The Folder > Properties > Security Tab

Click on

Edit to change Permissions > Select User

**Comment by M-kadi** [comment] 2020-08-26 12:14
on windows 10 👍

From Start Menu : type "CMD" then  "run as administrator"
