### ISSUE TITLE
Recursive Uninstall Not Working Correctly

### ISSUE THREAD

**Issue by dschnare** [pnpm/pnpm#1525] opened 2018-11-30 15:07 UTC
### Code to reproduce the issue:

Attempt to recursively uninstall a package from another package:

```
pnpm recursive uninstall @labs/valiators --filter @omd/api
```

### Expected behavior:

The `@labs/validators` dependency should be removed from the `package.json` file in `@omd/api` and the hardlink deleted.

### Actual behavior:

Nothing. Says "Already up to date" and the `package.json` file is untouched in `@omd/api` and the hardlink is still there.

### Additional information:

 - `node -v` prints: v10.13.0
 - Windows, OS X, or Linux?: Mac OSX Mojave 10.14.1

**Comment by zkochan** [comment] 2018-11-30 18:54
Do you use a shared `shrinkwrap.yaml`? I mean, do you use the `shared-workspace-shrinkwrap=true` config?

**Comment by dschnare** [comment] 2018-12-01 16:03
No. Separate shrinkwrap file in each package.

**Comment by zkochan** [comment] 2018-12-01 18:08
I cannot reproduce it. Could you create a sample repo?

**Comment by zkochan** [comment] 2019-07-15 19:53
This was probably fixed by 066910b6dc3bb08578ca704cdd08f580d3dba1e2

**Closed** 2019-07-15 19:53 UTC
Labels: area: multi-package repo, state: needs steps to repro
