### ISSUE TITLE
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with ...

### ISSUE THREAD

**Issue by ValeryG** [pnpm/pnpm#6526] opened 2023-05-10 16:00 UTC
In monoreposotory getting following error
```
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/package1/package.json
```

### pnpm version:

Error is not happening with pnpm ver 7 but happens in pnpm ver 8.4 & 8.5 on UBUNTU only (when running in GitHub actions). 

The same version on the same repo is working just fine on Mac.

node version: 18.16

Unfortunately repository is private so I cannot provide it for debugging, but would be happy to try any suggestion or provide as much of info I can.

- I did re-build `pnpm-lock.yaml`  and have correct version of it when running `pnpm I --forzen-lockfine`.
- My .npmrc has `strict-peer-dependencies=false`

**Comment by zkochan** [comment] 2023-05-10 23:06
Do you have `node-linker` set to `hoisted`?

**Comment by zkochan** [comment] 2023-05-13 01:14
Probably same as https://github.com/pnpm/pnpm/issues/6312

**Comment by ValeryG** [comment] 2023-05-15 20:34
with 8.5.1 getting same error in Ubuntu as before, but now it is telling me failure reason: 
```
Scope: all 20 workspace projects
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/core/core/package.json

Failure reason:
specifiers in the lockfile ({}) don't match specs in package.json ({"vue":"^3.2.47"})
Error: Process completed with exit code 1.
```

**Comment by jakebailey** [comment] 2023-05-15 20:35
Might be the bug fixed in my first commit of #6468?

**Comment by zkochan** [comment] 2023-05-15 20:55
I don't know what is happening. It would be great to have a repro repo. Maybe try to create a workspace with only package.json files and remove all private dependencies. It might be enough just to include the `packages/core/core/package.json` and `package.json` from the root of the monorepo.

**Comment by ValeryG** [comment] 2023-05-15 21:26
https://github.com/ValeryG/pnpm8-issue  - but of course the issue is not reproducible there. CI just works as expected on PR  workflow :( https://github.com/ValeryG/pnpm8-issue/actions/runs/4985311560/jobs/8924752920

**Comment by ValeryG** [comment] 2023-05-16 13:02
yes, that was it. When I am setting `auto-install-peers` to false - no error in ubuntu run.

**Comment by zkochan** [comment] 2023-05-16 23:50
your error message said

> specifiers in the lockfile ({}) don't match specs in package.json ({"vue":"^3.2.47"})

If you look in you lockfile, at `importers[packages/core/core].dependencies`. Is there no vue?

**Comment by zkochan** [comment] 2023-05-17 00:58
Closing this as it is a duplicate of #6312

**Closed by zkochan** 2023-05-17 00:58 UTC
Labels: type: bug
