### ISSUE TITLE
pnpx only works on 'master' branch when running from GitHub

### ISSUE THREAD

**Issue by TranquilMarmot** [pnpm/pnpm#3503] opened 2021-06-04 06:02 UTC
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

It has become common practice to use `main` as the default branch for a git repo instead of `master`:

https://github.com/github/renaming

However, currently running `pnpx github:username/repo` will result in an error if there is no `master` branch:

```
➜  ~ pnpx github:tranquilmarmot/pnpm-main-test
✔ Install the following package: github:tranquilmarmot/pnpm-main-test? (Y/n) · true

 ERROR  Could not resolve master to a commit of git://github.com/tranquilmarmot/pnpm-main-test.git.
at resolveRefFromRefs         /path/to/pnpm/dist/pnpm.cjs:61492  throw new Error(`Could n…
at resolveRef                 /path/to/pnpm/dist/pnpm.cjs:61486  return resolveRefFromRef…
at processTicksAndRejections  node:internal/process/task_queues:96

at async resolveGit           /path/to/pnpm/dist/pnpm.cjs:61437  const commit = await res…
at resolve                    /path/to/pnpm/dist/pnpm.cjs:64815  const resolution = (_a =…
at async run                  /path/to/pnpm/dist/pnpm.cjs:87926  resolve(await operation);
```

I've set up [TranquilMarmot/pnpm-main-test](https://github.com/TranquilMarmot/pnpm-main-test) as a minimal repro repo:

```
pnpx github:tranquilmarmot/pnpm-main-test
```

**Describe the solution you'd like**

`pnpx` should _at least_ look for a `main` branch before failing. It seems like this is what `npx` does but I'm not sure.

**Describe the drawbacks of your solution**

I'm not sure how feasible it is to check for branches when running `pnpx`. It might be easy to fallback to checking `main` if the command fails against `master`.

**Comment by TranquilMarmot** [comment] 2021-06-04 16:42
Here is where `pnpm` currently defaults to `master`:

https://github.com/pnpm/pnpm/blob/a468d2b3f8e4a456b3e57ad8a013af65b29c0484/packages/git-resolver/src/index.ts#L18-L21

Would it be possible to just `try` / `catch` here and try again with `main`? 🤔

**Comment by zkochan** [comment] 2021-06-04 20:33
Duplicate of https://github.com/pnpm/pnpm/issues/3199

**Closed** 2021-06-05 19:46 UTC
Labels: type: feature

**Comment by zkochan** [comment] 2021-06-05 23:49
:ship: 6.7.2
