### ISSUE TITLE
No warning about missing peer dependencies of `semantic-ui`.

### ISSUE THREAD

**Issue by cdfa** [pnpm/pnpm#1753] opened 2019-04-01 18:32 UTC
### Code to reproduce the issue:
1. `pnpm init`
2. pnpm i --save-dev `gulp@^3.9.1` `less` (following `semantic-ui`'s installation instructions [here](https://semantic-ui.com/introduction/getting-started.html)) and adding `less`.
3. pnpm i --save-dev semantic-ui

### Expected behavior:
The interactive `semantic-ui` install script (shown on the installation instructions page) gets executed and `pnpm` warns about `semantic-ui`'s missing peer dependencies.

### Actual behavior:
The log says an install script is run, but I don't get to see it. Additionally, `pnpm` doesn't warn about missing peer dependencies.

### Additional information:
`npm` does not warn about missing dependencies either, presumably because they're also normal dependencies for `semantic-ui` and are therefore present in `./node_modules`

 - `node -v` prints: `8.12.0`
 - Windows, OS X, or Linux?: Linux

**Comment by mcmxcdev** [comment] 2022-05-20 08:44
I can't reproduce this unfortunately because my node version is not compatible with the packages listed and runs into an error.
But missing peer dependencies are listed consistently with the latest pnpm version. I think we can close this.

**Comment by zkochan** [comment] 2022-05-20 23:19
I don't think semantic-ui is even maintained. Last release was 4 years ago.

**Closed by zkochan** 2022-05-20 23:19 UTC
Labels: area: peers
