### ISSUE TITLE
pnpm recursive not picking the dependent package

### ISSUE THREAD

**Issue by sunil-jhamnani** [pnpm/pnpm#2162] opened 2019-11-17 17:46 UTC
### pnpm version:
4.2.2
### Code to reproduce the issue:
`pnpm recursive --filter ./packages --workspace-concurrency 1 run build`

I am a bit new to pnpm and got a project I am working on using pnpm. I am running the above command which runs the build script for all the packages in the packages folder. 
All the cross dependencies are working fine except for 1 package which is getting used in every other. The build script should run on that package first which is not happening. 
Can anyone help me what could be the problem or what should be the correct place to debug?
I checked few things like package.json file, pnpm-workspace.yaml, import statements but all seems to be fine

error which I get:
```
Cannot find module '@abc/plugin'.
import { xyz } from '@abc/plugin'
```

Note: Its a typescript based project and if I try adding a // ts-ignore tag above the import statement it works but I kind of feel thats not the correct approach.  

 - `node -v` prints: v12.6.0
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment] 2019-11-17 17:49
Is that package inside the `packages` directory as well?

How is that package specified in the package.json of the dependent packages? As a local dependency (via file: or link:)?

**Comment by sunil-jhamnani** [comment] 2019-11-17 18:32
Is that package inside the packages directory as well?
Yes.
How is that package specified in the package.json of the dependent packages? As a local dependency (via file: or link:)?
It is specified as the package name.

Some more info:
Directory Structure:
```
packages
    @abc  
        plugin
        plugin1
        plugin2
```
plugin is used in both plugin1 and plugin2
packge.json of plugin1
```
"dependencies": {
   '@abc/plugin': '^1.0.0'
}
```

**Comment by sunil-jhamnani** [comment] 2019-11-21 12:52
@zkochan 
Anything on this?

**Comment by zkochan** [comment] 2019-12-15 10:50
To debug this, check this line:

https://github.com/pnpm/pnpm/blob/9f26da3c7a271e7b583197684b0a6db32c88af71/packages/plugin-commands-recursive/src/recursive.ts#L793

It is where pnpm decides in what order to run the workspace packages

**Comment by javier-garcia-meteologica** [comment] 2021-06-03 12:35
I just experienced this same issue. The problem was caused by cyclic dependencies.

If there are cyclic dependencies, graphSequencer always returns `{ safe: false, cycles: [...], chunks: [...] }` but `cycles` may be empty if the cycles are too complicated. Pnpm is ignoring this information.

At a minimum pnpm should print a warning if it detects cyclic dependencies and I'm personally inclined to make pnpm throw an error (unless `--parallel` is used).

- Cyclic dependencies are harder to debug as time passes and more cycles are added
- The problem may stay silent for a while and then it can slowly build a snowball of problems
- One big appeal for pnpm is to be strict by default

For instance, some of our packages produce (legacy) AMD bundles that include all their dependencies. If there are cyclic dependencies, the graph will be wrong and dependencies will be built out of order. The dependencies that should have been rebuilt before the parent package didn't cause the parent build to fail, because the parent build used stale builds.

There are 3 references to `graph-sequencer in the whole codebase. Should we place an assertion in each of these lines or should we create a wrapper package @pnpm/graph-sequencer to avoid duplication?

https://github.com/pnpm/pnpm/blob/a468d2b3f8e4a456b3e57ad8a013af65b29c0484/packages/sort-packages/src/index.ts#L63-L67

https://github.com/pnpm/pnpm/blob/a1a03d1457d8b28bdb8a1bdb9e00288bcb0caf12/packages/build-modules/src/index.ts#L45-L49

https://github.com/pnpm/pnpm/blob/a1a03d1457d8b28bdb8a1bdb9e00288bcb0caf12/packages/plugin-commands-rebuild/src/implementation/index.ts#L258-L262

**Comment by zkochan** [comment] 2021-06-21 21:54
merged https://github.com/pnpm/pnpm/pull/3537

**Closed by zkochan** 2021-06-21 21:54 UTC
Labels: area: monorepo
