### ISSUE TITLE
 pnpm PnP complaining about Node.js core modules prefixed with "node:

### ISSUE THREAD

**Issue by coltonehrman** [pnpm/pnpm#7275] opened 2023-11-02 16:14 UTC
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

8.10.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

You should be able to reproduce this issue with a Next.js 13.5.6 app installed with pnpm using the PnP node-linker. I am running into this issue on a corporate app, so cannot share details.

### Describe the Bug

Linking out to other issue opened against Yarn PnP - https://github.com/yarnpkg/berry/issues/5919
Adding issue here for visibility and cross-referencing.

### Expected Behavior

PnP does not complain about `node:` core modules.

### Which Node.js version are you using?

18.18.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Mister-Hope** [comment] 2024-01-28 07:51
I think this is duplicate of #4982

**Closed** 2024-08-10 22:41 UTC
Labels: type: bug
