### ISSUE TITLE
error should be warning: No package.json was found

### ISSUE THREAD

**Issue by milahu** [pnpm/pnpm#3728] opened 2021-08-30 09:55 UTC
### pnpm version:
6.10.0

### Code to reproduce the issue:

```
git clone --depth 1 https://github.com/vitejs/vite.git

cd vite/packages/vite

pnpm install 
# WARN  deprecated acorn-numeric-separator@0.3.6: acorn>=7.4 supports numeric separators
# ERROR  No package.json (or package.yaml, or package.json5) was found in "types".
# Progress: resolved 50, reused 44, downloaded 0, added 0

ls node_modules | wc -l
# ls: cannot access 'node_modules': No such file or directory
# 0

ls types
# alias.d.ts     commonjs.d.ts     dynamicImportVars.d.ts  importMeta.d.ts
# anymatch.d.ts  connect.d.ts      hmrPayload.d.ts         shims.d.ts
# chokidar.d.ts  customEvent.d.ts  http-proxy.d.ts         terser.d.ts
```

### Expected behavior:

> WARN  No package.json (or package.yaml, or package.json5) was found in "types".

yarn allows packages without a package.json file

### Actual behavior:

> ERROR  No package.json (or package.yaml, or package.json5) was found in "types".

also: pnpm silently fails when a `.pnpm-debug.log` file is present

### workaround

```
echo '{ "name": "some-package", "version": "0.0.1" }' >types/package.json
```

yarn requires name and version as soon as a package.json is present

**Comment by rimmartin** [comment] 2021-09-15 14:37
yarn is starting to fail on this too.

It would be nice if pnpm allowed me to include dependencies such as c++ header only projects that don't have and don't need a package.json manifest in them.

Would open up a whole world of useful projects to be simple dependencies if pnpm allowed it

**Comment by boardend** [comment] 2021-09-20 14:49
This looks like a duplicate of https://github.com/pnpm/pnpm/issues/1866

**Closed** 2021-09-20 18:40 UTC
Labels: type: bug
