### ISSUE TITLE
Patch DX: Make it as simple as patch-package

### ISSUE THREAD

**Issue by robertherber** [pnpm/pnpm#5686] opened 2022-11-24 16:07 UTC
The DX of `patch` and `patch-commit` is trailing [patch-package](https://github.com/ds300/patch-package) by a lot, and makes it very cumbersome to use. The use case for using patching is making commitable changes (a lot) simpler than having to fork a package.

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer I want to be able to patch packages in an effortless way.

**Describe the solution you'd like**

I'd like to create patches as easy as with `patch-package` - just modifying `node_modules` is effortless.

And the upgrade process is even more cumbersome: 
- Having to remove the existing patch to be able to upgrade adds a lot to the complexity (`patch-package` just gives a warning - or an error if the patch cannot be applied anymore).
- I don't currently see an easy way to reapply an existing patch when upgrading a package. One has to go through the entire process of adding a new patch, and manually applying the change again.

**Comment by lili21** [comment] 2022-11-30 03:42
Agree. `patch-package` is more easier

**Comment by zkochan** [comment] 2022-12-13 01:36
I think it is doable.

In the content-addressable store we have an index file for every package. An index file is a map of hashes. So we know what files each package has and we have a checksum calculated from the content of each file. We can use this information to check whether a package inside node_modules was modified.

We'd have to scan the node_modules and find any modified dependencies. Then we'd have to automatically create a new directory with the non-modified package and generate a patch.

**Comment by u3u** [comment] 2023-01-04 06:23
> * Having to remove the existing patch to be able to upgrade adds a lot to the complexity (`patch-package` just gives a warning - or an error if the patch cannot be applied anymore).
> * I don't currently see an easy way to reapply an existing patch when upgrading a package. One has to go through the entire process of adding a new patch, and manually applying the change again.

It's really annoying that patches don't apply automatically when upgrading dependencies, so for now I set [`pnpm.allowNonAppliedPatches`](https://pnpm.io/package_json#pnpmallownonappliedpatches) to `true` and then manually change the version number in the `patch` file and [`pnpm.patchedDependencies`](https://pnpm.io/package_json#pnpmpatcheddependencies)

**Comment by robertherber** [comment] 2023-01-04 08:01
@u3u I didn't even know about `allowNonAppliedPatches`, until now I had to repatch every time which was a real struggle. Thanks, that will actually make it bearable for me until it can be improved further 🙏

**Comment by await-ovo** [comment] 2023-01-09 10:36
For reapply case, is it possible to add an option(eg `--force`) that determines whether to use an existing patch file or to restart the patch ?

Assume the following project:

```
// package.json
{
  "name": "test-pnpm-patch",
  "dependencies": {
    "express": "^4.18.2"
  },
  "pnpm": {
    "patchedDependencies": {
      "express@4.18.2": "patches/express@4.18.2.patch"
    }
  }
}
// patches/express@4.18.2.patch
diff --git a/lib/express.js b/lib/express.js
index 6bbc9f3b6b4eacd0c1356b1dfcfc303356a29933..9c1c43033ca54ea4c71798dc4bbd4f3122966721 100644
--- a/lib/express.js
+++ b/lib/express.js
@@ -10,6 +10,8 @@ var Router = require('./router');
 var req = require('./request');
 var res = require('./response');
 
+console.log(`patch express 111`)
+
 /**
  * Expose `createApplication()`.
  */
```

If we run`pnpm patch express@4.18.2`, it will check whether the corresponding patch file already exists in package.json. If so, then apply the patch to the temp dir that we need to continue to modify later. In this way, the files we need to modify will automatically carry the changes made in the last patch,

If we run `pnpm patch  express@4.18.2 --force`, it will ignore the existing patch file.


Hi @zkochan, What do you think of this approach? if there is no problem, I'd happy to send a PR ~

**Comment by zkochan** [comment] 2023-01-09 23:08
@await-ovo as a solution to #5632, sounds good. But the force option seems confusing.

**Comment by karlhorky** [comment] 2023-03-10 16:52
Getting the ease of use of `patch-package` would be great!

In case this is a complex / long-running feature request, I have opened a request for a more incremental step here, which avoids the problems with temporary directories:

- https://github.com/pnpm/pnpm/issues/6206

**Comment by karlhorky** [comment] 2023-03-10 17:20
@await-ovo Also seems like applying the previous patch (PR #5906) is currently broken with `pnpm@7.29.1`:

- https://github.com/pnpm/pnpm/pull/5906#issuecomment-1464033763

**Comment by await-ovo** [comment] 2023-03-12 02:28
> @await-ovo Also seems like applying the previous patch (PR #5906) is currently broken with `pnpm@7.29.1`:
> 
> * [feat(plugin-commands-patching): apply existed patch file when re-patch #5906 (comment)](https://github.com/pnpm/pnpm/pull/5906#issuecomment-1464033763)

I'll check it later, can you provide the steps to reproduce the problem you encountered?  thanks a lot ~

**Comment by karlhorky** [comment] 2023-03-12 07:43
> I'll check it later, can you provide the steps to reproduce the problem you encountered?

Nice, thanks! I've edited [the comment](https://github.com/pnpm/pnpm/pull/5906#issuecomment-1464033763) with more detail about the reproduction steps.

**Comment by karlhorky** [comment] 2023-04-04 14:32
Now that old patches are reapplied, maybe DX improvements about the "upgrading" parts of this issue can be explored again, with detailed suggestions for solutions.

The following suggestions are actually beyond the capabilities of `patch-package`.

For example, 2 suggestions I would have for making failure cases into warnings are (assume an existing patch for `next@13.2.3` exists and the user upgrades to `next@13.2.4`):

1. If an existing patch can be applied to the new version, apply the patch automatically and print a warning that the user should A) rename the patch file B) update their `package.json` file
   1. Even better than a warning with 2 necessary manual user actions would be even a tty question "Patch for `next@13.2.3` can be applied cleanly to `next@13.2.4`. Upgrade patch?" which would update the patch file and the `package.json`
2. If the changed lines in an existing patch (lines added / removed) can be applied in a unique way to the new version without the "before" and "after" hashes matching, apply the patch and update the hashes automatically and print a warning  - eg. more like Git patches
   1. Could also have a tty question "Patch for `next@13.2.3` can be applied cleanly to `next@13.2.4`, but hashes didn't match. Apply and upgrade patch?" which would update the patch file and the `package.json`

@await-ovo @zkochan thoughts on these?

**Comment by karlhorky** [comment] 2023-04-07 13:59
## Workaround

In case this helps anyone, a useful command to make the upgrade process with `pnpm` patches a bit less painful - edits `package.json` to remove a particular patch, so that `pnpm install` works again:

```bash
# Use sed to remove all keys starting with `next@` in package.json
# under the path pnpm.patchedDependencies
sed -i -e '/"pnpm":/,/}/ {/"next@/d;}' package.json
```

**Comment by karlhorky** [comment] 2023-04-28 08:59
To demonstrate the problem of upgrading versions of a dependency and the patch not applying (although it's sometimes possible that the changes in the patch can be applied), check out the automated PR below from the Renovate bot.

Even if the changes in the patch could be applied, the version number in the patch file + `package.json` prevents this from "just working" and requires manual intervention from the user on dependency upgrades.

This is the problem that my robustness suggestions above are trying to solve.

- https://github.com/karlhorky/archive-webpage-browser-extension/pull/15

```
installing v2 tool node v18.16.0
linking tool node v18.16.0
node: v18.16.0 /usr/local/bin/node
npm: 9.5.1  /usr/local/bin/npm
Installed v2 /usr/local/buildpack/tools/v2/node.sh in 8 seconds
installing v2 tool pnpm v8.3.1
linking tool pnpm v8.3.1
8.3.1
Installed v2 /usr/local/buildpack/tools/v2/pnpm.sh in 4 seconds
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 9, reused 0, downloaded 9, added 0
Progress: resolved 12, reused 0, downloaded 12, added 0
Progress: resolved 13, reused 0, downloaded 12, added 0
Progress: resolved 29, reused 0, downloaded 17, added 0
Progress: resolved 39, reused 0, downloaded 26, added 0
Progress: resolved 57, reused 0, downloaded 41, added 0
Progress: resolved 68, reused 0, downloaded 48, added 0
Progress: resolved 80, reused 0, downloaded 57, added 0
Progress: resolved 100, reused 0, downloaded 77, added 0
Progress: resolved 106, reused 0, downloaded 99, added 0
Progress: resolved 106, reused 0, downloaded 100, added 0
Progress: resolved 116, reused 0, downloaded 102, added 0
.                                        |  WARN  deprecated sourcemap-codec@1.4.8
Progress: resolved 139, reused 0, downloaded 123, added 0
Progress: resolved 171, reused 0, downloaded 139, added 0
Progress: resolved 182, reused 0, downloaded 145, added 0
Progress: resolved 192, reused 0, downloaded 146, added 0
Progress: resolved 194, reused 0, downloaded 151, added 0
Progress: resolved 198, reused 0, downloaded 155, added 0
Progress: resolved 204, reused 0, downloaded 161, added 0
Progress: resolved 209, reused 0, downloaded 166, added 0
Progress: resolved 218, reused 0, downloaded 171, added 0
Progress: resolved 225, reused 0, downloaded 178, added 0
Progress: resolved 243, reused 0, downloaded 191, added 0
Progress: resolved 256, reused 0, downloaded 207, added 0
Progress: resolved 270, reused 0, downloaded 218, added 0
Progress: resolved 273, reused 0, downloaded 223, added 0
Progress: resolved 287, reused 0, downloaded 233, added 0
Progress: resolved 297, reused 0, downloaded 240, added 0
Progress: resolved 317, reused 0, downloaded 259, added 0
Progress: resolved 342, reused 0, downloaded 284, added 0
Progress: resolved 370, reused 0, downloaded 306, added 0
Progress: resolved 394, reused 0, downloaded 331, added 0
Progress: resolved 420, reused 0, downloaded 349, added 0
Progress: resolved 450, reused 0, downloaded 377, added 0
Progress: resolved 464, reused 0, downloaded 394, added 0
Progress: resolved 493, reused 0, downloaded 418, added 0
Progress: resolved 515, reused 0, downloaded 444, added 0
Progress: resolved 544, reused 0, downloaded 467, added 0
undefined
 ERR_PNPM_PATCH_NOT_APPLIED  The following patches were not applied: @vitejs/plugin-react@3.1.0

Either remove them from "patchedDependencies" or update them to match packages in your dependencies.
Progress: resolved 558, reused 0, downloaded 490, added 0
```

**Comment by karlhorky** [comment] 2023-08-08 12:41
## Workaround

Ok, finally encountered these errors enough to [do something about it](https://github.com/karlhorky/archive-webpage-browser-extension/pull/23/commits/0c161ef83dff9af6b160e4d4da2c5227825272ec).

In the commit linked above, I wrote a script that reads the versions from `.pnpm.patchedDependencies` in `package.json`, compares them against the new updated versions in `devDependencies` and `dependencies`, and then:

1. Removes the existing property from `pnpm.patchedDependencies`
2. Adds a new property to `pnpm.patchedDependencies` with the updated version number
3. Moves the patch file to the new version number
4. Update the pnpm lockfile with pnpm install

Bash script to fix `pnpm patch`: https://github.com/karlhorky/archive-webpage-browser-extension/blob/0c161ef83dff9af6b160e4d4da2c5227825272ec/scripts/fix-pnpm-patches.sh

I also wrote a GitHub Actions workflow step that runs this script and then commits the result:

GitHub Actions step to commit to Git: https://github.com/karlhorky/archive-webpage-browser-extension/blob/0c161ef83dff9af6b160e4d4da2c5227825272ec/.github/workflows/lint-check-types-and-build.yml#L18-L36

This looks like this - first commit upgrading dependencies by Renovate bot is broken, and then the script fixes the pnpm patches:

![Screenshot 2023-08-08 at 14 29 23](https://github.com/pnpm/pnpm/assets/1935696/286c7c80-180f-41c3-aefd-655df50d7b3d)

An example commit by the bot:

[karlhorky/archive-webpage-browser-extension@`bb17e8e` (#23)](https://github.com/karlhorky/archive-webpage-browser-extension/pull/23/commits/bb17e8e891d700420c4ebf4b725e5f9ca8403079)

![Screenshot 2023-08-08 at 14 30 20](https://github.com/pnpm/pnpm/assets/1935696/9ed2f23f-6e8e-46af-89e3-8090e37bfe95)

cc @await-ovo @zkochan would love to get feedback on this or for this same workflow to become a first-class feature in pnpm :)

**Comment by karlhorky** [comment] 2023-08-08 12:59
Reducing the pnpm surface area where these patch numbers / identifiers are kept would certainly minimize the problem.

At that point, then option 1 from [my suggestions from April 2023](https://github.com/pnpm/pnpm/issues/5686#issuecomment-1496081345) could be updated to behave pretty similarly to `patch-package` (apply patches for new versions as long as they apply, but print a warning):

> 1. If an existing patch can be applied to the new version, apply the patch automatically and print a warning that the user should A) rename the patch file B) update their `package.json` file C) run `pnpm install` to update the lockfile
>    1. Even better than a warning with 2 necessary manual user actions would be even a tty prompt "Patch for `next@13.2.3` can be applied cleanly to `next@13.2.4`. Upgrade patch?" which would rename the patch file, update the `package.json` and run `pnpm install`

To go beyond the DX of `patch-package`, my additional suggestions were:

> 2. If the changed lines in an existing patch (lines added / removed) can be applied in a unique way to the new version without the "before" and "after" hashes matching, create a new patch file with the new hashes and print a warning that a user should A) delete the old patch file B) update their `package.json` file C) run `pnpm install` to update the lockfile - eg. the idea here is to behave in a more robust / resilient way, more like Git merges
>     1. Could also have a tty prompt "Patch for `next@13.2.3` can be applied cleanly to `next@13.2.4`, but hashes didn't match. Apply and upgrade patch?" which would update the hashes in the patch file, rename the patch file, update the `package.json` and run `pnpm install`
> 3. If the changed lines in a hunk in an existing patch (lines added / removed) can be applied in a non-unique way to the new version, show user an interactive interface where they can choose the location that the hunk should be applied between the different possible matches, performing the hash updates, patch file renaming, `package.json` update and `pnpm install` described in `2.i.` above

**Comment by karlhorky** [comment] 2023-08-22 09:06
Seems like [`patch-package@8.0.0`](https://github.com/ds300/patch-package/releases/tag/v8.0.0) has a new feature `patch-package --partial` ([Partially applying a broken patch file](https://github.com/ds300/patch-package#partially-applying-a-broken-patch-file)), which applies only the hunks of the patch that apply and then emits errors for those hunks that did not apply:

> ### Partially applying a broken patch file
>
> Normally patch application is atomic per patch file. i.e. if a patch file contains an error anywhere then none of the changes in the patch file will be applied and saved to disk.
>
> This can be problematic if you have a patch with many changes and you want to keep some of them and update others.
>
> In this case you can use the `--partial` option. Patch-package will apply as many of the changes as it can and then leave it to you to fix the rest.
>
> Any errors encountered will be written to a file `./patch-package-errors.log` to help you keep track of what needs fixing.

This seems to be implemented here (internally, called `bestEffort`):

- [ds300/patch-package@`cced41a` (#474)](https://github.com/ds300/patch-package/pull/474/commits/cced41a37bdc14bc20e217fad844000431257f4d)

**Comment by karlhorky** [comment] 2023-08-22 10:10
I also wrote over in a `patch-package` issue about how `--partial` mode could be improved with interactive discarding of hunks, to reduce the amount users have to edit files in `node_modules/`:

- https://github.com/ds300/patch-package/issues/486

**Comment by karlhorky** [comment] 2023-11-25 17:03
In the meantime, before `pnpm patch` is fully robust, if anyone want to set up [my workaround above](https://github.com/pnpm/pnpm/issues/5686#issuecomment-1669538653), I also added a guide to set up a GitHub fine-grained personal access token for automatically committing in your repository:

- https://github.com/karlhorky/github-tricks#github-actions-push-to-pull-request-and-re-run-workflows

**Comment by Fryuni** [comment] 2023-12-19 19:55
> I've patched knockout, and running pnpm patch knockout checks out a fresh copy of knockout

You need to `pnpm patch knockout`, edit the folder it shows you, and then `pnpm patch-commit <folder>`.

It is a more convoluted process than `patch-package`, and that is the point of this issue.

**Comment by alfaproject** [comment] 2024-01-30 11:18
I'm now migrating from Yarn and one the things I love about patch-package is that I can just set a folder for the patches and that's it

**Comment by karlhorky** [comment] 2024-03-10 09:52
> 1. If an existing patch can be applied to the new version, apply the patch automatically and print a warning that the user should A) rename the patch file B) update their `package.json` file C) run `pnpm install` to update the lockfile

Following up on this suggestion from [my suggestions comment above](https://github.com/pnpm/pnpm/issues/5686#issuecomment-1496081345), to be clear, this is a feature of `patch-package` that is missing from `pnpm patch` that would be very useful:

Feature: Apply patches if the diff still applies to the new version (ignoring checksums at the top)

To demonstrate the `patch-package` feature, consider my patch below for `winston@3.11.0`:

`patches/winston+3.11.0.patch`

```diff
diff --git a/node_modules/winston/index.d.ts b/node_modules/winston/index.d.ts
index 929ef4a..9c5c53d 100644
--- a/node_modules/winston/index.d.ts
+++ b/node_modules/winston/index.d.ts
@@ -88,8 +88,9 @@ declare namespace winston {
     (message: string, callback: LogCallback): Logger;
     (message: string, meta: any, callback: LogCallback): Logger;
     (message: string, ...meta: any[]): Logger;
-    (message: any): Logger;
-    (infoObject: object): Logger;
+    // Winston cannot log Errors in first position https://github.com/winstonjs/winston/issues/1338
+    // (message: any): Logger;
+    // (infoObject: object): Logger;
   }
 
   interface LoggerOptions {
```

`patch-package` will apply this patch to `winston@3.12.0` with no errors (only a warning) even though the checksums on the `index` line do not match:

```
$ patch-package
patch-package 8.0.0
Applying patches...
winston@3.11.0 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    winston@3.11.0

  applied to

    winston@3.12.0
  
  At path
  
    node_modules/winston

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package winston

  to update the version in the patch file name and make this warning go away.
```

Then running `npm run patch-package winston` will:

1. Re-run the patching process
2. Create a new patch file for `winston@3.12.0` (the only line that will be changed here will be the checksums on the `index ...` line (line 2 in the patch above)
3. Delete the old patch file for `winston@3.11.0`

(caveat: deleting feature is [currently broken](https://github.com/ds300/patch-package/issues/480))

@zkochan @await-ovo what are your thoughts about adopting this feature as a start?

**Comment by braebo** [comment] 2024-06-05 21:59
I don't see how `pnpm-patch` is a usable feature when it blows up your repo as soon as you bump your deps.

Or am I just missing something?

**Comment by zkochan** [comment] 2024-07-17 00:05
Here pnpm picks the patch file by name and version:

https://github.com/pnpm/pnpm/blob/726753f05d6512c93dd6f26787a92891ded59533/pkg-manager/resolve-dependencies/src/resolveDependencies.ts#L1342

Maybe if there is only one version of the package in node_modules,  we can save it without a version and try applying it to any versions of the package. If there are multiple versions, maybe the `pnpm patch` command could ask the user if the patch should be applied to all versions.

**Comment by zkochan** [comment] 2024-08-01 12:28
Related PR: https://github.com/pnpm/pnpm/pull/8337

**Comment by zkochan** [comment] 2024-08-07 00:38
Try pnpm 9.7

**Comment by karlhorky** [comment] 2024-09-09 16:04
@zkochan I tried [pnpm 9.7](https://github.com/pnpm/pnpm/releases/tag/v9.7.0) with the following 2 features:

- #8337
- new default edit dir `node_modules/.pnpm_patches/pkg[@version]` #8379

Feedback: both work great! Thanks to you and @KSXGitHub 🙌 

Some details, for people who want to try them out:

## Apply patch to all versions

The new behavior will cause the patch file to be created without a version number (both in the `patches/` directory and also in the `pnpm.patchedDependencies` references in `package.json`):

`package.json`

```diff
 {
   "pnpm": {
     "patchedDependencies": {
-      "@vitejs/plugin-react@4.3.1": "patches/@vitejs__plugin-react@4.3.1.patch",
+      "@vitejs/plugin-react": "patches/@vitejs__plugin-react.patch",
```

So if you have existing patches and want to opt in to the new behavior to apply patches to all versions, then rename your patch files and update your `package.json` accordingly.

## New default edit dir `node_modules/.pnpm_patches/pkg[@version]`

This is great, your editor settings for the project `node_modules` (eg. no formatting on save) will be respected for the patch files:

```bash
$ pnpm patch prettier
Patch: You can now edit the package at:

  /Users/k/p/archive-webpage-browser-extension/node_modules/.pnpm_patches/prettier@3.3.3

To commit your changes, run:

  pnpm patch-commit '/Users/k/p/archive-webpage-browser-extension/node_modules/.pnpm_patches/prettier@3.3.3'
```

One small detail - the folder path is not cmd-clickable in VS Code (maybe because of the dashed / colored styling?). I opened an issue here:

- https://github.com/pnpm/pnpm/issues/8513

**Comment by karlhorky** [comment] 2024-09-09 16:35
With this latest changes in [pnpm 9.7](https://github.com/pnpm/pnpm/releases/tag/v9.7.0), I could imagine that this issue could finally be closed.

@robertherber @u3u @matthew-dean what do you think about closing this issue now?

**Comment by stephenwade** [comment] 2024-09-09 16:43
I want to use the new feature, but I need `pnpm install` to fail if the patches don't apply and there is no way to do that.

**Comment by karlhorky** [comment] 2024-09-09 16:57
Ah yeah, "`pnpm patch`: Fail on patch non-application" would be a good last feature request, that sounds reasonable.

Could also be an option, in case the pnpm decides that this should not be the default behavior.

**Comment by Fryuni** [comment] 2024-09-09 19:56
Since we got `pnpm patch prettier` we could also have `pnpm patch-commit prettier` looking at that same default folder, failing if it isn't there.

**Comment by zkochan** [comment] 2024-09-10 01:00
I do not have a strong opinion about the install fail. One of the issues in this thread was exactly about the install failure. As a compromise, instead of a failure we can probably finish the install but exit the process with a non-zero exit code. But I also can imagine a scenario where a project might want to have a predefined set of patches and it could be fine if not all are in use.

**Comment by stephenwade** [comment] 2024-09-10 01:10
@zkochan I found this setting: [pnpm.allowNonAppliedPackages](https://pnpm.io/package_json#pnpmallownonappliedpatches). I set it to `false` but the install still succeeds. Can you change the new behavior to respect this setting?

**Comment by tobiasdiez** [comment] 2024-09-11 08:12
> With this latest changes in [pnpm 9.7](https://github.com/pnpm/pnpm/releases/tag/v9.7.0) (also check out [my comment above](https://github.com/pnpm/pnpm/issues/5686#issuecomment-2338512915)), I could imagine that this issue could finally be closed.
> 
> @robertherber @u3u @matthew-dean what do you think about closing this issue now?

I agree the recent changes are a huge step in the right direction. But the following issue from the issue description are not yet addressed, right?

>    I don't currently see an easy way to reapply an existing patch when upgrading a package. One has to go through the entire process of adding a new patch, and manually applying the change again.

**Comment by karlhorky** [comment] 2024-09-11 08:24
> But the following issue from the issue description is not yet addressed, right?
> 
> > I don't currently see an easy way to reapply an existing patch when upgrading a package. One has to go through the entire process of adding a new patch, and manually applying the change again.

No, this has now been fixed. Check pnpm 9.7 and [my comment above](https://github.com/pnpm/pnpm/issues/5686#issuecomment-2338512915)

**Comment by alfaproject** [comment] 2024-09-11 08:29
For me, there are 2 important things that I rely from patch-package:
1. an option to fail the modules installation if the patches don't apply cleanly (enabled on CI)
2. an option to install patches coming from a dependent node module (so, custom patch folder ./node_modules/my-org-patches)

**Comment by robertherber** [comment] 2024-09-12 15:23
> With this latest changes in [pnpm 9.7](https://github.com/pnpm/pnpm/releases/tag/v9.7.0) (also check out [my comment above](https://github.com/pnpm/pnpm/issues/5686#issuecomment-2338512915)), I could imagine that this issue could finally be closed.
> o> @robertherber @u3u @matthew-dean what do you think about closing this issue now?

I'm glad to see this happening, thanks for the nice work! 👍 We've since migrated to bun for almost everything so I don't have anything to add to the discussion whether the issue should remain open or not.

**Comment by zkochan** [comment] 2024-09-15 10:00
I have created a new issue for [pnpm.allowNonAppliedPackages](https://github.com/pnpm/pnpm/issues/8528). If you have other requests, feel free to create new issues.

**Closed by zkochan** 2024-09-15 10:00 UTC
Labels: type: feature
