### ISSUE TITLE
Microsoft defender found Trojan:Win32/Wacatac.B!ml in 9.11.0

### ISSUE THREAD

**Issue by user03497803549** [pnpm/pnpm#8562] opened 2024-09-23 06:22 UTC
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.11.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Reproduction steps

1. type and run "pnpm self-update" on win 11

### Describe the Bug

I want update pnpm from 9.10.0 to 9.11.0 and after type 'pnpm self-update' microsoft defender delete my new downloaded version.

### Expected Behavior

expected behavior is update to 9.11.0

### Which Node.js version are you using?

22.7.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by erolj** [comment] 2024-09-23 06:43
![Screenshot 2024-09-23 144102](https://github.com/user-attachments/assets/efd6747f-a96e-4be1-a658-14678083c4a2)

Experiencing the same problem.

**Comment by CalvinWilkinson** [comment] 2024-09-23 09:13
I have the same issue as of this morning.

I originally already had pnpm installed, but when I went to run a command, I got the error. So I uninstalled pnpm and then tried to reinstall it using the `Invoke-WebRequest https://get.pnpm.io/install.ps1 -UseBasicParsing | Invoke-Expression` PowerShell command in the Windows terminal and got the same block from Windows Defender as well as the item being quarantined.

<img width="375" alt="image" src="https://github.com/user-attachments/assets/96d7da2c-437e-4460-bea3-a6f34b7238b0">

**Comment by glektarssza** [comment] 2024-09-23 14:12
Seeing this as well when I tried to update this morning via `scoop update -a`.

![image](https://github.com/user-attachments/assets/860a9d20-2dba-47ef-a848-99abeb60d756)

**Comment by glektarssza** [comment] 2024-09-23 14:36
Did some digging and not seeing anything suspicious in the binary or via some analysis tools I have access to. This smells like a false positive but I'm not an expert in this field so I'll leave this to the experts.

> Multiple several issues were opened. I guess the only way to solve this would be to recommend installing the non-exe version of node.js on windows. You can do that with corepack or npm. For instance:
> 
> ```
> npm i -gf pnpm
> ```
> 
> We can update our installation page.

This is probably the best way to solve the issue for now since this skips the binary entirely and just installs the source code directly.

**Comment by w3bdesign** [comment] 2024-09-23 19:15
Duplicate of this pinned issue:

https://github.com/pnpm/pnpm/issues/8559

**Closed** 2024-09-23 20:54 UTC
Labels: type: bug
