### ISSUE TITLE
full-icu installation hangs

### ISSUE THREAD

**Issue by dizel3d** [pnpm/pnpm#1816] opened 2019-05-07 11:49 UTC
### pnpm version:
3.2.0

### Code to reproduce the issue:
```
pnpm install full-icu
```

### Expected behavior:
`full-icu` should be installed

### Actual behavior:
Installation hangs on postinstall step:
```
node_modules/.registry.npmjs.org/full-icu/1.2.1/node_modules/full-icu: Running postinstall script...
```

### Additional information:
 - `node -v` prints: 8.6.0
 - Windows, OS X, or Linux?: macOS 10.13.6

**Comment by zkochan** [comment] 2019-05-07 23:06
The issue is that the postinstall script runs `pnpm install icu4c-data@62l` but pnpm locks the store, so the other install hangs, so it is a dead lock.

A workaround it to use the `--no-lock` flag: 

```
pnpm install full-icu --no-lock
```

But I guess pnpm should unlock the store before running the lifecycle hooks. There is no reason to keep the store locked on that step

**Comment by donaldpipowitch** [comment] 2020-01-27 08:00
Ah, I just opened a bug on full-icu, because of this. So from pnpm's point of view, it is a pnpm bug, not a bug on full-icu's side? https://github.com/unicode-org/full-icu-npm/issues/44

**Comment by prantlf** [comment] 2020-05-25 21:34
@zkochan, the `--no-lock` workaround does not work for me, if installing full-icu globally:

    $ pnpm install -g full-icu --no-lock
    Packages: +1
    +
    Resolving: total 103, reused 99, downloaded 1, done
    node_modules/.pnpm/registry.npmjs.org/full-icu/1.3.1/node_modules/full-icu: Runninode_modules/.pnpm/registry.npmjs.org/full-icu/1.3.1/node_modules/full-icu: Running postinstall script, failed in 2s
    .../full-icu/1.3.1/node_modules/full-icu postinstall$ node postinstall.js
    │ npm install icu4c-data@65l (Node 12.16.3 and small-icu 65.1) -> icudt65l.dat
    │ full-icu$ /Users/test/.nvm/versions/node/v12.16.3/bin/node /Users/test/
    │ Packages: +1
    │ +
    │ Resolving: total 1, reused 0, downloaded 1, done
    │  WARN  icu4c-data has no binaries
    │ /Users/test/.nvm/versions/node/v12.16.3/pnpm-global/3/node_modules/.pnpm/r
    │ + icu4c-data 0.65.2
    │  •  (no icudt65l.dat at ‘../icu4c-data/icudt65l.dat’)
    │ /Users/test/.nvm/versions/node/v12.16.3/pnpm-global/3/node_modules/.pnpm/r
    │ 			throw Error('Somehow failed to install ' + icudat);
    │ 			^
    │ Error: Somehow failed to install icudt65l.dat
    │     at npmInstallNpm (/Users/test/.nvm/versions/node/v12.16.3/pnpm-global/
    │     at Object.<anonymous> (/Users/test/.nvm/versions/node/v12.16.3/pnpm-gl
    │     at Module._compile (internal/modules/cjs/loader.js:1133:30)
    │     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    │     at Module.load (internal/modules/cjs/loader.js:977:32)
    │     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    │     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main
    │     at internal/main/run_main_module.js:18:47
    └─ Failed in 2s
     ERROR  Command failed with exit code 1.

I used to run `node` with ICU from wherever I needed like this:

    node --icu-data-dir=$NVM_BIN/../lib/node_modules/full-icu

**Comment by arikon** [comment] 2020-06-18 07:19
> But I guess pnpm should unlock the store before running the lifecycle hooks. There is no reason to keep the store locked on that step

@zkochan Is this planned to be fixed?

**Comment by zkochan** [comment] 2020-06-18 07:56
It is fixed in v5

**Comment by SapirNassimi** [comment] 2021-04-20 17:09
And what about v6? 🙄

**Comment by zkochan** [comment] 2021-04-20 22:13
Neither the store nor the node_modules are locked in v5 or v6, so this issue is fixed. Please create new issues if you have any.

**Closed by zkochan** 2021-04-20 22:13 UTC
