### ISSUE TITLE
Not all required scripts installed after `pnpm i`. Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by vtereshyn** [pnpm/pnpm#7425] opened 2023-12-15 09:47 UTC
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.12.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vtereshyn/pnpm-jest-jsdom-canvas

### Reproduction steps

Having `pdfjs-dist` or `canvas` packages installed in your project run Jest tests in `jsdom` testing environment

Repository with reproduction attached:

```
pnpm install
pnpm test
```

### Describe the Bug

Not all required scripts run on Apple M2 Processor, which causes an error:

```
Cannot find module '../build/Release/canvas.node'
    Require stack:
    - /Users/..../pnpm-jest-jsdom-canvas/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/bindings.js
```

Please note that when using `npm`, everything works as expected. Also, on Intel processor everything works as expected either. Using `npm,` everything works as expected.

Issue happens only if you have `canvas` in your `node_modules` and in `jsdom` Jest environment. Removing `pdfjs-dist` and it's `peer dependency` will resolve an issue, but that is not a solution

### Expected Behavior

All required scripts run when running `pnpm install`

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Using M2 processor

**Comment by zkochan** [comment] 2023-12-16 15:04
I see this error in the `node-pre-gyp` output:

```
ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
```

The "unknown" part in the URL bothers me. Maybe pnpm doesn't pass some env variable to the executed script?

**Comment by vtereshyn** [comment] 2023-12-16 20:52
@zkochan might be. I couldn't investigate more profoundly, but there's definitely something wrong with how PNPM manages its scripts.

**Comment by javidmammad** [comment] 2023-12-18 05:36
The same for me whenever I switched to pnpm - and installed node_modules via it exaclty the same error took his place when I run the tests, with npm it was totally fine

    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "test": "jest",
    "react": "^18.2.0",
    
    pnpm version - 8.12.1

**Comment by javidmammad** [comment] 2023-12-18 06:47
> @zkochan The same for me - whenever I switched to pnpm - and installed node_modules via it exaclty the same error took its place when I run the tests, with npm it was totally fine
> 
> ```
> "jest": "^29.7.0",
> "jest-environment-jsdom": "^29.7.0",
> "test": "jest",
> "react": "^18.2.0",
> 
> pnpm - 8.12.1
> node - 20.9.0
> 
> OS-macos
> ```

I found the issue in my project, we have react-pdf installed. Whenever I remove - the problem is disappearing. So probably having similar packages causing the issue

**Comment by javidmammad** [comment] 2023-12-18 07:24
@vtereshyn 
Try:
1. brew install pkg-config cairo pango libpng jpeg giflib librsvg
2. remove node_modules
3. pnpm install
4. pnpm rebuild

It resolves my issue
CC: @zkochan

**Comment by vtereshyn** [comment] 2023-12-18 09:21
@javidmammad I wonder if this is the solution because this error also appears on a CI. Of course, I can do that for Linux using some pretest script, but I don't have 100% confidence that this is correct way to solve that

But thank you for your suggestion!

**Comment by dlarr** [comment] 2023-12-19 15:54
Exact same error here, I am guessing my company proxy blocking this URL. 

So what's the work around ?

**Comment by zbjornson** [comment] 2024-01-05 19:08
> I see this error in the `node-pre-gyp` output:
> 
> ```
> ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
> ```
> 
> The "unknown" part in the URL bothers me. Maybe pnpm doesn't pass some env variable to the executed script?

Node-canvas maintainer here. The "unknown" is fine (that's your libc). The 404 is because you're on an ARM CPU, and node-canvas prebuilds aren't available for ARM. This is unrelated to the OP's issue.

**Comment by alvis** [comment] 2024-01-06 10:50
The issue is that the `install` script for the `canvas` package seems to be omitted when running `pnpm install`. To verify this, you can check the `canvas` folder within the `node_modules` directory. If you do not find a `built` folder, it means that the `install` script has been skipped.

This problem tends to occur during non-first-time installations. The root cause appears to me that it is a cache issue where pnpm mistakenly assumes that the package only needs to run the `install` script once during the first time installation and that any generated artifacts will be stored in the pnpm store. So, during subsequent installations, pnpm attempts to save time by merely cloning the stored artifacts, skipping the `install` script. However, in reality, the artifacts generated by the `install` script are left in the target folder, not in the store. Therefore, cloning misses these essential artifacts.

If I've misunderstood how pnpm works, please feel free to correct me, @zkochan.

@dlarr As my current workaround, I either run `pnpm rebuild` or `pnpm store prune` before `pnpm install`

**Comment by dlarr** [comment] 2024-01-08 10:42
@alvis thank for explanation it's very clear ! 

Though, if I must run pnpm store prune before pnpm install, I may loose any pnpm benefit no ? The scope here is in Jenkins CI environment.

I'll give this a try anyway.

**Comment by vtereshyn** [comment] 2024-01-08 10:44
The interesting part is that everything is good on Intel processors. This issue is reproducible on Apple processors if we are talking about Mac OS

**Comment by dlarr** [comment] 2024-01-08 10:51
> > I see this error in the `node-pre-gyp` output:
> > ```
> > ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The "unknown" part in the URL bothers me. Maybe pnpm doesn't pass some env variable to the executed script?
> 
> Node-canvas maintainer here. The "unknown" is fine (that's your libc). The 404 is because you're on an ARM CPU, and node-canvas prebuilds aren't available for ARM. This is unrelated to the OP's issue.

Hello @zbjornson Is there a way to modify the URL we hit. I work in a company where github is blocked by the proxy 

I don't have the unknown part, but I still  can't access this URL

```node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-x64.tar.gz failed, reason: getaddrinfo ENOTFOUND github.com```

Any environment wariable or .npmrc config would do it.

**Comment by zbjornson** [comment] 2024-01-08 17:03
You should be able to set `https_proxy` and `http_proxy` environment variables.

**Comment by dlarr** [comment] 2024-01-09 08:13
> You should be able to set `https_proxy` and `http_proxy` environment variables.

Thank you for the answer, but our proxy blocks github.  So that wont work. 

I can try to set these proxy to our company artifactory but I doubt this will work. I'll edit this comment to tell you the outcome

**Comment by dlarr** [comment] 2024-01-09 08:58
> @dlarr As my current workaround, I either run `pnpm rebuild` or `pnpm store prune` before `pnpm install`

I also tested this. The outcome didn't change either. Though I am not surprise, I get this error since launch 1, thus I am not in same case. I may fall in your case when my 1st `pnpm install --frozen-lockfile --loglevel verbose ` works as intended

**Comment by dlarr** [comment] 2024-01-10 08:25
> **EDIT 3:** I got it to work with `pnpm set proxy 'http://MY_PROXY:8080' (remove s from http)
> 
> awsome :) thank yall.

Though it would be nice to be able to host these binaries inside our artifactory, and be able to point to it...

**Comment by alvis** [comment] 2024-01-15 11:39
@zkochan Same issue and a minimal repo can be found in #6268

**Comment by iven** [comment] 2024-02-05 11:15
Seems related #5002

**Comment by ThekhoN** [comment] 2024-03-27 14:57
Was still reproducible on M3.

Manually resolving dependencies for Canvas fixed the issue.

```
// ensure node-gyp is installed else 
npm install -g node-gyp

// find canvas dir
find . -type d | grep canvas

// navigate to canvas dir
cd ./.pnpm/canvas@2.11.2/node_modules/canvas

// manually resolve binaries
node-gyp rebuild 
```

**Comment by jiang-bx** [comment] 2024-04-06 10:19
> Was still reproducible on M3.
> 
> Manually resolving dependencies for Canvas fixed the issue.
> 
> ```
> // ensure node-gyp is installed else 
> npm install -g node-gyp
> 
> // find canvas dir
> find . -type d | grep canvas
> 
> // navigate to canvas dir
> cd ./.pnpm/canvas@2.11.2/node_modules/canvas
> 
> // manually resolve binaries
> node-gyp rebuild 
> ```

thank you, i use volta, pnpm in M3. it's work!

**Comment by alvis** [comment] 2024-04-21 14:19
@zkochan any idea?

**Comment by vtereshyn** [comment] 2024-04-21 14:20
@alvis this has been fixed. Please upgrade your pnpm version to 9+

**Closed** 2024-04-21 14:20 UTC
Labels: type: bug

**Comment by alvis** [comment] 2024-04-21 15:59
@vtereshyn It's sad to report it's not fixed yet. I deleted all node_modules of my monorepo, run `pnpm store prune` and re-install with `pnpm i`, but the build script of node_canvas has not been hit at all, leaving no `build` folder under `node_modules/canvas`. I'm using the latest 9.0.4

**Comment by vtereshyn** [comment] 2024-04-21 16:02
> @vtereshyn It's sad to report it's not fixed yet. I deleted all node_modules of my monorepo, run `pnpm store prune` and re-install with `pnpm i`, but the build script of node_canvas has not been hit at all, leaving no `build` folder under `node_modules/canvas`. I'm using the latest 9.0.4

I had the same issue, but everything was fixed within that update. Double check if your scripts are being running after pnpm install command

**Comment by alvis** [comment] 2024-04-28 19:53
@vtereshyn I wish it's the case too. But with `shared-workspace-lockfile=false` it's not the case. It's still broken.

@zkochan I've prepared a MRE to demonstrate the issue
https://github.com/alvis/mre_pnpm_monorepo_package_dependency_build_skipped

When you install it you should see an error due to the missing `build` folder.
If you comment `shared-workspace-lockfile=false` in `.npmrc` the build script of canvas will be run and hence the issue will be gone.

**Comment by pulkit110** [comment] 2024-07-19 06:56
For me, the solution was to install the [dependencies suggested](https://github.com/Automattic/node-canvas?tab=readme-ov-file#compiling) on `node-canvas` README on the CI runner (no need to run `pnpm rebuild` or `pnpm store prune`). 

```yml 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages required by canvas
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    # ...
```

**Comment by dim882** [comment] 2024-07-30 19:36
Still happening on an M1 Mac with pnpm 9.6 and node 22.4.1. [Manually resolving with node-gyp](https://github.com/pnpm/pnpm/issues/7425#issuecomment-2041040453) didn't work for me. 

Since there are multiple comments saying it's still happening, can this issue be reopened?

**Comment by damain** [comment] 2024-10-29 20:27
I have also experienced it, I tried installing the dependencies in the canvas library and that solved it for a short time however this issue has now reoccured after a mac update to Sonoma 14.7

Now I have tried all the steps her and it is not resolving the issue. This is a blocker for running a testing library as canvas is a dep for jest dom.

**Comment by abencun-symphony** [comment] 2024-12-16 17:17
This is still an issue I've detected when moving from Node 20 to Node 22 with pnpm@9.15.0. The only thing that fixed it was what @alvis suggested: `pnpm rebuild`. Not even nuking the store and reinstalling deps fixed it for some reason. On CI envs our pnpm store is cached so this is going to be a pain to fix now.

**Comment by ki-ri** [comment] 2024-12-17 05:39
This issue still occurs on an M1 Mac(Sonoma 14.7) with pnpm 9.14.4 and Node.js versions v18.20.5, v20.18.0, v20.18.1, and v22.12.0. I have tried numerous methods, including this outlined below, but none have resolved the problem. This is a critical blocker for running tests in my Next.js project.
https://github.com/Automattic/node-canvas?tab=readme-ov-file#compiling

**Comment by abencun-symphony** [comment] 2024-12-17 09:18
@ki-ri install the deps listed there, restart your computer. Then try adding `canvas` as a dev dep with `pnpm i -D canvas`. If it installs properly then run `pnpm rebuild` to force it to rebuild. If it fails again it means you're still missing a system-level dep, unfortunately.

**Comment by ki-ri** [comment] 2024-12-18 07:20
@abencun-symphony Thank you for your comments! However, when I followed the steps you provided, the 'pnpm rebuild' command failed. Here are the error messages:

```
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.2.0
│ gyp info using node@20.18.1 | darwin | arm64
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│   SOLINK_MODULE(target) Release/canvas-postbuild.node
│   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
│ In file included from ../src/backend/Backend.cc:1:
│ ../src/backend/Backend.h:5:10: fatal error: 'exception' file not found
│     5 | #include <exception>
│       |          ^~~~~~~~~~~
│ 1 error generated.
│ make: *** [Release/obj.target/canvas/src/backend/Backend.o] Error 1
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack at ChildProcess.<anonymous> (/Users/ki-ri/.cache/node/corepack/v1/pnpm/9.14.4/dist/node_modules/node-gyp/lib/build.js:216:23)
│ gyp ERR! System Darwin 23.6.0
│ gyp ERR! command "/Users/ki-ri/.nvm/versions/node/v20.18.1/bin/node" "/Users/ki-ri/.cache/node/corepack/v1/pnpm/9.14.4/dist/node_modules/node-gy…
│ gyp ERR! cwd /Users/ki-ri/myProject/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
│ gyp ERR! node -v v20.18.1
│ gyp ERR! node-gyp -v v10.2.0
│ gyp ERR! not ok 
│ node-pre-gyp ERR! build error 
│ node-pre-gyp ERR! stack Error: Failed to execute '/Users/ki-ri/.nvm/versions/node/v20.18.1/bin/node /Users/ki-ri/.cache/node/corepack/v1/pnpm/9.…
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ki-ri/myProject/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_…
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1104:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
│ node-pre-gyp ERR! System Darwin 23.6.0
│ node-pre-gyp ERR! command "/Users/ki-ri/.nvm/versions/node/v20.18.1/bin/node" "/Users/ki-ri/myProject/node_modules/.pnpm/canvas@2.11…
│ node-pre-gyp ERR! cwd /Users/ki-ri/myProject/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
│ node-pre-gyp ERR! node -v v20.18.1
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.11
│ node-pre-gyp ERR! not ok 
│ Failed to execute '/Users/ki-ri/.nvm/versions/node/v20.18.1/bin/node /Users/ki-ri/.cache/node/corepack/v1/pnpm/9.14.4/dist/node_modules/node-gyp…
└─ Failed in 1.7s at /Users/ki-ri/myProject/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ki-ri** [comment] 2025-01-13 02:07
I resolved my issue by reinstalling xcode-select on my M1 Mac (Macos: Sonoma 14.7.2, node version: v20.18.0). Thank you, everyone!
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by gopuvivek** [comment] 2025-02-05 07:34
If using pdfjs-dist versions 4+, this issue is fixed

**Comment by ehrencrona** [comment] 2025-05-14 06:23
My issue was I had to run `pnpm approve-builds` to give permission for the canvas install script to run. There was a warning about it somewhere but I didn't see it among all the other output.

**Comment by Jendorski** [comment] 2025-07-18 21:02
> pnpm approve-builds

Thank you!

**Comment by ErwanRaulo** [comment] 2025-11-19 22:25
it's obvious but setting auto-install-peers=true in .npmrc worked for me
