### ISSUE TITLE
'pnpm install' Too slow

### ISSUE THREAD

**Issue by devenliu** [pnpm/pnpm#7133] opened 2023-09-26 03:26 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, CLI, Lockfile

### Reproduction steps

1. Create a react app using pnpm
2. Run `pnpm install`
3. Delete `node_modules` folder
4. Run `pnpm install` again

### Describe the Bug

After removing the 'node modules' directory, running 'pnpm install' again is very slow

### Expected Behavior

Running 'pnpm install' again should be done very quickly

### Which Node.js version are you using?

v16.20.2

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by tusharvaswanicoder** [comment] 2023-10-07 13:17
It's also slow on linux. I am on debian Debian GNU/Linux 12 (bookworm) and it used to be very fast earlier now its painfully slow.
Takes like 4m 29.1s and it's not even downloading stuff. But even if it was I have a fast consistent network speed of 200mbps so that is definitely not an issue. 
![image](https://github.com/pnpm/pnpm/assets/80880788/0b2695fc-86ec-4a5e-bdf0-f854af63d90a)
Also listing my hardware incase:
Intel® Core™ i5-10400
16.0 GiB

**Comment by KraXen72** [comment] 2023-11-24 06:37
this also happens for me in 8.10.5
```bash
PS D:\coding\svelte\pursiny-sveltekit> npm-check-updates -u -x re*
Using pnpm
Upgrading D:\coding\svelte\pursiny-sveltekit\package.json
[====================] 32/32 100%

 @types/node  ^20.9.4  →  ^20.9.5

Run pnpm install to install new versions.
PS D:\coding\svelte\pursiny-sveltekit> pnpm i
Packages: +2 -2
++--
Progress: resolved 436, reused 381, downloaded 1, added 2, done
    ├── ✕ unmet peer vite@^4.0.0: found 5.0.2
    └─┬ @sveltejs/vite-plugin-svelte-inspector 1.0.4
      └── ✕ unmet peer vite@^4.0.0: found 5.0.2

Done in 6m 51.4s
```
let me know if any more information is needed

**Comment by max-programming** [comment] 2023-11-26 08:40
I am on Windows and on pnpm version `8.6.7` and it is still very slow despite my internet speed being 150 MBps

![image](https://github.com/pnpm/pnpm/assets/51731966/d556029c-5945-4ae2-ab22-4c339a0d3c2a)

**Comment by ikaushiksharma** [comment] 2023-12-23 17:16
maybe its due to your disk read write speeds.. because pnpm copies half of the files/folders from .pnpm-store
So if you're on a HDD it'll be really slow as compared to being on SSDs.

**Comment by KraXen72** [comment] 2023-12-23 17:36
could be a possibility, yeah

**Comment by Hamziss** [comment] 2023-12-23 18:15
> maybe its due to your disk read write speeds.. because pnpm copies half of the files/folders from .pnpm-store So if you're on a HDD it'll be really slow as compared to being on SSDs.

that's what happened to me when i had .pnpm store on the HDD it was so slow i got it fixed by switching the pnpm store back to the ssd drive

**Comment by KraXen72** [comment] 2023-12-23 19:56
but you cannot soft/hard-link files across drives on windows, no?

**Comment by XilinJia** [comment] 2023-12-27 18:06
I just experienced this.  I'm on Manjaro linux.  And my disk is SSD of MacBook Pro.

✗ pnpm --version
8.13.1

✗ pnpm install babel-loader @babel/core @babel/preset-react @babel/preset-env --save-dev 

 WARN  25 deprecated subdependencies found: @babel/plugin-proposal-class-properties@7.18.6, @babel/plugin-proposal-nullish-coalescing-operator@7.18.6, @babel/plugin-proposal-numeric-separator@7.18.6, @babel/plugin-proposal-optional-chaining@7.21.0, @babel/plugin-proposal-private-methods@7.18.6, @babel/plugin-proposal-private-property-in-object@7.21.11, abab@2.0.6, domexception@1.0.1, domexception@2.0.1, fsevents@1.2.13, har-validator@5.1.5, request-promise-native@1.0.9, request@2.88.2, resolve-url@0.2.1, rollup-plugin-terser@7.0.2, sane@4.1.0, source-map-resolve@0.5.3, source-map-url@0.4.1, sourcemap-codec@1.4.8, stable@0.1.8, svgo@1.3.2, urix@0.1.0, uuid@3.4.0, w3c-hr-time@1.0.2, workbox-cacheable-response@6.6.0
Already up to date
Progress: resolved 1689, reused 1687, downloaded 0, added 0, done

dependencies:
- @babel/core 7.23.6
- babel-loader 9.1.3

devDependencies:
+ @babel/core 7.23.6
+ @babel/preset-env 7.23.6
+ @babel/preset-react 7.23.3
+ babel-loader 9.1.3

 WARN  Issues with peer dependencies found
.
├─┬ react-scripts 5.0.1
│ └── ✕ unmet peer typescript@"^3.2.1 || ^4": found 5.3.3
└─┬ optimize-css-assets-webpack-plugin 6.0.1
  └── ✕ unmet peer webpack@^4.0.0: found 5.89.0

Done in 5m 32.1s

**Comment by StarHosea** [comment] 2024-01-22 08:33
same on MacBookPro M2

pnpm version : 8.7.6

**Comment by MisterRichards** [comment] 2024-02-28 20:46
![2024-02-28 14_42_00-PNPM SLOWNESS](https://github.com/pnpm/pnpm/assets/137191972/fea1382e-4cdb-4a5b-b73f-499c4f0b1476)

I believe the assumption being made here is that you WILL be using this tool on an **SSD drive without any antivirus programs** active.  In this screenshot, you see it running on a platter, and has been running pnpm install on the first app (app-01) in the webpack module federation examples, comprehensive react 18 demo... **FOR OVER AN HOUR**... still not finished yet.

**Comment by zch233** [comment] 2024-03-20 08:38
the same as me

**Comment by NailKhalimov** [comment] 2024-04-02 08:14
Same

Any solution for this?

**Comment by YFengFly** [comment] 2024-04-07 01:51
Same. I used disk defragmenter, but it was still unbearably slow.

![20240407094220](https://github.com/pnpm/pnpm/assets/11311708/841d527a-1ec4-4666-875f-ee04447a05e9)

**Comment by YFengFly** [comment] 2024-04-07 06:00
Same. I used disk defragmenter for HDD, but it was still unbearably slow.
In SDD disk,the speed is very fast.
![20240407094220](https://github.com/pnpm/pnpm/assets/11311708/79cb50bd-8ef8-4e9e-8df2-ee360b2e3aff)

**Comment by ipmanlk** [comment] 2024-05-18 11:54
I'm using pnpm 9.1.0 on a NVMe drive and still having the same problem. I'm running Fedora 40.

**Comment by Neo-Ciber94** [comment] 2024-06-12 14:03
Same issue here, if I try to use pnpm in a HDD it takes +30 minutes to install in big projects, yarn takes few minutes.

In my case is unusable because time different are massive when I use it between a SSD and HDD.

**Comment by zkochan** [comment] 2024-06-12 14:34
You can try reducing the number of the [network-concurrency](https://pnpm.io/npmrc#network-concurrency) setting to see if it helps.

I don't think I ever used HDD with pnpm. Antiviruses are known for locking files during installation, which significantly slow pnpm down.

I would still expect pnpm to be faster than Yarn and npm in these cases. Unless you use Yarn with Plug'n'play. Yarn PnP might be faster as it writes the packages into zip files, so there are less file system operations.

Also, this issue doesn't seem useful. pnpm is too slow is too broad... pnpm is not slow as we regularly benchmark it and the competitors do as well. It could be slow in some scenarios or situations. If you have a concrete reproducible scenario, we can look into it. But with this title and description the issue just attracts people with different unrelated issues.

**Closed by zkochan** 2024-06-12 14:34 UTC
Labels: type: bug
