### ISSUE TITLE
Allow injection of NODE_PATH into binstubs

### ISSUE THREAD

**Issue by gsong** [pnpm/pnpm#1768] opened 2019-04-08 12:39 UTC
It would be great to be able to inject runtime `NODE_PATH` into the bin stubs as needed. For example, in create-react-app, we would be able to do `NODE_PATH=src npm t`. This is allowed by CRA using `.env` or injection at runtime.

I think it would be a simple matter of adding `${NODE_PATH}` as the last part of the path in the binstubs.

**Comment by zkochan** [comment] 2019-04-08 13:19
cc @ExE-Boss

**Comment by waynedpj** [comment] 2020-01-25 04:42
i believe that i am running into the same issue: my custom `NODE_PATH` environment variable is not getting passed along to the `node_modules/.bin/` commands.  the binstubs seem to be simply missing the additional `${NODE_PATH}` when redefining that environment variable.

i am very new to pnpm so most likely i am missing something, but it seems like an easy fix i.e. adding `:${NODE_PATH}` to that long new `NODE_PATH` string?

thanks for the space saving alt npm!

**Comment by zkochan** [comment] 2020-01-25 11:08
Indeed, seems like an easy fix that should be done in https://github.com/pnpm/cmd-shim

**Comment by waynedpj** [comment] 2020-04-04 15:51
@zkochan currently having trouble getting pnpm built and tests running, but on a first look perhaps the problem is not in [`cmd-shim`](https://github.com/pnpm/cmd-shim) but in pnpm's `link-bin` since `cmd-shim` [is just given the NODE_PATH](https://github.com/pnpm/pnpm/blob/3130bf712bb082e1c24055ba8f93faf1d2cb5da8/packages/link-bins/src/index.ts#L164)?  instead should `link-bin` be modified to push `"${NODE_PATH}"` into the `nodePath` variable before calling `cmdShim`?

AFAICT it seems like cmdShim is just doing what it is told and is not the one who should be making the decision about whether to include `NODE_PATH`?

either way it looks like a simple `nodePath.push("${NODE_PATH}");` line needs to be added to either `link-bin` or `cmd-shim`.  what do you think?

**Comment by ExE-Boss** [comment] 2020-04-04 16:43
See also <https://github.com/pnpm/cmd-shim/issues/3>

**Comment by waynedpj** [comment] 2020-05-06 18:06
> See also [pnpm/cmd-shim#3](https://github.com/pnpm/cmd-shim/issues/3)

thanks, as i mentioned above i think that the fix (something like `nodePath.push("${NODE_PATH}");`?) should be made in [`link-bin`](https://github.com/pnpm/pnpm/blob/427ae63d74f517fc953db19b98309c01cf7d7890/packages/link-bins/src/index.ts#L162) instead of the `pnpm/cmd-shim` since `cmd-shim` just takes whatever the `NODE_PATH` is as the option `nodePath` .. though i also said that i do not have a good enough handle of how things work to be qualified to guess ;)

**Comment by zkochan** [comment] 2020-05-06 18:49
Actually, it might be possible that we don't even need to override NODE_PATH anymore. We override it to allow some tools to find their plugins (because pnpm creates a non-flat node_modules.

However, since v4, pnpm creates a hoist node_modules by default, so I guess this is not needed

**Comment by waynedpj** [comment] 2020-05-06 18:59
but what about if we do not use hoisting?  i prefer the non-
hoisted/strict node_modules (i.e. hoist = false as default) when
possible and i use NODE_PATH currently with a local patch of pnpm/link-
bins on pnpm 4.14.1.

thanks.

**Comment by anomiex** [comment] 2021-05-19 18:09
https://github.com/pnpm/cmd-shim/pull/36 should fix this, once that is merged, a new version of cmd-shim is released, and then pnpm is updated to use that new version.

**Comment by anomiex** [comment] 2021-05-25 12:26
This seems to be fixed in 6.5.0 with ecd00529a

**Closed** 2021-05-25 12:28 UTC
Labels: good first issue, size: S
