### ISSUE TITLE
ENOENT: no such file or directory, mkdir '/path'

### ISSUE THREAD

**Issue by thanveershah** [pnpm/pnpm#5102] opened 2022-07-26 11:56 UTC
### pnpm version:
`7.6.0`

### Code to reproduce the issue:

> Type pnpm import or pnpm install on a yarm + TurboRepo Project

### behavior:

> j4ccxml4g9:cloud-fe-web user$ pnpm import
>  ENOENT  ENOENT: no such file or directory, mkdir '/path'
> 
> 
> j4ccxml4g9:cloud-fe-web user$ pnpm i
> Scope: all 37 workspace projects
>  ENOENT  ENOENT: no such file or directory, mkdir '/path'

### Additional information:

 - `node -v` prints: 16.6.0
 - Windows, macOS, or Linux?: macOS M1 2021

**Comment by mcmxcdev** [comment] 2022-07-27 15:07
Similar to https://github.com/pnpm/pnpm/issues/4964

**Comment by zkochan** [comment] 2022-07-31 01:16
duplicate of https://github.com/pnpm/pnpm/issues/4964

**Closed by zkochan** 2022-07-31 01:16 UTC
Labels: type: bug
