### ISSUE TITLE
PNPM 7.15+ is no longer defaulting to --strict-peer-dependencies

### ISSUE THREAD

**Issue by elliot-nelson** [pnpm/pnpm#5766] opened 2022-12-07 17:47 UTC
### Code to reproduce the issue:

```console
npm install -g pnpm@7.17.1
mkdir temp && cd temp
npm init -y
npm install @rushstack/heft-jest-plugin
pnpm install
```

### Expected behavior:

```console
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @rushstack/heft-jest-plugin 0.4.0
  └── ✕ missing peer @rushstack/heft@^0.48.8
Peer dependencies that should be installed:
  @rushstack/heft@^0.48.8  
```

(This expected behavior occurs as recently as pnpm 7.13; broken in 7.15)

### Actual behavior:

```console
 WARN  Issues with peer dependencies found
.
└─┬ @rushstack/heft-jest-plugin 0.4.0
  └── ✕ missing peer @rushstack/heft@^0.48.8
Peer dependencies that should be installed:
  @rushstack/heft@^0.48.8  
```

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: macOS

**Comment by octogonz** [comment] 2022-12-07 19:23
@zkochan was this an intentional change?

@elliot-nelson observed that `strict-peer-dependencies` defaults to true from version `7.0.0` through `7.13.x` but seems to have reverted to the old default as of `7.15.x`.  That's a fairly significant change for a SemVer minor release.

**Comment by zkochan** [comment] 2022-12-07 19:24
I don't think it's a breaking change because it remove errors. Vice versa would be a break change.

**Comment by octogonz** [comment] 2022-12-07 19:38
Looks like it was actually introduced in a [patch release](https://github.com/pnpm/pnpm/blob/main/pnpm/CHANGELOG.md):

> ## 7.13.5
> 
> ### Patch Changes
> 
> - Print a warning when cannot read the builtin npm configuration.
> - Also include missing deeply linked workspace packages at headless installation [#5034](https://github.com/pnpm/pnpm/issues/5034).
> - `pnpm outdated` should work when the package tarballs are hosted on a domain that differs from the registry's domain [#5492](https://github.com/pnpm/pnpm/issues/5492).
> - `strict-peer-dependencies` is set to `false` by default.  👈👈👈

```

**Comment by zkochan** [comment] 2022-12-07 19:42
I am sorry that this caused problems on your end and it was confusing but there was no other way. There was a storm of issues about this errors. Also, lots of angry tweets. Lots of messages in the discord chatrooms. And questions on stackoverflow. Turning the setting off was the only way out. And up to this point nobody complained about it.

**Comment by octogonz** [comment] 2022-12-07 19:45
I understand. That makes sense. Perhaps it could have been a larger version bump?

In any case, Rush should probably change its logic to explicitly set all the important options to avoid relying on assumptions about defaults.

**Comment by zkochan** [comment] 2022-12-07 19:46
It could be a larger bump. It just felt like a bug fix because it removes errors.

**Comment by octogonz** [comment] 2022-12-07 20:07
Closing the issue, since this behavior is **"by design"**, and there's nothing else we can do at this point.

We will update Rush's logic instead.

**Closed** 2022-12-07 20:07 UTC
Labels: type: bug

**Comment by octogonz** [comment] 2022-12-08 23:31
Fixed in https://github.com/microsoft/rushstack/pull/3828
