### ISSUE TITLE
Existing packages are automatically updated when adding new ones

### ISSUE THREAD

**Issue by stefano-b** [pnpm/pnpm#2193] opened 2019-11-29 19:28 UTC
### pnpm version: `>4.x` on Linux

When adding a new package to a project, i.e. with `pnpm install --save-dev aos` or `pnpm add -D aos`, existing packages are updated even if not explicitly given the appropriate command.

In this example, installing `aos` also updated `bootstrap` from version `4.3.1` to `4.4.1`, even if I have not explicitly told `pnpm` to update it; this is an unexpected and unwanted behavior.

I've tried this with different versions of `pnpm`, from the latest `4.3.x` to previous `4.x`, and this happens everytime; I had to downgrade `pnpm` to version `3.8.1` to get rid of this issue.

I also noticed that sometimes this issue updates both `package.json` and `pnpm-lock.yaml` with new package versions, some other times only `pnpm-lock.yaml` is updated; this might cause even more problems, since at a first glance the project's packages are listed with the correct version on  `package.json`, but they are actually present in the project with the newer versions as in `pnpm-lock.yaml`.

All of this does not happen with versions prior to `4.x`

I hope to have been clear enough, if more info are needed, please ask and I'll try to do more test and to provide more help.

These issues seem to be related: #2191 and #2188

**Comment by Djaler** [comment] 2019-12-11 12:57
@zkochan can you check this please?

**Comment by ExE-Boss** [comment] 2019-12-15 17:03
Duplicate of #2188

**Closed** 2019-12-15 18:44 UTC
Labels: closed because: duplicate, type: bug

**Comment by zkochan** [comment] 2019-12-16 16:46
:ship: [4.5.0](https://github.com/pnpm/pnpm/releases/tag/v4.5.0)
