### ISSUE TITLE
pnpm fails on empty file in node_modules

### ISSUE THREAD

**Issue by karel-3d** [pnpm/pnpm#2736] opened 2020-07-31 12:48 UTC
### pnpm version:

5.4.8

### Code to reproduce the issue:

`package.json`

```
{
  "name": "foo",
  "version": "1.0.0",
  "dependencies": {
    "is-odd": "^3"
  }
}
```

`node_modules/empty_file`

`(empty file)`

* `pnpm install`

### Expected behavior:

everything works

### Actual behavior:

```

 ERROR  ENOTDIR: not a directory, open '[path here]/node_modules/empty_file/package.json'

```

### Additional information:

 - `node -v` prints: v13.12.0
 - Windows, OS X, or Linux?: OS X

We need to add some empty file for metadata purposes.

Interestingly, if the filename starts with dot, everything works.

**Comment by zkochan** [comment] 2020-08-01 12:40
duplicate of #2730

**Closed by zkochan** 2020-08-01 12:40 UTC

**Comment by karel-3d** [comment] 2020-08-03 04:36
wow so fast fix :D thx
