### ISSUE TITLE
Not exiting with a code of 1 when passed to lint-staged

### ISSUE THREAD

**Issue by kissu** [pnpm/pnpm#3994] opened 2021-11-15 09:27 UTC
### Code to reproduce the issue:

My issue is [explained here](https://github.com/okonet/lint-staged/issues/1049).
There is nothing really fancy, PNPM just doesn't return an exit code different from 0 when there is an error in a `husky` + `pre-commit` git hook + `lint-staged` combo. 

Running it with `pnpm eslint:fix` and then checking with `echo $?` gives the proper (`1`) code meanwhile.

### Expected behavior:

I expect PNPM to crash my whole thing rather than allowing me to reach the next step (commitlint + actual commit).
Here is how yarn behaves, it is working as expected

![image](https://user-images.githubusercontent.com/5133074/141754767-7176d19c-a1a5-4a5f-ab1c-d8c02a6e5c5b.png)

With PNPM, the flow is not broken and we do proceed

![image](https://user-images.githubusercontent.com/5133074/141754874-ad2bcf47-80e9-48bb-8b27-6f769d0aa7f2.png)

### Actual behavior:

Sending an exit code of `0`, like everything worked perfectly.

### Info

 - `node -v` prints: `v14.18.1`
 - Windows, macOS, or Linux?: `Linux`

**Comment by bajtos** [comment] 2021-11-15 15:28
Possibly a duplicate of https://github.com/pnpm/pnpm/issues/3498

**Comment by zkochan** [comment] 2021-11-16 00:22
Maybe this change https://github.com/pnpm/pnpm/pull/3951 somehow caused it?

**Closed** 2021-11-16 01:34 UTC
Labels: type: bug, regression

**Comment by kissu** [comment] 2021-11-16 10:24
Thanks for the quick fix! 🙏🏼 ❤️
