### ISSUE TITLE
peerDependencies of dependency don't get resolved in workspace

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2174] opened 2019-11-20 15:53 UTC
Let's say I have packages `a`, `b` and `c`.
`a` and `b` are in the same workspace.

Both `a` and `c` use `b`. We're now working in `a` and want to use `c` in it, which defined `b` as a `peerDependency`.

`a/package.json`
```json
{
  "name": "a",
  "devDependencies": {
    "b": "workspace:1.2.3",
    "c": "1.2.3",
  }
}
```

`c/package.json`
```json
{
  "name": "a",
  "peerDependencies": {
    "b": "*",
  },
  "devDependencies": {
    "b": "1.2.3",
  }
}
```

In this case, unfortunately, `c` doesn't get access to `b` (which is in the same workspace as `a`).

I didn't have time yet to create a reproduction, but I hope this is already useful.

In my case:
`a` = `prisma2`
`b` = `@prisma/sdk`
`c` = `@prisma/studio-transports`
```
/Users/tim/code/p2/node_modules/.pnpm/registry.npmjs.org/yoga-layout-prebuilt/1.9.3/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module '@prisma/sdk'
Require stack:
- /Users/tim/code/p2/node_modules/.pnpm/registry.npmjs.org/@prisma/studio-transports/0.148.0_typescript@3.7.2/node_modules/@prisma/studio-transports/build/photon.js
- /Users/tim/code/p2/node_modules/.pnpm/registry.npmjs.org/@prisma/studio-transports/0.148.0_typescript@3.7.2/node_modules/@prisma/studio-transports/build/index.js
- /Users/tim/code/p2/prisma2/cli/prisma2/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/tim/code/p2/node_modules/.pnpm/registry.npmjs.org/@prisma/studio-transports/0.148.0_typescript@3.7.2/node_modules/@prisma/studio-transports/build/photon.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tim/code/p2/node_modules/.pnpm/registry.npmjs.org/@prisma/studio-transports/0.148.0_typescript@3.7.2/node_modules/@prisma/studio-transports/build/photon.js',
    '/Users/tim/code/p2/node_modules/.pnpm/registry.npmjs.org/@prisma/studio-transports/0.148.0_typescript@3.7.2/node_modules/@prisma/studio-transports/build/index.js',
    '/Users/tim/code/p2/prisma2/cli/prisma2/dist/bin.js'
  ]
}
```

Thanks!

**Comment by zkochan** [comment] 2019-11-20 17:05
There's a deeper issue. For instance, b is a regular dependency of c. It will be installed from the registry, not linked from the workspace.

To solve this, we need a way to declare this in the lockfile. We specify connections inside a workspace through `link:<relativePath>` (see https://github.com/pnpm/pnpm/blob/1a1b961e83673d674f53c9e495c1da891cd9b1fd/pnpm-lock.yaml#L34-L36). But relative path is not good for dependencies. Maybe something like `link:<lockfileDir><path>` would work.

**Comment by zkochan** [comment] 2019-11-20 18:27
For now, I'd recommend installing the peer dependency as a dependency of the root package.json

**Comment by timsuchanek** [comment] 2019-11-21 10:21
Thanks! Yes, that's what I also did for now, having it as a dependency works for now.

**Comment by P4sca1** [comment] 2020-04-14 21:15
Is the following scenario related to this issue and is there a solution? @zkochan 
I have a package `a` which depends on `b` and `c`.  The package `b` has a peer dependency to `c`.
The problem is that the peer dependency `b` is missing  in `c/node_modules`.

**Comment by Measy** [comment] 2021-06-28 09:28
Hi @zkochan ，any progress on this ? As https://pnpm.io/how-peers-are-resolved mentioned，
```
node_modules
└── .pnpm
    ├── foo@1.0.0_bar@1.0.0+baz@1.0.0
    │   └── node_modules
    │       ├── foo
    │       ├── bar   -> ../../bar@1.0.0/node_modules/bar
    │       ├── baz   -> ../../baz@1.0.0/node_modules/baz
    │       ├── qux   -> ../../qux@1.0.0/node_modules/qux
    │       └── plugh -> ../../plugh@1.0.0/node_modules/plugh
    ├── foo@1.0.0_bar@1.0.0+baz@1.1.0
    │   └── node_modules
    │       ├── foo
    │       ├── bar   -> ../../bar@1.0.0/node_modules/bar
    │       ├── baz   -> ../../baz@1.1.0/node_modules/baz
    │       ├── qux   -> ../../qux@1.0.0/node_modules/qux
    │       └── plugh -> ../../plugh@1.0.0/node_modules/plugh
    ├── bar@1.0.0
    ├── baz@1.0.0
    ├── baz@1.1.0
    ├── qux@1.0.0
    ├── plugh@1.0.0
```
I wonder if it's possible to deal with peer in workspaces's Shared library the same as package which is installed from the registry in node_module file structure; 
`installing the peer dependency as a dependency of the root package.json`  looks strange in a rush monorepo, which may not exists a root package.json;
Related : https://github.com/pnpm/pnpm/issues/2792

 thanks for your work on pnpm!

**Comment by zkochan** [comment] 2021-11-14 01:36
I guess this issue is solved with the new [`dependenciesMeta.injected`](https://pnpm.io/package_json#dependenciesmetainjected) feature of pnpm.

**Comment by Jolg42** [comment] 2022-02-16 15:25
Late to the party 😄 

Indeed that worked!
```
  "dependenciesMeta": {
    "@prisma/sdk": {
      "injected": true
    }
  },
```

**Closed** 2022-02-16 15:27 UTC
Labels: area: lockfile, area: monorepo, area: peers

**Comment by xiaoyu-tamu** [comment] 2022-02-25 03:00
`apps/app1/package.json`
```
{
  "name": "app1",
  "dependencies": {
    "b": "1.0",
    "@namespace/package1": "workspace:*"
  }
}
```
`packages/package1/package.json`
```
{
  "name": "package1",
  "peerDependencies": {
    "b": "1.0",
  },
  "devDependencies": {
    "b": "1.0",
  }
}
```

Hi guys, How to ensure the package "b" is shared between "app1" and "package1"?

The issues i'm facing is nestjs uses class references as providers keys instead of their names, and `"packages1/b" !== "app1/b"` in my case
