### ISSUE TITLE
The inferred type of X cannot be named without a reference to @types/qs

### ISSUE THREAD

**Issue by ALagoni97** [pnpm/pnpm#8291] opened 2024-07-08 12:01 UTC
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

I recently changed my project from yarn to pnpm and using workspaces. It just... Fails... And I am considering switching back as it seems like it's a bug. Or maybe a bug with Typescript?

### Describe the Bug

My code:
```ts
export interface ApiContext {
	database: typeof database
	auth: {
		userId: string
		email: string
	} | null
}

export function simpleWithContext(
	fn: (req: Request, res: Response, context: ApiContext, next: NextFunction) => void
): RequestHandler {
	return async (req, res, next) => {
		try {
			return fn(
				req,
				res,
				{
					auth: null,
					database,
				},
				next
			)
		} catch (error: any) {
			return res.status(500).json({ error: error.message })
		}
	}
}

export const login = simpleWithContext(async (req, res, { database }, next) => {
	if (!req.body.email || !req.body.accessToken) {
		return res.status(400).send()
	}
	return res.status(200).send()
})
```
My root project package.json dependencies:
```json
"devDependencies": {
    "@types/node": "^20.4.8",
    "@typescript-eslint/eslint-plugin": "^7.15.0",
    "@typescript-eslint/parser": "^7.15.0",
    "eslint": "^8.46.0",
    "eslint-config-prettier": "^8.10.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-react": "^7.33.1",
    "prettier": "^3.0.1",
    "prisma": "^5.16.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.5.3"
},
"dependencies": {
    "@prisma/client": "^5.16.1"
}
```
I am getting this error:
`The inferred type of 'login' cannot be named without a reference to '.pnpm/@types+express-serve-static-core@4.19.5/node_modules/@types/express-serve-static-core'. This is likely not portable. A type annotation is necessary.ts(2742)` 

### Expected Behavior

I would expect things to just work out of the gate. I am guessing it has something to do with pnpm way of using symlinks instead of hoisting, but it still seems like issues like this one shouldn't happen. 

I have another project where it is almost identical setup but the error doesn't happen there. Which is extra confusing. 

### Which Node.js version are you using?

20.11.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by zkochan** [comment] 2024-07-09 08:45
Duplicate of https://github.com/pnpm/pnpm/issues/7453

There are a few workarounds in the comments.

**Closed by zkochan** 2024-07-09 08:45 UTC
Labels: type: bug
