### ISSUE TITLE
[Error] - Cannot convert undefined or null to object (`auto-install-peers=true`)

### ISSUE THREAD

**Issue by raulfdm** [pnpm/pnpm#4804] opened 2022-05-26 09:56 UTC
### Code to reproduce the issue:

- `pnpm.debug.log`: https://mega.nz/file/It11VQ6Y#bgxRFLnQqqclN8npto-VUosfrHK3TC6Q-YMvmhcqzAE (couldn't paste here due Github limitation `Comment is too long (maximum is 65536 characters)`)

1. Clone this repo: https://github.com/raulfdm/raulmelo-studio
2. Checkout to the branch `cannot-convert-undefined-or-null-to-object`
3. Run `pnpm i`
4. See the error `Cannot convert undefined or null to object`

You can also try remove `pnpm.lock.yaml` and run `pnpm i` again. The error will still remain.

I think this is, somehow, related to `auto-install-peers=true` present in the `.npmrc` because if I:

1. set `auto-install-peers` to `false`;
1. run `pnpm i` (it'll run successfuly) and throw errors due missing peerDeps;
1. set `auto-install-peers` to `true`;
1. run`pnpm i --force` (no missing peerDeps error)

I won't get `Cannot convert undefined or null to object`.

### Expected behavior:

Either install deps and regen lock file or give me a good error message so I have a clue what's wrong and fix the issue.

### Actual behavior:

Blocks the installation.

### Additional information:

- `node -v` prints: v16.14.2
- Windows, macOS, or Linux?: macOS Monterey 12.4 - Apple M1 PRO

**Comment by raulfdm** [comment] 2022-05-26 10:03
I had done the workaround in my main branch and thought it was about working but I notice the the error come back if I run `pnpm i --lockfile-only`:

```
➜  raulmelo-studio git:(main) ✗ pnpm i
Scope: all 8 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
apps/fitness-buddy postinstall$ pnpm run typegen
│ > fitness-buddy@0.0.1 typegen /Users/raulmelo/development/raulmelo-studio/apps/fitness-buddy
│ > xstate typegen "src/**/*.ts?(x)"
│ src/lib/stores/trainingMachine.ts - success
└─ Done in 713ms
apps/fitness-buddy prepare$ svelte-kit sync
└─ Done in 191ms
```

```
➜  raulmelo-studio git:(main) ✗ pnpm i --lockfile-only
Scope: all 8 workspace projects
 WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 ERROR  Cannot convert undefined or null to object
Progress: resolved 0, reused 1, downloaded 0, added 0
```

**Comment by zkochan** [comment] 2022-05-27 00:24
It is a duplicate of https://github.com/pnpm/pnpm/issues/4796

**Closed by zkochan** 2022-05-27 00:24 UTC
Labels: type: bug

**Comment by tanBeehexa** [comment] 2022-10-12 07:38
I fix it by reinstall lockfile
