### ISSUE TITLE
pnpm incorrectly gets wrong dependency

### ISSUE THREAD

**Issue by vixalien** [pnpm/pnpm#7969] opened 2024-04-19 01:03 UTC
### Last pnpm version that worked

8.15.7

### pnpm version

9.0.3

### Code to reproduce the issue

I created a reproducer at https://github.com/vixalien/pnpm-dedupe-release-tags

But, you can also try this with a new package:

```sh
cd test
pnpm init
pnpm add @payloadcms/richtext-lexical@beta @payloadcms/ui@beta
```

### Expected behavior

I would expect the packages to be normally installed, like in v8

```
Packages: +413
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 429, reused 413, downloaded 0, added 29, done
node_modules/.pnpm/es5-ext@0.10.64/node_modules/es5-ext: Running postinstall script, done in 100ms
node_modules/.pnpm/@swc+core@1.4.16/node_modules/@swc/core: Running postinstall script, done in 45ms

dependencies:
+ @payloadcms/richtext-lexical 3.0.0-beta.11
+ @payloadcms/ui 3.0.0-beta.11

Done in 33.1s
```

### Actual behavior

They don't get installed correctly. `pnpm` incorrectly installs the alpha version of `@payloadcms/translations` for `@payloadcms/richtext-lexical` and even overrides won't tell it to install the correct version (`beta`)

```
Packages: +414
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 430, reused 414, downloaded 0, added 414, done
node_modules/.pnpm/@swc+core@1.4.16_@swc+helpers@0.5.5/node_modules/@swc/core: Running postinstall script, done in 85ms

dependencies:
+ @payloadcms/richtext-lexical 3.0.0-beta.11
+ @payloadcms/ui 3.0.0-beta.11

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @payloadcms/richtext-lexical 3.0.0-beta.11
  └── ✕ unmet peer @payloadcms/translations@3.0.0-beta.11: found 3.0.0-alpha.0

hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.

```

### Node.js version

v21.7.3

### Operating System

Linux

**Comment by vixalien** [comment] 2024-04-19 01:05
Also, I would expect this issue to be tagged with `regression`. Strange...

**Comment by zkochan** [comment] 2024-04-19 09:27
It might be expected. We will check it later.

As a workaround, just install @payloadcms/translations@3.0.0-beta.11 as a direct dependency.

**Comment by yovanoc** [comment] 2024-04-19 13:39
Same issue, even if I put the real good version in the package.json

**Comment by zkochan** [comment] 2024-04-19 13:42
The above example works when I install beta.11 as a direct dependency. So, if it doesn't work in your case, please provide steps to reproduce.

**Comment by yovanoc** [comment] 2024-04-19 14:44
Regression for sure because I only got this problem since 9.X upgrade. And will narrow to a minimal repro soon

**Comment by zkochan** [comment] 2024-04-21 12:43
This one is fixed by https://github.com/pnpm/pnpm/pull/7981 too

**Closed by zkochan** 2024-04-21 12:43 UTC
