### ISSUE TITLE
Fix (or document changes in) "file:" protocol

### ISSUE THREAD

**Issue by artemis-prime** [pnpm/pnpm#8053] opened 2024-05-04 16:12 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

try to use 'file:../../path/to/some/modude' which now fails.

### Describe the Bug

```
// root package.json

"pnpm": {
    "overrides": {
        "@mydomain/moduleName": "file:../../myOtherDomain/otherModuleName"

    }
  }
```

In 8.x, this is the main way that I used to do local dev on local modules (not in the host monorepo)

in 9.x, this produces:

 ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND  Could not install from "/home/<me>/mydoamin/monorepo/otherdomain/othermodulename/" as it does not exist.
 
 (ie, it's not even concatenating the filenames correctly!)
 
 Also, any mention of the "file:" protocol seems to be gone from the docs

### Expected Behavior

Should install and use the module as specified with "file:" above.

### Which Node.js version are you using?

18

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Mint 20

**Comment by zkochan** [comment] 2024-05-05 01:46
@KSXGitHub could this be related to the fix you did?

**Comment by KSXGitHub** [comment] 2024-05-05 06:13
@zkochan It's hard to say. I cannot reproduce it with `pd`.

Here's my `package.json`:

```json
{
  "private": true,
  "dependencies": {
    "@pnpm/tabtab": "*"
  },
  "pnpm": {
    "overrides": {
      "@pnpm/tabtab": "file:../../programming/pnpm-tabtab"
    }
  }
}
```

**Comment by KSXGitHub** [comment] 2024-05-05 06:18
And I cannot reproduce the bug with the latest release of `pnpm` (v9.0.6) either

**Comment by cognvn** [comment] 2024-05-06 03:58
I have same issue with monorepo + `pnpm.overrides`.
Here is the demo repo reproducing the bug: https://github.com/cognvn/demo-pmpm-issue
In this example, I use `@pnpm/types` in workspaces `apps/web` and `packages/ui`, then overrride `"@pnpm/types": "file:./tarball/pnpm-types-10.0.0.tgz"` in root workspace

This commit https://github.com/pnpm/pnpm/commit/04310be5572cc356af733970313b9844060ba9b6 fix absolute path issue but lost relation to root workspace directory.
How about resolving it like `link:` protocol:
https://github.com/pnpm/pnpm/blob/88f53d4a78f56cbdd342b39d2140a6308dc2d84b/hooks/read-package-hook/src/createVersionsOverrider.ts#L100-L111

**Comment by KSXGitHub** [comment] 2024-05-06 11:16
I have created https://github.com/pnpm/pnpm/pull/8055

**Closed** 2024-05-10 21:31 UTC
Labels: type: bug
