### ISSUE TITLE
No jest tests are working @#cra

### ISSUE THREAD

**Issue by fix-me** [pnpm/pnpm#2211] opened 2019-12-13 13:13 UTC
Having the latest versions installed, `npm install` + `npm test` work perfectly on `create-react-app` consuming a `create-react-library` from artifactory,
unfortunately pnpm does not!

Here is what comes using pnpm (no problems with npm here):

```
import { computed, decorate, observable } from "mobx";
           ^

    SyntaxError: Unexpected token {

 [..................]

  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
```

It seems that some babel transformers do not work or behave different than with npm.

<()nmts<

**Comment by jofravelo** [comment] 2020-11-04 13:02
I have the same problem, but in my case it's linked to the paths added in `transformIgnorePatterns`, in `jest.config.js`, that are not rightly resolved. It stopped working after starting to use pnpm with no change on either code or config.

I suspect it's due to the fact that pnpm uses "symbolic links" in `node_modules` and then folders are not "physically" there. Apparently, that's a problem for Jest (or Babel?) when resolving paths.

**Comment by jofravelo** [comment] 2020-11-04 13:22
At the end solved the issue using this solution: [https://github.com/facebook/jest/issues/2081#issuecomment-699558143](url)

It turns out it's rather linked to the folder structure. Even when I used `--shamefully-hoist` when installing dependencies, apparently it's not flat enough for some :)

**Comment by fireairforce** [comment] 2021-07-12 09:41
I meet the same question... but my regex seems not work..

**Comment by juanpicado** [comment] 2021-07-12 09:53
🤔  ... how are you exactly installing CRA with pnpm? I'd like to reproduce it.

**Comment by zkochan** [comment] 2022-05-08 01:27
If it is still an issue, use the [node-linker=hoisted](https://pnpm.io/npmrc#node-linker) setting.

**Closed by zkochan** 2022-05-08 01:27 UTC

**Comment by shawnthye-guru** [comment] 2024-06-28 17:51
> If it is still an issue, use the [node-linker=hoisted](https://pnpm.io/npmrc#node-linker) setting.

have some luck with prefix it with `.pnpm/node_modules`
```
  transformIgnorePatterns: [
    '.pnpm/node_modules/(?!((jest-)?react-native(-.*)?|@react-native(-community)?|victory(-.*)?|uuid)|react-navigation|@shopify/react-native-skia|@react-navigation/.*/)',
  ],
```
