### ISSUE TITLE
PNPM TYPE_ERROR:  Cannot set property name of  which has only a getter.

### ISSUE THREAD

**Issue by divinirakiza** [pnpm/pnpm#4270] opened 2022-01-21 05:23 UTC
### pnpm version:
```pnpm@6.27.1```
### Code to reproduce the issue:
```pnpm i```
```pnpm install```

### Expected behavior:
The command should install all dependencies in the ```package.json``` in the current directory.
### Actual behavior:
A TypeError is thrown
<img width="956" alt="image" src="https://user-images.githubusercontent.com/52403928/150470626-5e81634b-ce76-44c4-8cde-d40d399e48e4.png">

### Additional information:

 - `node -v` prints: `v16.13.2`
 - Windows, macOS, or Linux?: **Linux**

**Comment by andrey-skl** [comment] 2022-02-04 13:48
I can easily reproduce it if type in non-existing registry into .npmrc:
```
registry = https://non-exist.com
```

**Comment by shuiRong** [comment] 2022-02-09 15:23
In my case, I have set a valid npm proxy because I can't access `registry.npmjs.org`.  (ref, [China GreatFirewall](https://en.wikipedia.org/wiki/Great_Firewall))

I thought it was a network problem because I saw a log of network connection errors.

![image](https://user-images.githubusercontent.com/16076993/153231595-ae9b74b3-5caf-469b-aa49-0901cab4b603.png)

so I set:
```
# change the port to yours (vpn's watching).
npm config set proxy http://127.0.0.1:9910 
npm config set https-proxy http://127.0.0.1:9910
```

then solved.

hope that can help you.

**Comment by hotWater-me** [comment] 2022-07-12 03:22
![image](https://user-images.githubusercontent.com/56283392/178401626-2c48c65f-94d7-4bc5-9930-c1b81a706483.png) I have the same problem, how should I solve it?

**Comment by hqzh** [comment] 2022-09-06 01:00
same problem . version 6.34.0  . windows 10

**Comment by zkochan** [comment] 2022-11-02 08:37
Fixed by https://github.com/pnpm/pnpm/pull/5574

**Closed by zkochan** 2022-11-02 08:37 UTC
Labels: type: bug
