### ISSUE TITLE
Shortcut for script prefixed by "test:" and "start:"

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#2323] opened 2020-02-03 11:48 UTC
## Request

Make the following commands possible:

```sh
pnpm test:foo # => pnpm run test:foo
pnpm start:foo # => pnpm run start:foo
```

## Why?

Terminal applications allow user to press <kbd>up</kbd> arrow to previous command and edit it.
It would be convenient to change `test` to `test:foo` without having to add `run`.

**Comment by zkochan** [comment] 2020-02-03 21:09
Duplicate of #2169

**Comment by KSXGitHub** [comment] 2020-02-03 23:47
I don't think this is a duplicate. The issue you linked to would apply to all scripts, which makes adding commands in the future a breaking change. This issue only concern with those that start with `test:` and `start:`, as `test` and `start` shortcuts already exist.

**Comment by zkochan** [comment] 2020-02-03 23:51
That was the solution I suggested https://github.com/pnpm/pnpm/issues/2169#issuecomment-567477036

**Closed** 2020-02-04 02:33 UTC
Labels: closed because: duplicate
