### ISSUE TITLE
PNPM v9.12.3 hanging on `pnpm install`

### ISSUE THREAD

**Issue by lfloyd117** [pnpm/pnpm#8720] opened 2024-10-30 13:25 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.7.1, verified it also occurs on 9.12.3

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

- Changed the versions of `ember-data` packages from `4.6.4` to `4.12.8` repo-wide
- Run `pnpm install`
- Command hangs with most all packages complete: `Progress: resolved 2686, reused 2656, downloaded 0, added 0`

### Describe the Bug

The `pnpm install` command seems to resolve most packages then hangs and never completes. 
I have also tried deleting the lockfile to see if that was messing it up and the hanging continues. 
I have also watched `htop` and it does not appear to run out of memory.

Let me know if there are any logging commands/flags I can use to provide more helpful information.

### Expected Behavior

The `pnpm install` command does not hang

### Which Node.js version are you using?

18.19.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu (via WSL)

**Comment by lfloyd117** [comment] 2024-10-30 13:27
Let me know if there are any logging commands/flags I can use to provide more helpful information

**Comment by lfloyd117** [comment] 2024-10-30 20:42
For the record, it seems to not hang if I downgrade to pnpm@9.1.0 @zkochan

**Comment by xinyifly** [comment] 2024-11-01 15:51
Even after a kill -9 , it goes into a D state. I have to reboot my computer, and it blocks my computer from reboot :(

```
$ ps -l 3318
F S   UID     PID    PPID  C PRI  NI ADDR SZ WCHAN  TTY        TIME CMD
0 D  1000    3318    3194  4  80   0 - 2029110 io_uri pts/0    0:22 node /home/xinyifly/bin/../.local/share/pnpm/global/5/node_modules/pnpm/bin/pnpm.cjs i
```

```
$ pnpm --version
9.12.3
```

**Comment by cprussin** [comment] 2024-11-05 01:05
Same issue but in my case the install fails very intermittently, probably about a third of the time.  Every time, when it fails, it goes into a zombie state and as @xinyifly says it blocks reboot.  It also blocks the laptop from suspending, and the process seems to not respond to signals and can't be killed, so it's a highly obtrusive issue.

Anything I can do to help debug @zkochan ?

I've tried running with `--reporter ndjson` and the logs don't seem interesting; sometimes the last few messages have the name `pnpm:progress` and just tell me that some package was found in the store; other times it's `pnpm:link`.  One time I saw it hang after a message `pnpm:bins-conflict`.  When pnpm starts hanging appears totally inconsistent, at least judging from the ndjson logs.

Anecdotally, it seems to fail very often (most of the time) when running a fresh install on a clean repo.  It fails much less often (maybe a quarter of the time or less) when running a `pnpm install` when packages are already installed.

**Comment by cprussin** [comment] 2024-11-05 01:38
For what it's worth, here's the output of looking at `/proc/<pid>/syscall` for some of the stuck pnpm processes:

```
~ 
❯ : sudo cat /proc/111706/syscall
281 0x11 0x7ffe52d792c0 0x400 0xffffffff 0x0 0x8 0x7ffe52d78550 0x7f0047a25666
```

Looks like 281 is `sys_epoll_pwait`.  This is outside my expertise but as far as I can tell this seems to indicate that pnpm is awaiting some file descriptors to be available and they are never provided by the kernel?

I'll continue debugging and will post anything interesting that I learn.

**Comment by yuri-scarbaci-lenio** [comment] 2024-11-06 17:08
Facing the same issue here (with latest version and `node 22.1.0` )

moving to `9.1.2` improved stability but didn't completely solve the issue

trying to run `pnpm i` on a **_lock-file less_** monorepo (with namely 590 workspace projects as per reported by pnpm, but we do not have 590 packages, I think pnpm is counting them thrice?) completely hangs pretty much early 

running `pnpm i` when a pre-existing lock exist doesn't hand BUT `top` shows `node %cpu usage` up to `315` with an avarage of `105`

running `pnpm i --lockfile-only` does hangs indefinitively when the lock files doesn't exist.

**Comment by zkochan** [comment] 2024-11-06 20:38
Try to create a public repo that reproduces the issue. Just with ember-data I couldn't reproduce.

**Comment by xinyifly** [comment] 2024-11-07 02:58
Some notes in my situation:

1. I can successfully use latest pnpm even without notified any issue in my Laptop with `AMD Ryzen 7 8840HS` and `Linux 6.11.5` , `node v20.15.1`
2. pnpm install keep freezing whether or not I clean up all caches and fresh install in my PC with `Intel(R) Core(TM) i5-10400` and `Linux 6.6.58` , `node v20.15.1`

**Comment by lfloyd117** [comment] 2024-11-07 16:58
@zkochan  Made one right here: https://github.com/lfloyd117/pnpm-9-hanging/tree/main
I have the main branch mimicking our current, working state. But I have the [test-hang](https://github.com/lfloyd117/pnpm-9-hanging/tree/test-hang) branch with package changes to ember-data that cause `pnpm install` to hang.

To reproduce, just clone the repo, checkout `test-hang` and run `pnpm install`

**Comment by zkochan** [comment] 2024-11-07 22:42
@lfloyd117 thanks. I am able to reproduce the issue with your sample.

**Closed** 2024-11-14 16:15 UTC
Labels: type: bug

**Comment by lfloyd117** [comment] 2024-11-14 18:04
Thank you, @zkochan ! Just tested and v9.13.1 works!

**Comment by zkochan** [comment] 2024-11-14 20:38
I am locking this thread as people tend to comment on such issues with unrelated new issues. This specific issue is solved and a test covers it.
