### ISSUE TITLE
pnpm publish always publishes the created tarball

### ISSUE THREAD

**Issue by RafidMuhymin** [pnpm/pnpm#4593] opened 2022-04-20 09:41 UTC
### Additional information:

 - `node -v` prints: `17.6.0`
 - Windows, macOS, or Linux?: `Linux`

**Comment by fireairforce** [comment] 2022-04-20 17:18
can u please provide a more detailed demo ?

**Comment by RafidMuhymin** [comment] 2022-04-21 18:26
Thanks for your response @fireairforce ! The package I'm trying to publish is `astro-imagetools` and its code is at https://github.com/RafidMuhymin/astro-imagetools/tree/main/packages/astro-imagetools/. Whenever I'm publishing a new version using `pnpm publish`, the created tarball is also getting published.

For example, check this links https://unpkg.com/astro-imagetools@0.5.3/astro-imagetools-0.5.3.tgz https://unpkg.com/astro-imagetools@0.5.4/astro-imagetools-0.5.4.tgz and https://unpkg.com/astro-imagetools@0.5.5/astro-imagetools-0.5.5.tgz.

The command is acting like it's equivalent to `pnpm pack && npm publish`

**Comment by zkochan** [comment] 2022-04-21 23:42
The root cause of this issue might be the same as the cause of this one: https://github.com/pnpm/pnpm/issues/4348

**Comment by zkochan** [comment] 2022-04-21 23:57
pnpm packs the tarball and then it runs npm CLI to publish the tarball:

https://github.com/pnpm/pnpm/blob/9f06162824de4c263500eb1c4c7ba84cd2a8fa87/packages/plugin-commands-publishing/src/publish.ts#L199-L201

Maybe this doesn't work in the latest npm? Although I could not reproduce the issue while looking into #4348

**Comment by zkochan** [comment] 2022-05-07 01:12
I believe this is fixed by https://github.com/pnpm/pnpm/issues/4348

**Closed by zkochan** 2022-05-07 01:12 UTC
Labels: type: bug, area: publishing
