### ISSUE TITLE
pnpm version --recursive support

### ISSUE THREAD

**Issue by codejamninja** [pnpm/pnpm#2438] opened 2020-03-22 13:37 UTC
npm lets you increment your packages semantic version using the `version` command. For example . . .

```
npm version patch
```

It would be nice if I could recursively update all the versions in all my pnpm workspaces. For example . . .

```
pnpm -r version patch
```

**Comment by zkochan** [comment] 2020-03-22 14:27
Duplicate of #2225

**Closed by zkochan** 2020-03-22 14:27 UTC
