### ISSUE TITLE
Failed to find <pkg> in lockfile during hoisting. Next aliases will not be hoisted.

### ISSUE THREAD

**Issue by anantoghosh** [pnpm/pnpm#2798] opened 2020-08-24 19:18 UTC
### pnpm version: 5.5.3

I had started getting this warning when working on a project, whenever a new dependency is added in a workspace package 
```
Failed to find "/react/16.13.1" in lockfile during hoisting. Next aliases will not be hoisted: react
```
Such a message for each of the dependencies in the workspace package.
This caused issues when building the project.

Minimal Repo: https://github.com/anantoghosh/pnpm-report

Here `main-package` has `workspace-dep` as a dependency.
Adding any package to `main-package` shows the warning.

As a work around I was using `pnpm add <pkg> -r --filter main-package` from the root.

### Additional information:
 - `node -v` v12.18.3
 - Windows

**Comment by anantoghosh** [comment] 2020-08-28 14:24
Thank you very much!

**Comment by ChristianUlbrich** [comment] 2020-10-26 22:04
@zkochan 
This errors can still be reproduced with _current_ **5.10.2** and node **14.14.0**:
1. `git clone git@github.com:anantoghosh/pnpm-report.git`
1. `cd pnpm-report`
1. `pnpm i -r`
1. `pnpm i --filter workspace-dep`
1. -> `Failed to find "/react/16.13.1" in lockfile during hoisting. Next aliases will not be hoisted: react` :(

Problem also happens with pnpm **5.6.1**, so in lack of a release / changelog it is hard for me to pinpoint the version, that the above merge actually has been merged in...

**Comment by adamhonen** [comment] 2021-02-15 13:50
I'm not sure if the root cause of this issue has been analyzed, but in case it was, is there a known work around, by any chance?

I'm encountering this and it seems that subsequently the installation of some packages is skipped (using the `--filter <package name>...` syntax).

**Comment by dmichon-msft** [comment] 2021-02-24 00:43
I still repro this in 5.17.2, using a normal filtered install. I don't think this is actually related to add.

**Comment by dmichon-msft** [comment] 2021-02-24 00:53
On further inspection, I'm seeing that error message referencing package versions that aren't in the lockfile at all, so I'm wondering why pnpm is looking for that version at all.

For example, I have a monorepo with projects that are configured to use `@rushstack/heft@0.23.1`, but the filtered install is mentioning not finding `/@rushstack/heft/0.24.1` in the lockfile during hoisting, which is bizarre, because said package shouldn't be considered in the first place.

**Comment by develar** [comment] 2021-03-13 13:53
In my case I get this warning for package that specified in `optionalDependencies`. As result, compilation failed (no types). Works correctly for yarn 1/2. I thought that migration to PNPM will be more easier but it is second blocking bug :(

**Comment by zkochan** [comment] 2021-03-13 14:00
@develar do you install with the `--filter` option as well? I don't recommend using filtering with the installation command. It is extremely hard to make a partial installation in a workspace, maybe we should disable it in pnpm v6.

**Comment by develar** [comment] 2021-03-13 14:13
@zkochan No. `pnpm install --frozen-lockfile` or `pnpm install`. Works correctly on my macOS machine, but failed on CI machines (GitHub, CircleCi). I tried to explicitly added dependency also to `devDependencies`, but no luck.

**Comment by zkochan** [comment] 2021-03-13 14:17
I will look into your repo
if you're facing many small issues, might be faster to post in our chat https://pnpm.js.org/r/chat/

**Comment by develar** [comment] 2021-03-13 14:26
@zkochan I found the reason. And the reason is exactly why I decided to migrate to PNPM :) PNPM doesn't install `dmg-license` because this package requires `macOS` (https://github.com/argv-minus-one/dmg-license/blob/master/package.json#L76). Not clear why it was an issue for Yarn.

**Comment by zkochan** [comment] 2021-03-13 14:27
ok, tag me in the PR thread if you'll have other issues. or in the chat

**Closed** 2021-05-15 18:27 UTC
Labels: state: in progress
