### ISSUE TITLE
Patching packages during installation

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#3077] opened 2021-01-17 14:32 UTC
It is supported by Yarn. Related pages:

* [Patch protocol](https://yarnpkg.com/features/protocols#patch)
* [yarn patch](https://yarnpkg.com/cli/patch)
* [yarn patch-commit](https://yarnpkg.com/cli/patch-commit)

And there's this tool also, which does not support pnpm: https://www.npmjs.com/package/patch-package

**Comment by schmod** [comment] 2021-04-14 15:55
Yarn 2's implementation of this is actually pretty slick.  Implementing such a feature in pnpm seems like it could be tedious, but would be extremely desirable to have.  

It's currently the one thing preventing us from using pnpm.

**Comment by schmod** [comment] 2021-04-14 17:18
This appears to be a duplicate of #2675

**Comment by zkochan** [comment] 2021-04-28 22:45
How is Yarn's implementation better than patch-package?

I see there is a PR to patch-package to add pnpm support: https://github.com/ds300/patch-package/pull/302

**Comment by m1heng** [comment] 2021-09-06 03:05
Seems patch-package's PR is about to be merged.

**Comment by bhvngt** [comment] 2021-09-11 05:39
Seems like patch-package is not actively maintained. To handle this kind of scenario, `patch` functionality in `pnpm` core would be fantastic.

**Comment by MarcCelani-at** [comment] 2021-09-26 02:39
@m1heng do you have an insider scoop as to what's going on over at patch-package? I don't see any activity on that PR.

+1 for patch support in pnpm core. I've run into enough issues in patch-package that the lack of maintenance scares me off. This issue is blocking us from being able to evaluate pnpm as an alternative to yarn classic.

**Comment by rizkyramadhan** [comment] 2022-02-06 23:20
Is this issue still progressing ?

**Comment by JanJakes** [comment] 2022-04-08 07:07
I hope it's not off-topic but I'd also like to ask whether this is planned or researched or if there are no particular plans yet.

I've noticed this makes the two most upvoted issues:

![Screen Shot 2022-04-08 at 9 02 28](https://user-images.githubusercontent.com/141436/162382474-3c485713-d3be-4f0f-89a4-e185275b43d1.png)

Thanks!

**Comment by zkochan** [comment] 2022-04-09 22:05
I have no objections against this feature but it is not easy to implement. Currently, I don't see enough value in it to spend a lot of my time on it.

To patch a package, it is easy to fork it, publish it with a new name an use an [override](https://pnpm.io/package_json#pnpmoverrides) to replace the package with the fork in all places.

**Comment by rizkyramadhan** [comment] 2022-04-13 17:42
or easier, just use workspace:^ to modify the package

**Comment by schmod** [comment] 2022-04-13 18:41
Personally, I don't think either of those are particularly "easy" workflow, especially compared to the ergonomics that `patch-package` provides (edit the files in-place in `node_modules`, run `patch-package`, and check in the files that it produces).

In particular, users in corporate settings typically do not have the ability to easily clone/re-publish temporary forks of packages.

**Comment by leebeydoun** [comment] 2022-04-22 04:31
Agree with @schmod on this one. Forking a package is not really an option. Currently the lack of being able to patch packages with `pnpm` is the only thing stopping my team at at work from adopting `pnpm`. 

I've also never worked at a company that didn't have to patch a package at some point - its just a sad reality of packages on npm. Getting this ability in `pnpm` would be amazing, and I think we definitely drive the adoption of `pnpm` higher, especially in corporate settings.

**Comment by zkochan** [comment] 2022-04-22 15:01
@milahu has forked patch-package https://github.com/milahu/patch-package-with-pnpm-support

Does it work? Could we just move it to the pnpm org and make it an "official" solution?

**Comment by deini** [comment] 2022-04-22 15:18
> Does it work?

Last time I checked it didn't support workspaces.

**Comment by milahu** [comment] 2022-04-22 15:23
the benefit of patch-package is that it works with all package managers (npm, pnpm, yarn, rush, ...)
simply by adding `.scripts.postinstall = "patch-package"` to package.json

> Last time I checked it didn't support workspaces.

should work with npm/yarn/pnpm workspaces
see https://github.com/milahu/patch-package-with-pnpm-support/issues/4#issuecomment-1098590539

**Comment by donferi** [comment] 2022-06-01 22:29
Have any plans changed around this? Still looking for an official solution, the proposed solutions so far feel a bit "risky". I'm still willing to sponsor some $ for this feature.

**Comment by zkochan** [comment] 2022-06-17 01:15
I am working on a patch solution: https://github.com/pnpm/pnpm/pull/4885

**Closed** 2022-06-20 13:00 UTC
Labels: type: feature

**Comment by zkochan** [comment] 2022-06-22 22:35
:ship: 7.4.0-0

**Comment by hrasoa** [comment] 2022-06-29 21:31
```
$ pnpm -v
7.4.0
```

```patch``` is working great, thanks! But everytime I add new dependencies with ```pnpm add <pkg>``` I have this message: 

<img width="794" alt="Screenshot 2022-06-29 at 23 28 35" src="https://user-images.githubusercontent.com/796524/176548161-33865337-48c5-4ed8-98dc-e4cee44e2907.png">

My ```package.json```:

```
"pnpm": {
  "patchedDependencies": {
    "@babel/plugin-transform-typescript@7.18.6": "patches/@babel__plugin-transform-typescript@7.18.6.patch"
   }
}
```

I have to manually remove the ```patchedDependencies``` and put it back when I'm done. Am I doing right ?

**Comment by zkochan** [comment] 2022-06-29 21:36
@hrasoa I cannot reproduce your issue. If this happens, it needs to be fixed. Make an issue with more details. Is it in a workspace?

**Comment by hrasoa** [comment] 2022-06-29 21:38
@zkochan yes it's in a workspace

**Comment by zkochan** [comment] 2022-06-29 21:42
ok, yes
I could repro it in a workspace.
