### ISSUE TITLE
`pnpm pack` doesn't respect `files:` field with pnpm@6.32.0

### ISSUE THREAD

**Issue by Mehdi-Hp** [pnpm/pnpm#4376] opened 2022-02-22 12:16 UTC
### pnpm version:
6.32.0

### Code to reproduce the issue:
`pnpm pack` or `pnpm publish`

### Expected behavior:
pnpm should includes files from `files` field in `package.json`

### Actual behavior:
It ignores `files` and only packs `package.json`

**Comment by BlackHole1** [comment] 2022-02-25 08:25
<img width="720" alt="images" src="https://user-images.githubusercontent.com/8198408/155680954-dfd04df6-aae5-4efd-95e4-f43562f892a9.png">

I did not reproduce the problem.

**Comment by Mehdi-Hp** [comment] 2022-03-01 18:51
Maybe there's some new bugs with `**` in `files`? 6.31.x was alright.  

![CleanShot 2022-03-01 at 22 19 19](https://user-images.githubusercontent.com/8641684/156230538-8cae82a7-c628-4c59-ad6c-65de80c377eb.png)

**Comment by BlackHole1** [comment] 2022-03-02 06:51
Hey @Mehdi-Hp 👋. I just did some research on this issue and npm has the same behavior.
In your question, just delete the `. /` prefix to fix it.

---

### Reason:

pnpm/npm use [npm-packlist](https://github.com/npm/npm-packlist) library.

[npm-packlist](https://github.com/npm/npm-packlist) use [node-glob](https://github.com/isaacs/node-glob) library.

`node-glob` not support `./` prefix. see: https://github.com/isaacs/node-glob/issues/309

Since this issue is caused by an upstream dependency and we need to be consistent with the behavior of npm, I will close this issue. if you have any other ideas, I will reopen this issue. 🙇‍♂️

**Closed by BlackHole1** 2022-03-02 06:51 UTC
Labels: type: bug
