### ISSUE TITLE
pnpm install with `--package-import-method=clone`  fails but 'copy' and 'hardlink' works fine

### ISSUE THREAD

**Issue by hardfist** [pnpm/pnpm#2879] opened 2020-09-19 15:54 UTC
### pnpm version:
5.5.13

### Code to reproduce the issue:

https://gist.github.com/hardfist/47678583c20cee545b573ea60742393b

### Additional information:

 - `node -v` prints: v12.18.2
 - Windows, OS X, or Linux?: OSX 10.15.6

**Comment by zkochan** [comment] 2020-09-19 20:25
This is probably a duplicate of #2761

**Closed** 2021-03-14 02:15 UTC
Labels: closed because: duplicate
