### ISSUE TITLE
`pnpm publish` does not replace `workspace:` versions when publishing

### ISSUE THREAD

**Issue by BerkeKaragoz** [pnpm/pnpm#4624] opened 2022-04-26 18:01 UTC
### Expected behavior:
`pnpm publish` replaces `workspace:*` with corresponding versions as explained here: 
https://pnpm.io/workspaces#publishing-workspace-packages

`pnpm view eslint-config-berkekaragoz@0.1.8`:

![image](https://user-images.githubusercontent.com/34271483/165362253-0ad9df10-2bc2-422f-bede-7b4bf45e2ab7.png)

### Actual behavior:
`pnpm publish` leaves `workspace:*` as it is.

`pnpm view eslint-config-berkekaragoz@0.1.7`:

![image](https://user-images.githubusercontent.com/34271483/165362361-f803bbcc-f497-49dd-81dc-896a40dc99c5.png)

### Additional information:
`pnpm pack` packs as I wanted. But when I ran `pnpm publish *tarball*`, it set the versions to `workplace:*`. So I packed and published with `npm publish`.

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Windows 10

**Comment by zkochan** [comment] 2022-04-26 23:19
This is a duplicate of https://github.com/pnpm/pnpm/issues/4348

**Closed by zkochan** 2022-04-26 23:19 UTC
Labels: type: bug
