### ISSUE TITLE
[Feat/Bug] `pnpm init` does not respect `init.*` options as flags like `npm init --init-*`

### ISSUE THREAD

**Issue by josh-hemphill** [pnpm/pnpm#8090] opened 2024-05-16 00:56 UTC
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

I often have multiple folders to init, and when the defaults are specific there's no way to set them all other than manually, but I'd like to be able to set defaults on the cli so I can easily create a bunch of package.json files by just modifying a cli one-liner, or write some automation to iterate with the option flags.

In fact, `npm` has actually [deprecated using the config options instead of the cli flags](https://docs.npmjs.com/cli/v10/using-npm/config#initauthoremail ) as introduced in pnpm with #4422 

### Describe the solution you'd like

I'd actually like it if pnpm allowed more of the default values to be set with flags, since that would add even more convenience.

### Describe the drawbacks of your solution

Nothing I can think of.

### Describe alternatives you've considered

Using npm

**Comment by btea** [comment] 2024-05-16 02:18
It seems to be a duplicate of #7711.

**Comment by josh-hemphill** [comment] 2024-05-16 02:23
Ah, didn't manage to find that one (not much searchable text/keywords on it 😅). Should I close this or link them?

**Comment by btea** [comment] 2024-05-16 02:27
My comment above has been linked there, maybe you can close this issue directly. You can keep it active by adding your comments there. 😀

**Closed** 2024-05-16 03:01 UTC
Labels: type: feature
