### ISSUE TITLE
deploy command with node-linker=hoisted produces empty node_modules folder

### ISSUE THREAD

**Issue by bm77525-kr** [pnpm/pnpm#6682] opened 2023-06-15 17:35 UTC
We're attempting to migrate our monorepo containing several Azure Function apps to pnpm. The main issue we're facing is the packaging/deployment of individual functions apps since Azure Functions don't support symlinks when deployed.

We've attempted to use the `node-linker=hoisted` option since it shouldn't create symlinks along with the `deploy` command, but the output of the `node_modules` folder ends up with just `node_modules/.pnpm/lock.yaml` and nothing else.

### pnpm version: 

8.6.2

#### .npmrc file
```
node-linker=hoisted
```

#### Command:
`pnpm --filter={workspace name} --prod deploy pruned`

### Expected behavior:

A package is deployed from the specified workspace which contains a flat `node_modules` without symlinks.

### Actual behavior:

The package is deployed from the specified workspace that contains a near-empty `node_modules` folder, containing only a single file: `node_modules/.pnpm/lock.yaml`

### Additional information:

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by wmartins** [comment] 2023-06-21 21:55
I'm facing a similar issue, I thought it'd be good to comment in case they're related.

I'm also working on packaging a package to be deployed on Lambda. To do that, I wanted to install all dependencies on the root of a folder called `dist` and I'd simply zip it all up and that's the content of my Lambda.

My idea was to use `--modules-dir` to specify where `node_modules` should live, however, when I run it like this:

```bash
pnpm install --ignore-workspace --modules-dir modules --node-linker hoisted
```

The result is somewhat like this:

```
.
├── modules
│   └── .modules.yaml
├── node_modules
│   ├── .bin
│   │   └── some-binary -> ../path-to-some-binary
│   ├── .pnpm
│   │   └── lock.yaml
│   ├── @some-package
│   │       └── package.json
```

The `modules` folder has only this `.modules.yaml` file and we have a `node_modules` folder with all the packages.

If I don't use `node-linker hoisted`, I can see packages in the `modules` folder correctly.

**Comment by ennioVisco** [comment] 2023-07-09 07:58
> We're attempting to migrate our monorepo containing several Azure Function apps to pnpm. The main issue we're facing is the packaging/deployment of individual functions apps since Azure Functions don't support symlinks when deployed.
> 
> We've attempted to use the `node-linker=hoisted` option since it shouldn't create symlinks along with the `deploy` command, but the output of the `node_modules` folder ends up with just `node_modules/.pnpm/lock.yaml` and nothing else.
> 
> ### pnpm version:
> 8.6.2
> 
> ### Code to reproduce the issue:
> #### .npmrc file
> ```
> node-linker=hoisted
> ```
> 
> #### Command:
> `pnpm --filter={workspace name} --prod deploy pruned`
> 
> ### Expected behavior:
> A package is deployed from the specified workspace which contains a flat `node_modules` without symlinks.
> 
> ### Actual behavior:
> The package is deployed from the specified workspace that contains a near-empty `node_modules` folder, containing only a single file: `node_modules/.pnpm/lock.yaml`
> 
> ### Additional information:
> * `node -v` prints: v16.16.0
> * Windows, macOS, or Linux?: macOS

Same issue here!

**Comment by realduolaf** [comment] 2023-09-01 03:07
Is there any progress? Or deploy should not be used when using `node-linker=hoisted` 🤔?

**Comment by bm77525-kr** [comment] 2023-11-14 20:01
Wondering the same. The `deploy` command (or `hoisted` node-linker setting?) has been broken for a long time. There are several open issues regarding the same problem including this one and these:

* https://github.com/pnpm/pnpm/issues/6259#issuecomment-1644693101
* https://github.com/pnpm/pnpm/issues/6166#issuecomment-1455562090

@zkochan continues to recommend using `hoisted` node-linker setting and continues to be told it doesn't work with no reply or acknowledgement that it's broken and, as far as I've seen, has never worked. This is really the only thing preventing us from switching to pnpm as it makes packaging Azure Functions untenable due to having to use a bunch of workarounds that make our build/deploy process brittle.

**Comment by men232** [comment] 2023-11-21 15:06
I made a script for my needs to deploy a package from workspace to google cloud functions, maybe someone will find it useful.
https://github.com/men232/pnpm-better-pack

**Comment by chrisjarman** [comment] 2024-02-27 14:24
Might be pointless but I'd like to bump this all the same. `pnpm deploy` is a fantastic tool, and exactly what we need for our deployment pipelines. But if it doesn't work with `node-linker=hoisted` it's as good as useless for our purposes, as our monorepo includes a React Native app.

**Comment by mark-omarov** [comment] 2024-04-30 06:00
In a monorepo I need to pack one of the applications with `bundleDependencies` which requires the `node-linker=hoisted`.
The option doesn't work with `pnpm deploy` which is required to make an isolated `node_modules` in the target directory.
This issue is a huge blocker.

pnpm: `v9.0.6`
node: `v20.11.1`

**Comment by lukebelbina** [comment] 2024-05-02 20:12
I am running into this exact issue still

**Comment by michaelwarren1106** [comment] 2024-05-03 16:32
Im running into this exact same thing also. Trying to package up a nextjs app for deployment to an Azure Web App Service and cant because of the symlinks to the `.pnpm` directory that is created by `pnpm deploy`. Would definitely love a way to generate a flat `node_modules` that wouldnt require pnpm to be installed on the Azure infra.

**Comment by GlCap** [comment] 2024-05-24 14:01
having the same problem on the latest version of pnpm, is there some news or workaround for this?

**Comment by clayrisser** [comment] 2024-06-21 22:09
It's not possible to use pnpm with expo in a monorepo without `node-linker=hoisted`. When deploying, it's critial that node modules from other packages are pruned out. This is very easy to do in yarn with `yarn workspaces focus`.

https://yarnpkg.com/cli/workspaces/focus

Either pnpm needs to support `pnpm install --filter` or `pnpm deploy --filter`  when `node-linker=hoisted` in order to really be viable for expo/react-native monorepo project (and probably many other projects)

**Comment by bwlt** [comment] 2024-06-22 09:25
I had a similar problem with AWS CodeDeploy (not Azure Function).
The AWS CodeDeploy agent is not able to copy the symlinks properly.
As a workaround in the `AfterInstall` hook what I do is:
- rm the node_modules directory
- cp -r /opt/codedeploy-agent/deployment-root/.. (nested path using environment variables DEPLOYMENT_GROUP_ID and DEPLOYMENT_ID - see [documentation](https://arc.net/l/quote/mfvkiszv))

In this way I am able to run my nodejs application

**Comment by nickfujita** [comment] 2024-08-09 02:59
Also confirmed when trying to deploy via AWS Amplify from a monorepo with multiple applications. We need to only install a subset of the dependencies, not all for the entire repo. This worked well using `pnpm --filter "apps/myApp..." install` alone. But unfortunately further down the deployment pipeline, there is a failure due to `node-linker=hoisted` not being set. This appears to be [required](https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#support-for-monorepo-framework).

When `node-linker=hoisted` is set, the `--filter` argument appears to be ignored.

**Comment by clayrisser** [comment] 2024-08-12 09:51
This is a major breaking issue for me that prevents me from migrating from yarn to pnpm.

**Comment by iffa** [comment] 2024-08-27 13:39
Ran into this very same issue which prevents us from using pnpm completely for our monorepo setup.

**Comment by clayrisser** [comment] 2024-09-14 16:42
@iffa did you ever figure out a solution to this?

**Comment by iffa** [comment] 2024-09-15 10:59
> @iffa did you ever figure out a solution to this?

Yes, we moved to yarn 4 instead. Doesnt have a deploy command but together with turborepo's "prune" we got a solid working setup, and a few bugs in yarns side that i found were fixed within 24hrs.

**Closed** 2024-09-20 01:27 UTC
Labels: type: bug

**Comment by zkochan** [comment] 2024-09-20 10:40
:ship: 9.11

**Comment by clayrisser** [comment] 2024-09-25 19:25
@zkochan is this fixed?
