### ISSUE TITLE
pnpm install --frozen-lockfile fails with pnpm 7 after upgrading lockfile to 6.1 from 6.0

### ISSUE THREAD

**Issue by ludofischer** [pnpm/pnpm#6609] opened 2023-05-29 21:30 UTC
### Code to reproduce the issue:
https://github.com/cssnano/cssnano/pull/1504
### Expected behavior:
pnpm 7.x.x manages to install the dependencies when the lockfile version is 6.1,
since the major lockfile version did not change

### Actual behavior:
pnpm fails and prints this error:
```
 WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/@changesets/cli/2.26.1' in pnpm-lock.yaml

This issue is probably caused by a badly resolved merge conflict.
To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
```
It is not even possible to downgrade the lockfile, because running `pnpm --no-frozen-lockfile` gives a different error:
```
 ERROR  /@babel/code-frame@7.18.6 is an invalid relative dependency path
```

### Additional information:

 - `node -v` prints:  v20.2.0
 - Windows, macOS, or Linux?: Linux

**Comment by hjaber** [comment] 2023-05-30 01:24
downgrading to `pnpm@8.5.1` solved this for me in the meantime

**Comment by yceffort** [comment] 2023-05-30 05:15
I think old pnpm should also support installing lock file 6.1. 
Since 6.1 is not a major version change, the installation should be fine.

**Comment by reeversedev2** [comment] 2023-05-30 06:29
@hjaber I can confirm that by downgrading to pnpm@8.5.1 solved the issue for me as well.

**Comment by fdc-viktor-luft** [comment] 2023-05-30 10:53
Also happens with that dependency:

```
ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/@apidevtools/swagger-parser/10.1.0(openapi-types@12.1.3)' in pnpm-lock.yaml
```

Could it be related to dependencies starting with `/@`? 🤔

**Comment by sparanoid** [comment] 2023-05-30 10:57
Got exact the same error on Vercel after upgrading lockfile to 6.1:

```
Vercel CLI 29.3.6
--
03:03:47.647 | Detected `pnpm-lock.yaml` version 6.1 generated by pnpm 8...
03:03:47.656 | Installing dependencies...
03:03:48.200 | WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
03:03:48.212 | Lockfile is up to date, resolution step is skipped
03:03:50.644 | ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/@emotion/react/11.11.0(@types/react@18.2.7)(react@18.2.0)' in pnpm-lock.yaml
03:03:50.874 | BUILD_UTILS_SPAWN_1: Command "pnpm install" exited with 1
```

Downgrade to pnpm@8.5.1 works for me.

**Comment by zkochan** [comment] 2023-05-30 14:16
I'll try to port it to v7 later.
In the meantime, try to upgrade to v8 if you can.

**Comment by hosmelq** [comment] 2023-05-30 21:51
I am running `pnpm@8.5.1` in the server and `pnpm@8.6.0` in my local and having the same error.

**Comment by zkochan** [comment] 2023-05-31 00:37
There was a bug in the code that checks the version of the lockfile. That is why it fails. The version was changed to 6.1 and the code cannot detect it as v6. Update pnpm on the server to v8.6

**Comment by christianhg** [comment] 2023-05-31 06:51
If you, like me, experienced this problem with a v6.1 lockfile on Vercel, then good news: Looks like they updated pnpm now, effectively resolving the issue.

**Comment by zkochan** [comment] 2023-05-31 09:42
:ship: 7.33.0

for consistent install between v7 and v8 you also need to set `auto-install-peers` in `.npmrc` in the root of your project.
In v7 it is `false` by default while in v8 it is `true`. So if you use both, set the setting explicitly. Otherwise, `pnpm install --frozen-lockfile` will fail.

**Closed by zkochan** 2023-05-31 09:42 UTC
Labels: type: bug

**Comment by 99tech-hamid-ali** [comment] 2023-08-17 09:34
=> ERROR [stage0 3/3] RUN pnpm i --frozen-lockfile                                                                                                                                                                      1.2s 
------                                                                                                                                                                                                                        
 > [stage0 3/3] RUN pnpm i --frozen-lockfile:                                                                                                                                                                                 
#0 1.097  WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0                                                                           
#0 1.098 Lockfile is up to date, resolution step is skipped
#0 1.133  ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/@apollo/client/3.7.11(graphql@16.6.0)(react-dom@18.2.0)(react@18.2.0)' in pnpm-lock.yaml
#0 1.133 
#0 1.133 This issue is probably caused by a badly resolved merge conflict.
#0 1.133 To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
------
Dockerfile:47
--------------------
  45 |     # COPY ./bin/postinstall.js /app/bin/postinstall.js
  46 |     RUN npm install pnpm@8.1.1 -g
  47 | >>> RUN pnpm i --frozen-lockfile

**Comment by socar-poki** [comment] 2025-05-12 07:53
@zkochan The pnpm-lock.yaml file is version 9.0, and the pnpm package manager version is 9.1.0, but I'm experiencing the same issue as described.
Do you have any idea what might be causing this problem?
