### ISSUE TITLE
Fails to install from private registry (Azure Devops)

### ISSUE THREAD

**Issue by schummar** [pnpm/pnpm#1815] opened 2019-05-07 11:08 UTC
### pnpm version:
3.2.0

### Code to reproduce the issue:
.npmrc:
```
@{scope}:registry=https://{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/
//{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/:username=packageWriteAccess
//{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/:_password=***
//{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/:always-auth=true
```

Run:
`pnpm install`

### Expected behavior:
Dependencies - including from private registries - are installed.

### Actual behavior:
Downloading *.tgz file from private registry fails:
` ERROR  400 Authentication information is not given in the correct format. Check the value of Authorization header.: https://{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/@{scope}/{package}/-/{package}-4.0.12497.tgz`

### Additional information:
- `node -v` prints: `v11.10.0`
- Windows
- Works with pnpm version 2.17.8
- Works with `npm install`

**Comment by zkochan** [comment] 2019-05-07 23:08
Where is the `.npmrc` file located? Have you tried adding it to the package's folder?

**Comment by schummar** [comment] 2019-05-08 04:45
It is in the project folder, right next to package.json. If I remove it the error looks different - something about not finding that package - so pnpm does seem to pick it up.
And add I said: If I change nothing but downgrade to pnpm 2.17.8, it works.

**Comment by zkochan** [comment] 2019-05-08 21:25
Could you try different versions of pnpm to see which version caused the regression?

**Comment by schummar** [comment] 2019-05-10 08:01
3.0.0-beta.0 seems to be the first that fails
2.25.7 works

Btw. I checked the store and there lies our private project's index.json containing dependencies etc. so that part is working fine, only the tarball fetch fails.

**Comment by zkochan** [comment] 2019-05-10 08:34
Does it work if you try w/o lockfile in the repo?

**Comment by schummar** [comment] 2019-05-10 08:37
No, still fails. I did my experiment in freshly initialized folder, therefore containing only a package.json and .npmrc.
I tried to install using a fesh store as well `pnpm i --store .store ...`

**Comment by zkochan** [comment] 2019-05-10 23:08
What about other auth methods? Have you tried setting _authToken?
```
//{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/:_authToken=***
```

Also, can you reproduce it locally? Maybe you could debug it. The auth headers are set here: https://github.com/pnpm/pnpm/blob/643329bf7964bf6f8fe1e1b50b41916b94a444fc/packages/fetch-from-npm-registry/src/index.ts#L68-L88

**Comment by aquark** [comment] 2019-05-13 16:02
I'm having the same issue with a different private registry, which breaks when upgrading to 3.x.

In my case, I root caused the issue to the fact that `node-fetch-unix` does not remove authorization headers on redirect. There is an [open issue for this problem in the related node-fetch package](https://github.com/bitinn/node-fetch/issues/274). The private registry we are using redirects to a different domain with authorization data included in the URL, and that domain rejects the request when there is conflicting authorization data in the headers. It is not correct or safe to send authorization headers for one domain to a different domain on redirect. This isn't included in the fetch spec only because that spec doesn't allow the caller to provide authorization headers.

As a workaround until this is fixed in node-fetch-unix, you could use `redirect: 'manual'` and follow the redirect yourself after removing the authorization header.

**Comment by zkochan** [comment] 2019-05-13 19:20
@schummar so it appears that after the rename of VSTS to devops, they changed the `.visualstudio.com` domain for artifacts to `.azuere.com`.

If in your `.npmrc` you change
`//{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/`
to
`//pkgs.dev.azure.com/{organisation}/_packaging/my_feed/npm/registry/`

then it should work.

Related: https://github.com/microsoft/web-build-tools/issues/1274 
But I'll check why it works with v2. Maybe it is related to what @aquark described as `.visualstudio.com` probably redirects to `.azure.com`

**Comment by schummar** [comment] 2019-05-14 17:09
@zkochan changing the url in my .npmrc does not seem to work in my case.
I tried it with the related pull request though and this worked perfectly.

**Closed** 2019-05-14 19:53 UTC
Labels: regression, state: in progress, type: bug

**Comment by zkochan** [comment] 2019-05-14 20:14
:ship: [pnpm@3.3.2](https://github.com/pnpm/pnpm/releases/tag/v3.3.2)
