### ISSUE TITLE
Problem still exists with EBUSY

### ISSUE THREAD

**Issue by Aliziloubaf** [pnpm/pnpm#6231] opened 2023-03-17 14:46 UTC
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
 EBUSY  EBUSY: resource busy or locked, copyfile 'd:\pools\.pnpm-store\v3\files\91\9eded09712882972a3e568d465b89a5a1c12c81122a9f6052a47bb6d8b15127f864a0fe2246cd2ec402ae44c913751280ce297156ba41e45a75f8ddaabef4e' -> 'C:\xxx\node_modules\.pnpm\@swagger-api+apidom-core@0.69.0\node_modules\@swagger-api\_tmp_2716_bc7f600b996c76bc14cfcb02f9f226e1\cjs\index.cjs'

pnpm: EBUSY: resource busy or locked, copyfile 'd:\pools\.pnpm-store\v3\files\91\9eded09712882972a3e568d465b89a5a1c12c81122a9f6052a47bb6d8b15127f864a0fe2246cd2ec402ae44c913751280ce297156ba41e45a75f8ddaabef4e' -> 'C:\xxx\node_modules\.pnpm\@swagger-api+apidom-core@0.69.0\node_modules\@swagger-api\_tmp_2716_bc7f600b996c76bc14cfcb02f9f226e1\cjs\index.cjs'
Progress: resolved 886, reused 861, downloaded 3, added 799

C:\xxx>pnpm --version
7.30.0

C:\xxx>

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment] 2023-04-02 00:49
It is a duplicate of https://github.com/pnpm/pnpm/issues/6201

**Closed by zkochan** 2023-04-02 00:49 UTC
Labels: type: bug
