### ISSUE TITLE
CI complains of outdated lockfile but says the lockfile is up to date

### ISSUE THREAD

**Issue by tleunen** [pnpm/pnpm#5144] opened 2022-08-02 15:59 UTC
The CLI says the lockfile is up to date but it still failing when it runs on CI. Running `pnpm i` locally doesn't create any updates to the lockfile.

### pnpm version: 7.8.0

The issue exists since the release of 7.6.0. It works fine in 7.5.2

### Expected behavior:

CI doesn't complain about outdated file when the lockfile is updated.

### Actual behavior:

CI complains the lockfile is outdated

```
pnpm install --prefer-offline

Scope: all 21 workspace projects
Lockfile is up-to-date, resolution step is skipped
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with packages/eslint-plugin/package.json

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"

Exited with code exit status 1
```

### Additional information:

 - `node -v` prints: 16.16.0
 - Windows, macOS, or Linux?: OSX/Linux

**Comment by zkochan** [comment] 2022-08-02 17:58
can you create repository that reproduces the issue?

**Comment by tleunen** [comment] 2022-08-03 12:18
I'll try to make a repro of this, because this is happening in our monorepo at work.

**Comment by diesal11** [comment] 2022-08-04 11:56
I'm finding a similar issue also fixed by downgrading to 7.5.2, it seems that Pnpm wants to generate a different lockfile on Macos vs Linux.

Unfortunately this is also happening on my work monorepo so can't share a repro either.

**Comment by zkochan** [comment] 2022-08-06 00:59
Do you use the `auto-install-peers=true` setting?

**Comment by tleunen** [comment] 2022-08-06 13:05
Exactly, we have this setting enabled at the moment. I'll be able to try on Tuesday with the option set to false instead to see if it makes a difference

**Comment by zkochan** [comment] 2022-08-06 18:34
It was caused by this change: https://github.com/pnpm/pnpm/pull/5067

And a similar issue was already reported and fixed: https://github.com/pnpm/pnpm/issues/5080

But looks like there are still some edge cases.

**Comment by supalarry** [comment] 2022-08-08 13:32
Same here

**Comment by zkochan** [comment] 2022-08-09 22:52
Have you tried to remove your lockfile and node_modules, then to generate again and commit it? The issue is that pnpm now installs the root peer dependency automatically, so if you did not have the peer dependency in your package.json, your lockfile will now be considered outdated.

**Comment by tleunen** [comment] 2022-08-10 14:53
> Have you tried to remove your lockfile and node_modules, then to generate again and commit it?

Unfortunately this doesn't fix the issue.

The only way to fix it seems to be by removing `auto-install-peers`

**Comment by supalarry** [comment] 2022-08-17 10:11
@zkochan removing lockfile and node_modules did not work. What helps is moving a peer dependency from `peerDependencies` to `devDependencies`. For example I had following error

```
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with config/stylelint-config/package.json
```

and `stylelint-config/package.json` had `autoprefixer` in `peerDependencies` and once I moved it to `devDependencies` the error disappeared. But I have more cases like this...

**Comment by supalarry** [comment] 2022-08-17 10:22
@tleunen same here, once I set `auto-install-peers` to false the error disappeared.

**Comment by jason-ha** [comment] 2022-08-31 19:32
Failure appears to happen when the peer dependency is a devDependency in root or any other workspace.
Snippet of pnpm-lock.yaml when issue occurs using file set listed below:
```
  packages/api-extractor-configuration:
    specifiers:
      '@microsoft/api-extractor': 7.x
    devDependencies:      <----- This would be "dependencies:" when there is no issue.
      '@microsoft/api-extractor': 7.29.5
```
Here is a minimalish set of files:
package.json:
```
{
  "name": "@my-stuff/pnpm-peer-lock-failure",
  "private": true,
  "devDpendencies": {
    "@microsoft/api-extractor": "^7.29.0"
  }
}
```
pnpm-workspaces.yaml:
```
prefer-workspace-packages: true
packages:
  - 'packages/*'
```
packages\api-extractor-configuration\package.json:
```
{
  "name": "@my-stuff/api-extractor-configuration",
  "version": "0.0.0-placeholder",
  "peerDependencies": {
    "@microsoft/api-extractor": "7.x"
  }
}
```

I attempted workaround of making the few peers we have be regular dependencies in the root, but the issue remained so long as any other package had the peer as a devDependency.

**Comment by jason-ha** [comment] 2022-09-02 21:35
For one repository I went ahead and added all of the peer dependencies explicitly. For another that we are upgrading from pnpm 6 to 7, we will be setting `strict-peer-dependencies=false` until there is a fix.

**Comment by zkochan** [comment] 2022-09-04 23:32
@jason-ha thanks

I was able to reproduce it https://github.com/zkochan/pnpm-issue-5144

**Comment by grug** [comment] 2022-09-05 09:40
@zkochan I see you've closed this - is there a resolution to this?

**Comment by zkochan** [comment] 2022-09-05 09:41
Soon in v7.11.0

**Comment by grug** [comment] 2022-09-05 09:42
Amazing - really appreciate it. I know it's probably difficult to say, but do you have an idea of when that will be published? Are we talking days/weeks/months? I'm assuming pretty soon 😄

**Comment by zkochan** [comment] 2022-09-05 09:43
Soon means like 5 minutes

**Comment by grug** [comment] 2022-09-05 09:43
Hahaha you're a legend!

**Comment by grug** [comment] 2022-09-05 12:19
I'm still receiving this issue on 7.11.0 but I'm not 100% sure how I'm going to be able to reproduce this for you as it's happening in a work project repository and it's pretty big.

**Comment by zkochan** [comment] 2022-09-05 12:36
Have you remove node_module and `pnpm-lock.yaml` and create a new lockfile?

**Comment by grug** [comment] 2022-09-05 13:23
@zkochan Yep with fresh node_modules and lockfile I'm still experiencing it 😢

**Comment by grug** [comment] 2022-09-05 15:55
I'll try to create a reproduction repository tomorrow. I'm hoping that if I just pull out all of the dependencies and devDependencies out of my project and run it through CI that it will fail in exactly the same way

**Comment by jason-ha** [comment] 2022-09-05 16:58
At least for the case I hit, it was sufficient to use `--frozen-lockfile` locally to reproduce the issue.

**Comment by yugasun** [comment] 2022-09-06 02:39
After set `auto-install-peers=false`, solve my problem.

**Comment by emahuni** [comment] 2022-09-06 08:06
yep, got this and had to delete pnpm entire store, my lock files (committed the deletion into vcs, I did this initially without these other measures and it didn't work), node_modules, .pnp.cjs; as if it's a new machine for the project. Then it works now. It seems as if pnpm is keeping some lockfile somewhere, and I suspect the store has something to do with it, coz I had done the other measures before and it still caused this error.

I have a monorepo setup as well, with auto-install-peers turned on.
Actually it's a metarepo - the workspaces just do what they do without the git repo in the root managing the entire worktree, they are ignored using .gitignore at each workspace dir glob, eg `packages/*` each project has its own git repo and can be used in another metarepo that's totally separate) 

Another things is, I recently upgraded to the version that just popped up a few hours ago pnpm 7.11.0, I think it also helped with solving this error. So maybe you guys need to check and confirm if your issues were resolved by this

**Comment by jason-ha** [comment] 2022-09-06 22:01
Thanks @zkochan - I tried 7.11.0 and was able to rollback my workarounds.
One other thing I noticed now using auto-install-peers is that some dependencies that were marked as `dev` dependencies in the lock file became production dependencies. It seems like peer dependencies should not become production dependencies unless there is a production dependency on the package that lists said peer dependencies.
Given `A` with peer dependency on `Peer`. Then `B` with dev dependency on `A` should produce a dev dependency on `Peer`. Only `C` with [production] dependency on `A` should produce a production dependency on `Peer`.

**Comment by emahuni** [comment] 2022-09-06 23:58
I just love the fact that it installs transitive peer dependencies. Yarn 1 was my go to pm, but for years they've been adamantly refusing to work on this seemingly intuitive feature. I had to use other means to auto instead peers for years hoping they'd fix this. I ditched it coz pnpm does everything much much better. @zkochan and team listen to feedback and they actually made this with regards to how people use package managers not how they want people to use package managers. Thanks a million, we will support your efforts.

**Comment by yugasun** [comment] 2022-09-08 09:05
After I update pnpm to `7.11.0` and set `auto-install-peers=true`, the issue never came up again.

**Comment by zkochan** [comment] 2022-09-08 09:32
> yep, got this and had to delete pnpm entire store, my lock files (committed the deletion into vcs, I did this initially without these other measures and it didn't work), node_modules, .pnp.cjs; as if it's a new machine for the project. 

@emahuni you had to only remove the lockfile and node_modules. The reason you need to remove node_modules is because there is a duplicate of the lockfile inside `node_modules/.pnpm/lock.yaml`. The store should not be removed.

**Comment by emahuni** [comment] 2022-09-12 11:51
> > yep, got this and had to delete pnpm entire store, my lock files (committed the deletion into vcs, I did this initially without these other measures and it didn't work), node_modules, .pnp.cjs; as if it's a new machine for the project.
> 
> @emahuni you had to only remove the lockfile and node_modules. The reason you need to remove node_modules is because there is a duplicate of the lockfile inside `node_modules/.pnpm/lock.yaml`. The store should not be removed.

yes, that's right, but it didn't work. The reason why I had to remove it is a long story, but it worked at the end.

I was having that issue, tried what you are saying and more (deleting all lock files, .pnp, node_modules, and everything as if I am using pnpm for the first time - I actually had to write a script to do this since i did this many many times in trial and error mode trying to see where I was hitting a wall, coz it initially worked). So I ended up:
-  completely ditching pnpm (actually removing it and all its stores etc), 
- went to yarn 3, ended up developing a transitive peer [dependency installer](https://www.npmjs.com/package/@emahuni/trans-peerdeps) coz yarn doesn't have peer deps installation,
- then was very annoyed by yarn 3 as it departs from yarn 1 usefulness, as you can't even do certain things anymore, it's a mess and probably the death of Yarn.
- went to npm 8... grew a beard using it, so had to stop my accelerated ageing and..., 
- came back to pnpm thinking where did it go wrong coz one time it worked. Then it just worked again.
- So I noticed that the issue must have been with the store, which one thing I wasn't touching.
- later on... it happened again, so I just deleted everything by running that same said script and the store this time, and it worked... so yeah there is something happening there. It's as if pnpm thinks my workspace is a CI or something when it does, I am not even using any CI pipeline anywhere for that matter. This is the reason how I came to find this issue after I had had to deal with it more twice, I wanted to see if anyone was aware this was happening and throw my 2 cents at it.

However, this is now my package manager of choice coz it's just super super duper badass! Though I feel there are still a few edge cases to fix, the whole concept is going in the correct direction. _cough support for something like yarn publish on v1 is needed pliz cough 😬_

**Comment by emahuni** [comment] 2022-09-12 11:59
> > > yep, got this and had to delete pnpm entire store, my lock files (committed the deletion into vcs, I did this initially without these other measures and it didn't work), node_modules, .pnp.cjs; as if it's a new machine for the project.
> > 
> > 
> > @emahuni you had to only remove the lockfile and node_modules. The reason you need to remove node_modules is because there is a duplicate of the lockfile inside `node_modules/.pnpm/lock.yaml`. The store should not be removed.
> 
> yes, that's right, but it didn't work. The reason why I had to remove it is a long story, but it worked at the end.
> 
> I was having that issue, tried what you are saying and more (deleting all lock files, .pnp, node_modules, and everything as if I am using pnpm for the first time - I actually had to write a script to do this since i did this many many times in trial and error mode trying to see where I was hitting a wall, coz it initially worked). So I ended up:
> 
> * completely ditching pnpm (actually removing it and all its stores etc),
> * went to yarn 3, ended up developing a transitive peer [dependency installer](https://www.npmjs.com/package/@emahuni/trans-peerdeps) coz yarn doesn't have peer deps installation,
> * then was very annoyed by yarn 3 as it departs from yarn 1 usefulness, as you can't even do certain things anymore, it's a mess and probably the death of Yarn.
> * went to npm 8... grew a beard using it, so had to stop my accelerated ageing and...,
> * came back to pnpm thinking where did it go wrong coz one time it worked. Then it just worked again.
> * So I noticed that the issue must have been with the store, which one thing I wasn't touching.
> * later on... it happened again, so I just deleted everything by running that same said script and the store this time, and it worked... so yeah there is something happening there. It's as if pnpm thinks my workspace is a CI or something when it does, I am not even using any CI pipeline anywhere for that matter. This is the reason how I came to find this issue after I had had to deal with it more twice, I wanted to see if anyone was aware this was happening and throw my 2 cents at it.
> 
> However, this is now my package manager of choice coz it's just super super duper badass! Though I feel there are still a few edge cases to fix, the whole concept is going in the correct direction. _cough support for something like yarn publish on v1 is needed pliz cough 😬_

Oh yah one thing I forgot to mention is that when I came back to pnpm, I had moved the .npmrc file into a bck dir when I ditched pnpm, so I was starting afresh.

you see that?

```
auto-install-peers=true
shamefully-hoist=true
node-linker=hoisted
strict-peer-dependencies=false

symlink=true
prefer-frozen-lockfile=false

shared-workspace-lockfile=false
prefer-workspace-packages=true
save-workspace-protocol=false
link-workspace-packages=deep
```
that was me trying to fix the issues before ditching pnpm, then this:

```
auto-install-peers=true
strict-peer-dependencies=false
link-workspace-packages=deep
```
 is now, working without any issues when I came back to pnpm. believe me, I had that config before and it didn't work, it wasn't about this config.

**Comment by zkochan** [comment] 2022-09-15 21:44
I think the original issue was fixed. If you have exact steps to reproduce, open a new issue.

**Closed by zkochan** 2022-09-15 21:44 UTC
Labels: type: bug

**Comment by tleunen** [comment] 2022-09-22 14:23
@zkochan Is there any verbose mode or anything that could help finding the root cause? I'm having hard time reproducing it in a smaller testcase than what I have at work. But I might have found out that the lockfile is not generated/updated when I turn `auto-install-peers` on (`auto-install-peers=true` in .npmrc).
I confirmed that by deleting the file and running pnpm install again and nothing is generated. (tested with recent v7.12.1)

**Comment by emahuni** [comment] 2022-09-22 15:58
Are you by any chance using workspaces?

**Comment by emahuni** [comment] 2022-09-22 15:59
> @zkochan Is there any verbose mode or anything that could help finding the root cause? I'm having hard time reproducing it in a smaller testcase than what I have at work. But I might have found out that the lockfile is not generated/updated when I turn `auto-install-peers` on (`auto-install-peers=true` in .npmrc). I confirmed that by deleting the file and running pnpm install again and nothing is generated. (tested with recent v7.12.1)

Are you by any chance using workspaces at work?

**Comment by zkochan** [comment] 2022-09-22 16:11
Maybe you have this issue: https://github.com/pnpm/pnpm/issues/5372#issuecomment-1253967126

**Comment by callmeberzerker** [comment] 2022-11-21 16:26
I am still hitting this issue in `7.14.1`. Everything works locally. Can we see which package is outdated?

**Comment by HopeKenga** [comment] 2022-11-24 08:16
I'm hitting with 7.17.0 and have followed all the processes but the workflow is still failing

**Comment by NullVoxPopuli** [comment] 2023-02-14 15:48
I'm getting this error as well. `hasBin: true` is getting removed: https://github.com/CrowdStrike/ember-headless-form/actions/runs/4175506300/jobs/7230511766#step:4:192

which... makes sense.. most of these deps don't have bins.
But why is local pnpm, (also 7.27.0), adding `hasBin: true`?

**Comment by WINOFFRG** [comment] 2023-05-07 23:12
Hi! Can anyone please help me with this issue
I am literally fed up of this, Builds and Installation all succeeds on local env but on github actions repeatedly getting the issue
https://github.com/WINOFFRG/limeplay/actions/runs/4909772277/jobs/8766378903

I have tried all the steps recommended by the community above. Waiting for response!

**Comment by zkochan** [comment] 2023-05-07 23:16
Try to use pnpm v8

https://github.com/WINOFFRG/limeplay/blob/77215e95b258b3d972e064f4bbcbf7fbf4773b08/.github/composite-actions/install/action.yml#L10

**Comment by jjangga0214** [comment] 2023-06-08 02:51
@zkochan This issue appears on v8 as well..

**Comment by wallace-sf** [comment] 2023-08-12 00:37
Hello @zkochan I also experienced the error as well on version 8.6.12, when i tried to run CI in vercel. Take a look at logs:

```
[21:04:32.441] Running build in Cleveland, USA (East) – cle1
[21:04:32.503] Cloning Repository (Branch: feature/wCPANBaO, Commit: d94807e)
[21:04:33.246] Cloning completed: 743.17ms
[21:04:34.797] Restored build cache
[21:04:34.828] Running "vercel build"
[21:04:35.336] Vercel CLI 31.2.3
[21:04:36.001] Warning: Detected "engines": { "node": ">=18.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[21:04:36.024] Detected `pnm-lock.yaml` version 6 generated by pnpm 8...
[21:04:36.024] Running "install" command: `pnpm install`...
[21:04:36.632]  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
[21:04:36.632]
[21:04:36.632] Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
[21:04:36.632]
[21:04:36.632] Failure reason:
[21:04:36.634] specifiers in the lockfile ({
  "@headlessui/react":"^1.7.15",
  "@heroicons/react":"^2.0.18",
  "@reduxjs/toolkit":"^1.9.5",
  "axios":"^1.4.0",
  "classnames":"^2.3.2",
  "flatpickr":"^4.6.13",
  "formik":"^2.4.2",
  "immer":"^10.0.2",
  "jwt-decode":"^3.1.2",
  "lodash":"^4.17.21",
  "react":"^18.2.0",
  "react-dom":"^18.2.0",
  "react-flatpickr":"^3.10.13",
  "react-redux":"^8.1.1",
  "react-router-dom":"^6.14.2",
  "react-secure-storage":"^1.2.2",
  "tiny-warning":"^1.0.3",
  "usehooks-ts":"^2.9.1",
  "validator":"^13.9.0",
  "yup":"^1.2.0",
  "@commitlint/cli":"^17.6.5",
  "@commitlint/config-conventional":"^17.6.5",
  "@types/lodash":"^4.14.196",
  "@types/react":"^18.0.37",
  "@types/react-dom":"^18.0.11",
  "@types/validator":"^13.7.17",
  "@typescript-eslint/eslint-plugin":"^5.59.0",
  "@typescript-eslint/parser":"^5.59.0",
  "@vitejs/plugin-react":"^4.0.0",
  "autoprefixer":"^10.4.14",
  "eslint":"^8.38.0",
  "eslint-config-prettier":"^8.8.0",
  "eslint-config-standard-with-typescript":"^35.0.0",
  "eslint-import-resolver-typescript":"^3.5.5",
  "eslint-plugin-import":"^2.25.2",
  "eslint-plugin-import-helpers":"^1.3.1",
  "eslint-plugin-n":"^15.0.0",
  "eslint-plugin-prettier":"^4.2.1",
  "eslint-plugin-promise":"^6.0.0",
  "eslint-plugin-react":"^7.32.2",
  "eslint-plugin-react-hooks":"^4.6.0",
  "eslint-plugin-react-perf":"^3.3.1",
  "eslint-plugin-react-refresh":"^0.3.4",
  "husky":"^8.0.0",
  "lint-staged":"^13.2.2",
  "postcss":"^8.4.24",
  "prettier":"^2.8.8",
  "prettier-plugin-tailwindcss":"^0.3.0",
  "rimraf":"^5.0.1",
  "tailwindcss":"^3.3.2",
  "tsc-files":"^1.1.4",
  "typescript":"^5.0.2",
  "vite":"^4.3.9",
  "vite-tsconfig-paths":"^4.2.0"
}) don't match specs in package.json ({
  "@commitlint/cli":"^17.6.5",
  "@commitlint/config-conventional":"^17.6.5",
  "@types/lodash":"^4.14.196",
  "@types/react":"^18.0.37",
  "@types/react-dom":"^18.0.11",
  "@types/validator":"^13.7.17",
  "@typescript-eslint/eslint-plugin":"^5.59.0",
  "@typescript-eslint/parser":"^5.59.0",
  "@vitejs/plugin-react":"^4.0.0",
  "autoprefixer":"^10.4.14",
  "eslint":"^8.38.0",
  "eslint-config-prettier":"^8.8.0",
  "eslint-config-standard-with-typescript":"^35.0.0",
  "eslint-import-resolver-typescript":"^3.5.5",
  "eslint-plugin-import":"^2.25.2",
  "eslint-plugin-import-helpers":"^1.3.1",
  "eslint-plugin-n":"^15.0.0",
  "eslint-plugin-prettier":"^4.2.1",
  "eslint-plugin-promise":"^6.0.0",
  "eslint-plugin-react":"^7.32.2",
  "eslint-plugin-react-hooks":"^4.6.0",
  "eslint-plugin-react-perf":"^3.3.1",
  "eslint-plugin-react-refresh":"^0.3.4",
  "husky":"^8.0.0",
  "lint-staged":"^13.2.2",
  "postcss":"^8.4.24",
  "prettier":"^2.8.8",
  "prettier-plugin-tailwindcss":"^0.3.0",
  "rimraf":"^5.0.1",
  "tailwindcss":"^3.3.2",
  "tsc-files":"^1.1.4",
  "typescript":"^5.0.2",
  "vite":"^4.3.9",
  "vite-tsconfig-paths":"^4.2.0",
  "@headlessui/react":"^1.7.15",
  "@heroicons/react":"^2.0.18",
  "@reduxjs/toolkit":"^1.9.5",
  "axios":"^1.4.0",
  "classnames":"^2.3.2",
  "flatpickr":"^4.6.13",
  "formik":"^2.4.2",
  "immer":"^10.0.2",
  "jwt-decode":"^3.1.2",
  "lodash":"^4.17.21",
  "react":"^18.2.0",
  "react-dom":"^18.2.0",
  "react-redux":"^8.1.1",
  "react-router-dom":"^6.14.2",
  "react-secure-storage":"^1.2.2",
  "tiny-warning":"^1.0.3",
  "usehooks-ts":"^2.9.1",
  "validator":"^13.9.0",
  "yup":"^1.2.0"
})
[21:04:36.667] Error: Command "pnpm install" exited with 1
```

**Comment by wallace-sf** [comment] 2023-08-12 01:10
I had the same problem, but then I realized that there was an outdated `pnpm-lock.yaml` file in my repository. At some point, I had added it to `.gitignore`. When I tried to deploy on Vercel, I encountered this error. After uploading a new version of the lockfile, the error disappeared

**Comment by Usnul** [comment] 2023-11-14 08:03
Here's what worked for me:

```sh
pnpm i --fix-lockfile --config.auto-install-peers=false
```

Run this locally, then commit your updated lockfile.
