### ISSUE TITLE
pnpm creates multiple installations for same dependency

### ISSUE THREAD

**Issue by d4mr** [pnpm/pnpm#5351] opened 2022-09-13 20:39 UTC
### Code to reproduce the issue:

I have a workspace with main app A and a library B. A had `react-query` as a dependency. B has `react-query` as a peerDependency. For library B to be able to work, the dependency needs to be a singleton.

Even though they are using the same exact version, the dependency inside node_modules is being symlinked to two different places:
In App A is being symlinked to: `node_modules/.pnpm/react-query@3.39.2_biqbaboplfbrettd7655fr4n2y/node_modules/react-query`
In Library B is being symlinked to: `node_modules/.pnpm/react-query@3.39.2/node_modules/react-query`

I have tried `pnpm up -r` and `syncpack`. I have also tried to set an override for `react-query: "^3.39.2"`.
None of this solved my problem.

Here are the two different listings for react-query in the pnpm lock file:

```
  /react-query/3.39.2:
    resolution: {integrity: sha512-F6hYDKyNgDQfQOuR1Rsp3VRzJnWHx6aRnnIZHMNGGgbL3SBgpZTDg8MQwmxOgpCAoqZJA+JSNCydF1xGJqKOCA==}
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: '*'
      react-native: '*'
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-native:
        optional: true
    dependencies:
      '@babel/runtime': 7.19.0
      broadcast-channel: 3.7.0
      match-sorter: 6.3.1
    dev: true

  /react-query/3.39.2_biqbaboplfbrettd7655fr4n2y:
    resolution: {integrity: sha512-F6hYDKyNgDQfQOuR1Rsp3VRzJnWHx6aRnnIZHMNGGgbL3SBgpZTDg8MQwmxOgpCAoqZJA+JSNCydF1xGJqKOCA==}
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: '*'
      react-native: '*'
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-native:
        optional: true
    dependencies:
      '@babel/runtime': 7.19.0
      broadcast-channel: 3.7.0
      match-sorter: 6.3.1
      react: 18.2.0
      react-dom: 18.2.0_react@18.2.0
    dev: false
```

The obvious difference seems to be `dev` with true and false for each of these. No clue why they both exist though. Some help here would be greatly appreciated, since our monorepo breaks if we cannot use the same version for these packages.

### Expected behavior:
The dependency should be reused, and the same dependency in both A and B should symlink to the same folder.

### Actual behavior:
The dependency is duplicated, causing issues in the monorepo since it cannot be used as a singleton. This is especially problematic with react context related libraries, since this makes it impossible to extract functionality to a different library.

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOs

**Comment by szmarci** [comment] 2022-09-15 08:26
I can confirm this, I have the same issue with the same library with the exact same versions and monorepo setup. I can create a repro repo if it helps.

**Comment by szmarci** [comment] 2022-09-15 13:12
@d4mr See my comment here: [https://github.com/TanStack/query/issues/3595#issuecomment-1248074333](https://github.com/TanStack/query/issues/3595#issuecomment-1248074333)
It solved this issue for me.

**Comment by d4mr** [comment] 2022-09-16 02:37
@szmarci both React and React DOM are already peer dependencies, so not much I can do

**Comment by szmarci** [comment] 2022-09-16 07:53
@d4mr I also had to run `pnpm purge` and clear the browser cache before running my app.
I created a minimal repository: https://github.com/szmarci/pnpm
Master branch is the working one, fail branch is... well the failing one. Maybe you can try it if it behaves the same for you.

**Comment by d4mr** [comment] 2022-09-16 08:14
@szmarci I cannot find any documentation for `pnpm purge` on their website or in the manpage. Running it gives me this: `Unable to purge disk buffers: Operation not permitted`

Since I am unable to find documentation for the command, I have no idea what it does.

Also taking a look at your `fail` branch in your repro repo:

```
  /react-query/3.39.2:
    resolution: {integrity: sha512-F6hYDKyNgDQfQOuR1Rsp3VRzJnWHx6aRnnIZHMNGGgbL3SBgpZTDg8MQwmxOgpCAoqZJA+JSNCydF1xGJqKOCA==}
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: '*'
      react-native: '*'
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-native:
        optional: true
    dependencies:
      '@babel/runtime': 7.19.0
      broadcast-channel: 3.7.0
      match-sorter: 6.3.1
    dev: false

  /react-query/3.39.2_sfoxds7t5ydpegc3knd667wn6m:
    resolution: {integrity: sha512-F6hYDKyNgDQfQOuR1Rsp3VRzJnWHx6aRnnIZHMNGGgbL3SBgpZTDg8MQwmxOgpCAoqZJA+JSNCydF1xGJqKOCA==}
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: '*'
      react-native: '*'
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-native:
        optional: true
    dependencies:
      '@babel/runtime': 7.19.0
      broadcast-channel: 3.7.0
      match-sorter: 6.3.1
      react: 17.0.2
      react-dom: 17.0.2_react@17.0.2
    dev: false
```

These are the two react-query listings in your pnpm lockfile.  The second one has

```
      react: 17.0.2
      react-dom: 17.0.2_react@17.0.2
```

in its dependencies while the first does not. This clues in to why what you did might be working.

However, my lockfile also has another line of difference, with the `dev` property being `true` and `false`.

My best guess is that for one of these packages, dev dependencies are also being installed. However I have no clue as to why and how.

**Comment by d4mr** [comment] 2022-09-16 08:25
@szmarci Another thing to note that in your example, where it is working, these are your ilbrary dependencies:
```
{
  "name": "@org/b",
  "version": "0.0.0",
  "main": "./index.ts",
  "types": "./index.ts",
  "license": "MIT",
  "devDependencies": {
    "typescript": "^4.6.4",
    "@types/react": "^17",
    "@types/react-dom": "^17"
  },
  "dependencies": {

  },
  "peerDependencies": {
    "react-query": "^3.39.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

Notably, `react-query` is only listed as a peerDependency and not also as a dev dependency. 

If I too remove it from devDependencies and only have it in my peerDependencies, then the multiple dependency problem **gets resolved for me.** However, this is useless since I am not able to import `useQuery`, and the entire reason we wanted to have a separate library with `react-query` as a peer dependency was so that we can extract some of the query hooks and reuse them across apps.

The default behaviour for pnpm when you run `pnpm add react-query --save-peer` is to add it to both peerDependency and devDependency, and also install it as a dev dependency. Without this happening, you cannot import anything from `react-query` (since the package is simply not installed for you to use).

**Comment by d4mr** [comment] 2022-09-16 09:48
> Why not? You can import `react-query` inside your library code where it is listed only as a peer dependency. It is resolved to the library's `node_modules` where you see it installed (it is although symlinked)

This is not the behaviour I get. Can you try having your dependency listed only as a peerDependency, and then run `pnpm prune` followed by `pnom install`?

For me if i only have it at as a peer dependency, react-query is not present in the library's node modules.

**Comment by szmarci** [comment] 2022-09-16 10:24
Yeah, it installs them for me. 
Have you tried setting `pnpm config set auto-install-peers true` before installing? Or have it in the `.npmrc` just like in the example repo?

**Comment by matzeeable** [comment] 2022-09-23 23:15
Hey! Perhaps this is related: https://github.com/pnpm/pnpm/issues/5348? The two different versions are created due to the `peerDependenciesMeta.*.optional` field.

**Comment by d4mr** [comment] 2022-09-24 10:12
> Hey! Perhaps this is related: #5348? The two different versions are created due to the `peerDependenciesMeta.*.optional` field.

Optional is false here, do you suggest setting this to true?

**Comment by matzeeable** [comment] 2022-09-24 10:32
Hey @d4mr ! PNPM creates two different versions because [`react-query` defines `react-dom` as `optional:true`](https://github.com/TanStack/query/blob/650fb99764c9ce5bc7075e3cea1f6ce01cf8f875/packages/react-query/package.json#L58-L61): `/react-query/3.39.2` and `/react-query/3.39.2_biqbaboplfbrettd7655fr4n2y`. PNPM does currently not consider sub-dependencies of own dependencies to resolve `optional` dependencies as "`true`".

What happens if you add `react-dom` as direct (dev-)dependency to both of your packages?

**Comment by d4mr** [comment] 2022-09-28 18:54
@matzeeable I can confirm that adding `react-dom` as a direct dev dependency did not help. There are still two different instances of the same version of react-query floating around.

**Comment by IPWright83** [comment] 2022-09-29 14:50
I've had exactly the same problem with `react-redux` and the fix was to include `react-dom` as a peer dependency. I believe it's related to https://pnpm.io/how-peers-are-resolved

**Comment by d4mr** [comment] 2022-09-29 15:55
@IPWright83 I am aware of this peer-dependency requirement, and `react`, `react-dom` and `react-query` have all been peer dependencies to begin with. The issue still occurs.

**Comment by unional** [comment] 2022-10-03 23:36
pnpm@7.10.0 seems to be working fine

**Comment by yuhang1995** [comment] 2022-10-10 02:38
> pnpm@7.10.0 似乎工作正常

I tried using pnpm@7.10.0, but two dependencies still appear.

This is a screenshot of the react-query version retrieved from the pnpm-lock.yaml file:
![image](https://user-images.githubusercontent.com/31569789/194792306-b3bf2809-c40a-4bc2-a747-8c2ffadaf3c7.png)

**Comment by TkDodo** [comment] 2022-10-10 17:16
I can confirm that adding `react` and `react-dom` as peerDependencies to my lib that also has `react-query` as peerDependency did the trick to de-duplicate react-query in node_modules.

I don't fully understand it to be honest. Why would it ever be a good idea to have the same version of a lib twice? This causes trouble if react context is used because everyone will then have their own context...

**Comment by IPWright83** [comment] 2022-10-10 17:25
@TkDodo I agree it is a pain, but this is mostly an issue with some of these stateful libraries. You could include lodash once for each package and I can't envisage you hitting any problems.

It comes down to versions I guess, the page I linked previously explains https://pnpm.io/how-peers-are-resolved in that the same dependency may have different peers in those 2 cases so the only safe thing to do is duplicate them for the isolation.

I think it probably makes sense, but maybe debugging why could be made easier, or even a warning saying that a package has been included twice.

**Comment by unional** [comment] 2022-10-10 20:34
I do see some problem with the resolution algorithm.

For example, I have a monorepo.
Say the package I have problem with is `@typescript-eslint/eslint-plugin`.

1. I add an unrelated depended to one package (e.g. `pnpm --filter pkg-a add some-package`).
2. `pnpm` adds the package but also changed the hash of `@typescript-eslint/eslint-plugin` in another package (e.g. `pkg-b`).
3. I manually edit the lock file to revert that change.
4. `pnpm i --force`
5. The change in step 2 didn't occur.
6. I delete the lock file
7. `pnpm i`
8. Things are still working correctly.

That means, step 1 produces a different resolution compare to step 7.

**Comment by belgattitude** [comment] 2022-10-16 12:17
Hi, I've created a separate issue that is related https://github.com/pnpm/pnpm/issues/5351. Hope it does not create too much noise.

**Comment by d4mr** [comment] 2022-10-17 12:40
Hello again, this is an issue that we are still facing, I wanted to understand if the problem has been communicated sufficiently well, or something like a reproducible repo would help.

I don't have clarity around whether this is a bug, or something that has gone with my config.
Would very much appreciate an answer.

**Comment by unional** [comment] 2022-11-01 21:54
ref: https://github.com/pnpm/pnpm/discussions/5435

**Comment by dmichon-msft** [comment] 2022-11-03 21:13
In the issue at the top, the consuming package of the first version does not specify a `react` or `react-dom` in `dependencies` or `devDependencies`, so pnpm _correctly_ does not provide a version of them to `react-query` when installing it in that package.

For the second version, the caller _has_ specified a version of both `react` and `react-dom` in either `devDependencies` or `dependencies`, so pnpm links `react-query` against those provided versions.

Solution to deduplicate the version is to have the caller of the first version specify `react` and `react-dom` in either `devDependencies` or `dependencies`. If they are already `peerDependencies`, then `devDependencies` would be the correct field.

The `peerDependencies` field, for reference, means absolutely nothing in a workspace package (with possible exception of if `dependenciesMeta` has `injected: true` specified, in which case peer dependency resolution is possible), since there is not a "consuming package".

**Comment by zgriesinger** [comment] 2022-11-04 22:03
https://github.com/zgriesinger/pnpm-nest-mono

I'm having a similar issue here, I'm not sure where the problem is, but it looks like singleton classes like `@nestjs/core` have issues with pnpm

**Comment by belgattitude** [comment] 2022-11-05 09:33
@zgriesinger did you try to run https://www.npmjs.com/package/pnpm-deduplicate to see if it helps ?

**Comment by zgriesinger** [comment] 2022-11-07 22:39
I have not yet @belgattitude 

We did figure out a workaround for the time being (My Repo above `fixed` branch)

We found that the differences were `optionalDependencies`. If we include the same `optionalDependencies` on all internal dependencies it fixes things for now. I would hope that `pnpm` would consider an option to work around it.

**Comment by sabasayer** [comment] 2022-12-03 22:41
I had the same problem with pinia. Store was stopped working because two different versions. After couples of hours research i figured out that i was using different typescript versions in my packages as devDependency. For that pnpm was creating 2 dependencies for pinia. Check your pnpm.lock and carefully investigate the differences between 2 dependencies.

**Comment by tjx666** [comment] 2022-12-12 18:35
many same condition, cause vite bundle many copy of same dependency:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/41773861/207126627-38f0d935-8b09-4926-9903-e5a7c44e4256.png">

**Comment by desfero** [comment] 2023-01-20 11:40
This was a tricky one we had to solve in a complex monorepo setup. In our case, the problem was with duplicated `@apollo/client` and `react-query` due to the `react-dom` optional peer dependency.
@zkochan would be so good to have a nice way of solving (or at least having some sort of warning) when different packages in the monorepo resolve different packages due to unmeet optional `peerDependencies`. 
I would propose adding additional check to the brilliant https://github.com/ocavue/pnpm-deduplicate package to at least show `error/warning` when this happens.

**Comment by fedeee** [comment] 2023-02-10 07:40
Hey @desfero would you be able to share how you fixed the issue ? We're having  similar problem with `@apollo/client` and  "@vue/apollo-composable" in our turbo monorepo where imported packages don't seem to recognize the default apollo client  id provided upstream. Interestingly this only happens when serving the bundle statically and not when starting the app via the local dev server provided by vite.

**Comment by sneko** [comment] 2023-02-18 00:35
@tjx666 did you solve your issue https://github.com/pnpm/pnpm/issues/5351#issuecomment-1347041730?

I have something similar, they got a random suffix. Not a suffix describing an unmatched `peerDependency` (like described in https://pnpm.io/how-peers-are-resolved).

It seems a basic question https://github.com/pnpm/pnpm/discussions/6055 but I'm not sure of the recommended way to share the same dependency between all my packages (I don't want my build to bundle 2 times the same code since I use the same versions...)

Thank you,

**Comment by unional** [comment] 2023-02-18 07:59
From https://github.com/pnpm/pnpm/discussions/6055#discussioncomment-5016072, will see if v6 fixes this.

**Comment by sneko** [comment] 2023-02-18 14:45
@unional v6 format helped me removing duplications. It's still a manual work but here what I did: https://github.com/pnpm/pnpm/discussions/6055#discussioncomment-5018827

**Comment by zkochan** [comment] 2023-03-20 10:16
This should be fixed if you use [`dedupe-peer-dependents=true`](https://pnpm.io/npmrc#dedupe-peer-dependents)

It is true by default in v8.

**Closed by zkochan** 2023-03-20 10:16 UTC
Labels: type: bug
