### ISSUE TITLE
Recursive Runs with Multiple Packages Lose Color

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2148] opened 2019-11-11 15:03 UTC
### Code to reproduce the issue:

Run a recursive command which outputs text with ansi colors `stdio`. For example, using `rollup` and `ava`:

```console
$ pnpm run test --filter ./packages/strip --filter ./packages/replace
```

### Expected behavior:

Expectation is that there exists a means to disable the muting of colors by pnpm and allowing the intended colors and ansi codes to be displayed. 

### Actual behavior:

The image below demonstrates what actually occurs. 

![Imgur](https://i.imgur.com/yOGbwh3.png)

As you can see above, `rollup`s output has been "muted" and greyed. While the image below shows the output from `pnpm run build --filter ./packages/strip`. Note that colors are correct when only one package is run against.

![Imgur](https://i.imgur.com/hC39qko.png)

### Additional information:

 - `node -v` prints: 12.3.1
 - Windows, OS X, or Linux?: Mac OS

**Comment by panoply** [comment] 2020-06-02 19:02
Bumping this. 

It would be great if when passing the `--color`  flag via an pnpm command that colours will be inherited/respected, as of now `--color` will just print white. 

I might be wrong, but I do recall reading somewhere that pnpm intentionally mutes/strips stdout when running recursively, don't hold me to that because I may have it confused with another project. Eitherway, I would love to see this.

**Comment by zkochan** [comment] 2020-06-02 22:19
We can make the child processes inherit the parent's stdio

https://github.com/pnpm/pnpm/blob/5a51caa594f895b9d5427ff6093ed4f58ea1aad5/packages/plugin-commands-script-runners/src/runRecursive.ts#L40-L43

But it will be a mess. Is that ok?

**Comment by panoply** [comment] 2020-06-02 23:59
> But it will be a mess. Is that ok?

So the pnpm output text when running recursive commands would be sacrificed? ie: we loose path prefix?

**Comment by zkochan** [comment] 2020-06-03 00:06
correct

**Comment by panoply** [comment] 2020-06-03 00:15
I've only partially explored the code base, at what point does pnpm strip the piped stdio when generating the recursive output? I see that chalk and [supports-color](https://www.npmjs.com/package/supports-color) is used, can we not leverage the environment variable? In my opinion, the way in which pnpm facilitates logging is a huge part of its aesthetic and the overall pnpm feel (so-to-speak).

**Comment by panoply** [comment] 2020-06-03 00:35
For more context, opposed to inheriting, when the `--color` flag is detected, can we not parse the piped stdio and remove any characters that would cause conflict (eg: `(\n\s{0,1}|\-{5,}`) while preserving newlines and from here split out and appropriate?

**Comment by rhyek** [comment] 2020-11-06 04:36
lerna seems preserve colors with `--parallel`:

![image](https://user-images.githubusercontent.com/702922/98326565-2aa71000-1fb7-11eb-92da-024bab7d80ad.png)

**Comment by zkochan** [comment] 2020-11-06 10:22
if Lerna managed to do it, then we can probably as well.

**Comment by rhyek** [comment] 2021-01-25 01:26
Any idea when this might get looked at? With microsoft/TypeScript#40584 fixed this is the only issue I'm waiting for to switch over from lerna.

**Comment by panoply** [comment] 2021-08-21 13:03
At what point is pnpm stripping the stdio? This one is becoming a little difficult to wrangle lately, which module handles this action?

**Comment by ghostdevv** [comment] 2021-11-05 16:09
Does anyone have a solution to this?

**Comment by rhyek** [comment] 2021-11-05 16:31
Btw, I was wrong about Lerna handling this correctly. In general, it is my understanding that programs will internally decide wether to output color escape codes and usually they do so by detecting if they are currently attached to a tty. If not, they do not output the codes. Pnpm and lerna will pipe stdout of programs they manage for us so that they can prefix their output for our benefit. Doing so means the programs will not be running inside a tty directly.

Some programs allow for forcing their output via some environment variable or command line argument. For example, node programs that use https://www.npmjs.com/package/chalk can set `FORCE_COLOR=1`.

I don't think a general solution applicable to all programs regardless of their support for flags is something pnpm (or lerna) can easily or should do. I might be wrong about this, but I think they would have to run some sort of pseudo terminal (maybe https://github.com/microsoft/node-pty?) per program so they think they're inside a tty, capture their output, and finally output that with the colored prefixes to the real tty.

**Comment by zheeeng** [comment] 2022-02-18 04:18
I'm using npm-run-all, it managed output color, can we try its solution?

**Comment by woubuc** [comment] 2022-04-12 12:50
So I've tracked down where the colour gets stripped because I ran into this issue and it is a little annoying to lose all colour output.

All ANSI codes are stripped while truncating output lines from lifecycle scripts in [packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts:270](https://github.com/pnpm/pnpm/blob/5e79891033076eb5c963b67e3917f349ae493feb/packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts#L270-L272). 

This needs to be replaced with a better solution that will truncate the line while being aware of ANSI escape codes, like for instance the [`cli-truncate`](https://www.npmjs.com/package/cli-truncate) package.

**Comment by sebaplaza** [comment] 2022-09-19 20:09
Any advance on this ?

**Comment by zkochan** [comment] 2022-10-15 22:57
There was an attempt to make it work but it breaks the output: https://github.com/pnpm/pnpm/pull/4559#issuecomment-1097800003

**Comment by DzmitryFil** [comment] 2023-01-20 21:31
+1 very annoying

**Comment by pokey** [comment] 2023-03-12 16:29
Is it not risky to run with `FORCE_COLOR=1`?  I believe this environment variable would be inherited by all children of a script.  What if a program invokes another program and pipes that output to a file?  It would be incorrect / surprising to get color codes there

@rhyek's solution of giving each script its own pty using eg https://github.com/microsoft/node-pty seems like the safest bet.  It seems like if `pnpm` detects that it is attached to a tty, then it should use ptys for each recursive process.  But certainly possible I'm missing something here

**Comment by valerii15298** [comment] 2023-05-22 13:06
+1 also having problems with colours

**Comment by peteromano** [comment] 2023-06-02 23:54
Yea this issue really stagnated..

**Closed** 2023-06-14 05:42 UTC
Labels: area: monorepo, area: lifecycle-scripts

**Comment by zkochan** [comment] 2023-10-21 03:27
I don't think it is a regression. The suggested solution never worked 100% correctly as I have posted in the comment: https://github.com/pnpm/pnpm/pull/4559#issuecomment-1097800003

**Comment by basickarl** [comment] 2024-09-12 01:12
Bump! Still na issue, would be exceptionally lovely to get this fixed!

**Comment by bnussman** [comment] 2024-09-16 01:35
Please reopen this issue. Still is an issue as of `9.9.0`

**Comment by bhuynhdev** [comment] 2024-09-25 02:07
Would love to have this fixed. Still an issue as of 9.10.0 It sucks that I have to install extra dependencies like `npm-run-all` when `pnpm` have this amazing `--parallel` option

**Comment by segevfiner** [comment] 2025-06-18 22:03
But that will also effect non-interactive/no-tty runs. We might want pnpm to set `FORCE_COLOR` only for recursive/multiple exec invocations with a tty.

**Comment by AhmedBaset** [comment] 2025-08-17 22:58
Is there a way to let pnpm output the full stdout with `-r` including qr code?

the usual `expo start` output looks like this

<img width="1194" height="1044" alt="Image" src="https://github.com/user-attachments/assets/7d086965-7907-4e5b-9de5-09b647e457b2" />

but with `pnpm -r` it's stripped to 

<img width="951" height="307" alt="Image" src="https://github.com/user-attachments/assets/31f550a2-4828-4309-a3bc-62e3a7c23ca4" />
