### ISSUE TITLE
Add `pnpm SCRIPT` as a shortcut for `pnpm run SCRIPT`

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2169] opened 2019-11-19 13:34 UTC
It's quite convenient to hot have to type `run`. In case there could be a naming conflict, you could simply not make it available without `run`.

So turning `pnpm run build` into `pnpm build`.

**Comment by timsuchanek** [comment] 2019-11-19 13:44
And btw, yarn doesn't even warn you if you e.g. have a script called `publish`. So you could even warn users once there is a conflict with builtin commands.

**Comment by zkochan** [comment] 2019-11-19 16:09
I am not sure about this one. This change would mean that any new pnpm command is a breaking change.

But we could probably update the `pnpx` command to run the script. pnpx currently works similarly to how [npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) works.

**Comment by ExE-Boss** [comment] 2019-11-23 13:34
This is&nbsp;a&nbsp;massive footgun, precisely&nbsp;for&nbsp;the&nbsp;reasons outlined&nbsp;above by&nbsp;@zkochan.

Therefore, I’m&nbsp;against implementing this&nbsp;proposal.

**Comment by timsuchanek** [comment] 2019-11-25 10:15
That totally makes sense. As I can also define my own aliases on this, I'm fine with it. They may however be other users coming from the yarn convenience, stumbling over this.

**Comment by ExE-Boss** [comment] 2019-11-25 13:28
I&nbsp;recommend&nbsp;adding some&nbsp;sort&nbsp;of&nbsp;detection for&nbsp;cases where&nbsp;`cmd`&nbsp;matches a&nbsp;`script`&nbsp;name in&nbsp;`package.json` and&nbsp;to&nbsp;suggest&nbsp;using <code>pnpm&nbsp;run&nbsp;&lt;script&gt;</code>&nbsp;instead.

**Comment by aparajita** [comment] 2019-12-18 17:44
Let's look at the pros and cons.

We run npm commands a **lot**. Which means that anything we do to make running scripts more convenient is a huge win for productivity and ease of use. By removing the need for `run` it accomplishes three things:

- Less typing.
- Less cognitive friction between built in commands and user commands (scripts).
- Alignment with those switching from yarn.

It's true that implementing this would mean that any new pnpm command **might** be a breaking change, but how often are new commands going to be added? The majority of new features at this point seem to be options on existing commands.

If we weigh the everyday, guaranteed benefits against the potential, occasional problems, it seems the benefits far outweigh the drawbacks.

**Comment by zkochan** [comment] 2019-12-18 17:51
ok, I have no objections

**Comment by timsuchanek** [comment] 2019-12-18 18:04
Well put, @aparajita! I 100% agree.
Btw in the meantime, I added an alias in my shell: `pnpm run command` -> `run command`.
That already saved me a lot of cognitive friction, as you nicely put it.

**Comment by ExE-Boss** [comment] 2019-12-19 03:21
I&nbsp;still don’t&nbsp;like&nbsp;this, since&nbsp;it&nbsp;mixes built‑in&nbsp;commands with&nbsp;package&nbsp;scripts.

**Comment by zkochan** [comment] 2019-12-19 10:33
cc @pnpm/collaborators

**Comment by nikoladev** [comment] 2019-12-19 11:48
I'm for always requiring `run`. I don't like the "potential breaking change" aspect of running scripts without `run` and also I prefer to know explicitly if I'm running my own commands or the built-in commands.

> Less typing.

I honestly don't mind the extra `run` that I need to type (I even use it when I'm working with yarn). Though the argument for less typing makes me think that **autocompletion** for scripts would be great for reducing typing!

No matter which package manager I use for my projects I always use `npm run` for running scripts because it can autocomplete the script names (I start typing the script name and then press `Tab`). I feel that this could reduce way more typing than getting rid of `run` for scripts.

I don't know how easy it is to implement autocomplete, but here's what I know about it: I use [zsh](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH) and [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh) which has an [npm plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/npm) that makes use of [npm's own completion script](https://github.com/npm/cli/blob/latest/lib/utils/completion.sh). Here's the [documentation on npm's completion](https://github.com/npm/cli/blob/b829d62c98506325d2afb2d85d191a8ff1c49157/docs/content/cli-commands/npm-completion.md)

> Alignment with those switching from yarn.

Maybe we can meet them halfway by reminding them to use `run` whenever they try to run a script without it. For example: 

* somebody tries to run the `start` script in their `package.json` with `pnpm start`
* it doesn't work because they didn't use `run`
* we check the `scripts` field in their `package.json` and if the command they used is found we can show a message saying something like:

```
If you want to run the `start` script from your package.json you should use:

`pnpm run start`
```

**Comment by zkochan** [comment] 2019-12-19 12:51
Seems like the majority is againts at the moment.

I think we can have a whitelist of commands the will work without `run`. Like `start`, `stop`, `restart`, `test` already work without `run`. We can add `lint`, `build`, `tsc`, `compile`, etc.

And as I mentioned earlier, we can make `pnpx` run the scripts also.

**Comment by timsuchanek** [comment] 2019-12-19 15:09
It's obvious that this is not a feature everyone would like to use and that's also fine. I like the whitelist approach, as that would fix the future problem of potential breaking changes, but still gives people who like this feature the possibility to integrate it into their workflows.

And on top there still can be an autocompletion both on top-level and on `run` level.

**Comment by aparajita** [comment] 2019-12-19 22:00
> Maybe we can meet them halfway by reminding them to use run whenever they try to run a script without it.

And every time that happens I think, "Well what the heck else could I possibly mean? If you're smart enough to figure out it's a script in the first place, why not just run it?!"

Obviously the yarn folks think the same way.

**Comment by bdchauvette** [comment] 2019-12-20 03:37
> > Maybe we can meet them halfway by reminding them to use run whenever they try to run a script without it.
> 
> And every time that happens I think, "Well what the heck else could I possibly mean? If you're smart enough to figure out it's a script in the first place, why not just run it?!"
> 
> Obviously the yarn folks think the same way.

This reminds me of how if you type `exit` in a Python REPL, it tells you to use `exit()` instead. :man_facepalming: 

That being said, I'm not sure the yarn model (which I do enjoy using) really translates nicely to pnpm. Some other considerations:

- how will this interact with `pnpm recursive`? I assume `pnpm m foo` would become `pnpm m run foo`, but I'm not sure if there are any edge cases we'd need to consider
- yarn forwards any flags directly to the script, but pnpm uses `--` for this. What should we do if someone calls `pnpm foo --some-flag`? If we pass through the flag, then it's inconsistent with the rest of the CLI. If we don't pass it through, then it breaks the "do what I mean" UX.

It seems a bit silly, but maybe we could alias `run` to `r`? Or maybe use something like `pnpm -- my-script` / `pnpm m -- my-script`?

**Comment by zkochan** [comment] 2020-02-03 21:21
> maybe we could alias run to r

No. Currently, `r` is an alias of `remove` (as in npm). But I think `r` should not be an alias of anything because we have 3 commands that start with `r` and it causes confusion.

> Yarn forwards any flags directly to the script, but pnpm uses -- for this.

This needs some investigation. The run command also has some flags, like `--if-present`. So the run command's own flags would have to be before the scripts name. The args parser will work with `pnpm run --if-present build` but `pnpm --if-present build` might be harder.

> how will this interact with pnpm recursive? I assume pnpm m foo would become pnpm m run foo, but I'm not sure if there are any edge cases we'd need to consider

Seems correct but, as I mentioned above, as a compromise, for now we will allow this only for some whitelist of script names.

**Comment by Bessonov** [comment] 2020-02-20 12:33
hm, what about something like
```bash
alias r="pnpm run"
```

It's even shorter than `pnpm whatever`.

**Comment by admmasters** [comment] 2020-07-01 08:23
So to weigh in on this - in a discussion at work about adopting pnpm someone actually cited one of the benefits for moving to yarn from npm was the convenience of "yarn <COMMAND>" vs "npm run <COMMAND>". So going the other way - when adopting pnpm it actually feels like a loss of productivity for them and a considerable amount of typing. Realistically you can alias "pnpm to p" or whatever - however this is not particularly useful in package.json scripts as you then add a dependency on everyone to have added the same alias to their environment.

I can see the pros and cons behind this, but wanted to give my perspective on this issue from interactions with co-workers. Thanks for the hard work on this by the way, seems to be gaining a lot of deserved traction at the moment and has actually caught some real issues with dependencies missing from the package.json etc.

**Comment by aparajita** [comment] 2020-07-01 14:44
I have to agree here @zkochan. Providing the incredible convenience **today** of not having to type "run" every time is well worth the **possibility** that a user script might have the same name as some future pnpm command. And in that case they can still use "run" to avoid the name clash, so I fail to see what the problem is. The same potential issue exists with yarn, and I've never heard anyone complain about it. On the other hand, people **are** complaining about the need for "run" in pnpm.

**Comment by ExE-Boss** [comment] 2020-07-01 15:18
I suggest taking the whitelist approach that was mentioned in <https://github.com/pnpm/pnpm/issues/2169#issuecomment-567477036>.

**Comment by zkochan** [comment] 2020-07-01 15:22
I am fine doing it for all but printing a warning if the command is not from the whitelist.

**Comment by aparajita** [comment] 2020-07-01 15:22
The users will curse us if you do that. The whitelist should be configurable. If the user specifically wants to be able to run **any** command, and they understand the **potential** future consequences, why limit them?

**Comment by zkochan** [comment] 2020-07-01 15:23
How will the users know about the potential consequences without the warning?

**Comment by aparajita** [comment] 2020-07-01 15:25
Warn them once then. If you warn them every time it will be incredibly annoying.

**Closed** 2020-07-05 21:23 UTC
Labels: state: needs better error message, type: feature

**Comment by zkochan** [comment] 2020-07-07 15:15
:ship: 5.3.0
