### ISSUE TITLE
Bundling up project for deployment

### ISSUE THREAD

**Issue by Aankhen** [pnpm/pnpm#2198] opened 2019-12-03 11:27 UTC
I’ve got a TypeScript monorepo with packages that are never published to any registry. I want to make a Docker image for one package. I need a way to bundle up a single package and its dependencies, along with either a whitelist of files or all files in the directory that aren’t in a blacklist (`.npmignore` would do fine, I guess) so that I can compile my code (maybe using something similar to a `prepublish` script), create a bundle, copy that bundle into my Node.JS-based image—no symlinks involved—and go.

There’s some overlap here with #1637, but in my case, I’m using a multi-stage Docker build: the `build` stage is where I’d like to compile and prepare the bundle, and the `deploy` stage is where I’d like to just copy that bundle over. If the end result were something that didn’t require `pnpm`, i.e. a regular Node.JS package, that would be even more convenient.

([From Gitter.](https://gitter.im/pnpm/pnpm?at=5de5504d55066245985650f4))

**Comment by Aankhen** [comment] 2019-12-04 16:56
I did manage to get a working version by first running `pnpm install -r` and then copying only the package I wanted into a different directory using `cp -rL`, which dereferences symlinks. The problem is, I ended up with a 4.3 GB image, because each package in the repo might have symlinks in its `node_modules` to another package which might have symlinks yadda yadda, so it’s not a single flat directory, like `pnpm` creates on its own, but rather a tree with many nested copies of each dependency.

**Comment by Aankhen** [comment] 2019-12-04 17:15
For the moment, as a workaround, I’ve switched to a single-stage Dockerfile that builds everything, then calls `pnpm prune --production` and manually removes all the redundant files & directories, like so:

```Dockerfile
RUN pnpm i -r --prefer-offline --frozen-lockfile \
    --filter $PACKAGE_NAME... --reporter=silent && \
  pnpm run -r build --filter $PACKAGE_NAME... --reporter=silent

RUN pnpm prune --production && \
  find . -type f -name '*.ts' -delete && \
  find . -type d -depth -empty -delete
```

**Comment by mledom** [comment] 2019-12-10 18:21
I have similar issues with a monorepo and trying to deploy my functions using the serverless framework. One thought mentioned was to create a `pnpm export` feature that could package all necessary dependencies and child dependencies without symlinks and recursive symlinks from shared local packages.

**Comment by Aankhen** [comment] 2019-12-10 19:58
I’m guessing that would no longer require `pnpm` itself to interact with the resultant package, so it would fulfill my requirements well.

**Comment by mledom** [comment] 2019-12-10 20:06
It might be useful to export with a flag to specify the folder if other than `node_modules` as to not hose up the existing setup.

**Comment by zkochan** [comment] 2019-12-11 00:17
So let's say there's a monorepo with 3 packages: foo, bar, qar. You want to deploy foo, which has bar as a dependency.

You run something like `pnpm export foo` and pnpm creates a new workspace with only `foo` and `bar` in it, with all their production dependencies installed. Sounds right?

**Comment by Aankhen** [comment] 2019-12-11 06:02
Yes, that sounds right. And, of course, it would include any transitive dependencies of `bar` as well.

**Comment by zkochan** [comment] 2019-12-11 10:21
This issue probably covers also #1919

> create a bundle, copy that bundle into my Node.JS-based image—no symlinks involved—and go

symlinks will still be present but between the exported projects and their dependencies. However, there will be an issue on Windows as there we use junctions. Junctions might break when copied to a docker image. I might be wrong though. Maybe docker handles it

**Comment by mledom** [comment] 2019-12-11 13:39
@zkochan when you export where are you thinking about storing the new workspace? I think specifying the folder to output the export would be a required arg. I was also thinking the symlinks would be removed on export. I did not have luck with our docker project either with symlinks. Like @Aankhen I'm having to `rsync` all the modules. I had to copy each file into the docker context or current directory path.

**Comment by zkochan** [comment] 2019-12-11 14:03
> when you export where are you thinking about storing the new workspace?

we can add a default location, for instance, `<workspace root>/dist`. And we can make it also configurable. Through a config setting and a CLI option/arg

> I was also thinking the symlinks would be removed on export

If symlinks cannot be copied to the image, then we will have to run pnpm inside the image to create the symlinks.

**Comment by Aankhen** [comment] 2019-12-11 17:08
Is there no way to avoid symlinks, since we’re creating the artifact from scratch anyway? It seems like it would drastically simplify using it.

**Comment by zkochan** [comment] 2019-12-11 17:17
npm/yarn create a flat node_modules to avoid symlinks. But that's not a possibility for us.

Another solution would be to override Node's resolution algorithm. That's what Yarn PnP and tink do. We will probably support Yarn PnP in the future but that thing is still very alpha.

**Comment by boardthatpowder** [comment] 2019-12-12 02:34
The sad thing is, this used to work with pnpm@3.5.3 using `pnpm i --no-lock --prod --shamefully-flatten --force`.  Unfortunately something changed after that version on the implementation of shamefully-flatten (renamed to shamefully-hoist from 4.0).

**Comment by zkochan** [comment] 2019-12-12 09:15
In that case, the issue is not with symlinks because all versions of pnpm used symlinks.

Could you create a sample repository for me to play with? My knowledge of dockers is entry level at the moment.

**Comment by boardthatpowder** [comment] 2019-12-12 14:16
My comment above regarding pnpm@3.5.3 is not specific to docker.  Running ‘pnpm i --no-lock --prod --shamefully-flatten --force’ with that version will create a true flat node_modules directory which we can then use to bundle all dependencies to upload to AWS Lambda.  We’ve had to pin our CI to that version, unable to upgrade to any more recent pnpm versions since.

**Comment by zkochan** [comment] 2019-12-12 14:59
In that case, this is unrelated to this issue. I don't know what changed in hoisting. `shamefully-hoist` works the same as `shamefully-flatten`. But pnpm v4 also hoists everything by default. Just not to the root of node_modules

**Comment by mledom** [comment] 2019-12-12 19:44
@zkochan I tried to create a test repo that shows the issues when you package for serverless and tried to show how docker fails when trying to build. Maybe @Aankhen can add what he has to do to get it to work but hopefully this helps. You can see in the screenshot how moment is included 2x and format-number is included 3x.
![image](https://user-images.githubusercontent.com/205515/70743512-e69b8480-1ced-11ea-8889-012483b674c9.png)
https://github.com/eletype/pnpm-test-monorepo

**Comment by Aankhen** [comment] 2019-12-12 20:55
My Dockerfile install `pnpm`, copies over the entire repository (`node_modules` directories are ignored, of course), then runs `pnpm install -r` with the relevant filters.

Just to clarify, the `COPY` command in a Dockerfile can only be provided a static list (which can use shell wildcards), so I can’t, for example, copy only the in-repo dependencies plus the package I’m building.

**Comment by Aankhen** [comment] 2019-12-23 09:24
I was thinking about it, and if `pnpm export` (or whatever it ends up being called) is what creates the symlinks, that might be okay. Then the first stage of the Dockerfile would run `pnpm export` to create the artifact and the second stage would copy over that artifact, and as long as the symlinks weren’t to a large `node_modules` in the root, it would work perfectly, even with plain `npm`. If the symlinks were to the root `node_modules`, then that would be more complicated. There would have to be some way of pruning the unused dependencies, although even then, it would be wasteful to download them in the first place.

**Comment by zkochan** [comment] 2020-02-05 09:29
For reference, there's a really good post from @kaidjohnson about how his team uses pnpm workspace in dockers: https://github.com/pnpm/pnpm/issues/1637#issuecomment-582086415

**Comment by Aankhen** [comment] 2020-02-05 14:26
The key there is the prefiltering—`pnmp` can’t do it, so they rely on Gradle to handle it instead.

**Comment by kaidjohnson** [comment] 2020-02-05 14:52
We only use gradle because our JavaScript pnpm workspaces are a part of a much larger monorepo orchestrated with gradle.

You could accomplish the same thing with only Docker, but the Dockerfile would be a bit more verbose. You could also accomplish the same thing with a node script (wired up to an npm script to be executed via `pnpm run`) to handle the prefiltering at the top of the workspace (or within each package, individually). If you created a stack of packages in, for example, `/docker-images`, these packages could have all of the dependencies defined for your build order and manage all of the build orchestration exclusively via node. It is, obviously, not an out-of-the-box solution, but has some power in its flexibility, allowing each repository to carefully tune the build logic for its individual needs.

**Comment by Aankhen** [comment] 2020-02-06 06:21
I understand what you’re saying, but most of that boils down to manually maintaining lists of dependencies, which defeats the purpose of using something like `pnpm`.

**Comment by zkochan** [comment] 2020-02-06 09:22
You can get the list of dependencies of projects by `pnpm list --depth -1 --filter <project name>... --parseable`

**Comment by Aankhen** [comment] 2020-02-12 07:05
Sorry for the delayed reply! Unfortunately, you can’t specify a dynamic list of files to copy in a Dockerfile. At most, you can only use wildcards.

**Comment by rnarayana** [comment] 2020-02-18 05:24
So if I understand the idea here, you build everything, and then remove the files you do not need in the final image.. is that it? Like, you have typescript files, you do pnpm i -r, build and create js files.. now you remove dev deps and ts files and you get the final docker image?

**Comment by Aankhen** [comment] 2020-02-18 08:27
That’s what we’re doing right now, yes.

**Comment by Bessonov** [comment] 2020-02-19 23:34
I'm not sure why it should be in scope of a package manager. For me, it's a task of tools like webpack, rollup etc. Actually, we use webpack to create a single file with all dependencies (incl. openapi definitions for validation in it) for deployment.

**Comment by bdchauvette** [comment] 2020-04-01 14:11
We currently also use webpack to bundle up all of our node services. In one sense it's pretty nice, because you get a go-like ability to have a "single file" deployment: build bundle, copy bundle, set `CMD ["node", "bundle.js"]`.

However, along the way we've encountered a decent number of issues with various node libraries that (rightfully) don't expect to be bundled by webpack. Off the top of my head, the most common issues have been things involving dynamic requires, shebangs, and optional dependencies. We've been able to work around everything that's come up, but it does feel very hackish having to cobble together a `webpack.config.js` just to be able to deploy a node service container.

As an alternative to creating a temp workspace, maybe we could have a "focused" install mode, that would explicitly copy all of the package files into a give package's `node_modules`, including  all workspace packages.

I think with this approach, a Dockerfile could then look something like:

```dockerfile
FROM node-image-with-pnpm AS build

# Copy entire workspace. Since this is a multistage build, it won't be included
# in the final image. Altervatively, you could just copy the files you know you
# need, like `pnpm-workspace.yaml`, `pnpm-lock.yaml`, and the various workspace
# package directories that are part of the dep graph.
COPY ./ ./

# Install everything directly into ./packages/my-package/node_modules, avoiding
# any symlinks that point outside of that directory. Copying everything into the
# directory should allow us to just COPY it in the next stage.
RUN pnpm install --focused --filter ./packages/my-package

FROM node AS deploy
COPY --from=build ./packages/my-package/ ./
CMD ["node", "index.js"]
```

**Comment by Aankhen** [comment] 2020-04-04 08:20
@bdchauvette: Yes, that’s exactly what I would like, too, and your experience with Webpack mirrors my own.

**Comment by zkochan** [comment] 2020-04-05 11:53
> As an alternative to creating a temp workspace, maybe we could have a "focused" install mode, that would explicitly copy all of the package files into a give package's node_modules, including all workspace packages.

But shouldn't the packages be installed from the registry?
I guess we could do this with packages that are private.
Also what about packages that installed in the root package of the repository? Probably those dependencies should be installed as dependencies of the focused package.

**Comment by hardfist** [comment] 2020-04-23 12:48
I use https://github.com/choffmeister/yarn-workspace-isolator to isolate package, which works well

**Comment by RDeluxe** [comment] 2020-05-04 15:32
Hi, just coming to +1 this. 
As I said earlier on Gitter, we have the same flow for now ;

Our typical CI/CD flow is :

1.     Install all deps and cache the folder (ie. caching with gitlab CI/CD) so it speeds up further installs
2.     lint, test, build (using the previously created cache)
3.     build docker images (simple COPY most of the time)
4.     deploy to K8S or other

I think the first step is important to remember, as caching the node_modules folder for your monorepo from one CI/CD stage to another can greatly increase their speed (plus, in a more common sense its good practice to avoid downloading hundrerds of megabytes of data just to lint your repo).


Our problem, like the others, is that for nodejs applications (express servers, SSR apps bundling an express server, etc.) we need the node_modules folder.

For now we have been copying the ENTIRE git folder, but of course that bundles all the dependencies of all our applications in each Docker File, not really optimum.

ie. for our api the Dockerfile looks like this

``` yaml
# Copy everything for now
COPY . .

# Remove useless packages
RUN rm -r packages/backoffice
RUN rm -r packages/studio
RUN rm -r packages/webapp
RUN rm -r packages/ui-kit
RUN rm -r packages/redux-store

WORKDIR /usr/src/app/packages/api
```

Like others have said, this is subpar (error prone and images are getting huge).

We tried using something like yarn-workspace-isolator (just realized I forked it 2 years ago) but that was not conclusive either.

So I strongly support this.

**Comment by yahgwai** [comment] 2020-06-30 13:56
I'm also facing this issue. I have a package that has multiple private packages as dependencies, each of these share large dependencies which I cant afford to duplicate. If I want to create a deployment bundle for my package at the moment I copy all the node_modules from the root, then manually delete and re-arrange until I have the set of dependencies that roughly equates to what I need.

```
pnpm run clean-all
pnpm i --frozen-lockfile
pnpm run build
pnpm run clean-dep
pnpm i --frozen-lockfile --prod
cp -rL ./node_modules/.pnpm/node_modules ./packages/coordinator/node_modules2
cp -rL ./packages/coordinator/node_modules/@any-sender/client/node_modules/ethers ./packages/coordinator/node_modules2/ethers
cp -rL ./packages/coordinator/node_modules/@any-sender/client/node_modules/@any-sender/contracts ./packages/coordinator/node_modules/@any-sender/contracts
rm -rf ./packages/coordinator/node_modules/@any-sender/client/node_modules
rm -rf ./packages/coordinator/node_modules/@any-sender/common/node_modules
rm -rf ./packages/coordinator/node_modules/@any-sender/contracts/node_modules
rm -rf ./packages/coordinator/node_modules/@any-sender/data-entities/node_modules
rm -rf ./packages/coordinator/node_modules/@any-sender/payment-client/node_modules
cp -rL ./packages/coordinator/node_modules/@any-sender ./packages/coordinator/node_modules2/@any-sender
rm -rf ./packages/coordinator/node_modules
mv ./packages/coordinator/node_modules2 ./packages/coordinator/node_modules
rm -rf ./packages/coordinator/node_modules/aws-sdk
```

**Comment by dpolivy** [comment] 2020-07-22 00:27
I want to add my +1 for this, as well. I am using pnpm via @microsoft/rush, which does have a deploy command. In theory, this works great, however it is symlinking all the `node_modules` from all projects into a common pnpm module store, and then symlinking just the direct dependencies into the app folders. The challenge is that my deployment method (Azure Web App "Run from Package (ZIP)") doesn't support symlinks. So, after everything is packaged up, it fails to run because the full set of dependencies cannot be resolved.

Since I'm using rush, my scenario may be slightly different, but ultimately it would be wonderful to have some way to build a flat and de-duped node_modules that doesn't require symlinks so my app can run in production.

**Comment by zkochan** [comment] 2020-07-22 19:45
But pnpm cannot create a node_modules without using symlinks. Symlinks are what allows us to avoid using a flat node_modules.

**Comment by dpolivy** [comment] 2020-07-22 21:35
> But pnpm cannot create a node_modules without using symlinks. Symlinks are what allows us to avoid using a flat node_modules.

Understood, but it seems like many folks here are requesting a symlink-free solution that would work with Docker, ZIP files, etc. Is there any possibility of generating something like that (flat node_modules optimized for production deployment) as a build artifact. I'm new to pnpm, and I appreciate the problems it is trying to solve. For development purposes, the current behavior is great, but when it comes to packaging the app for a production deployment, maybe it's OK to structure things a little differently in the name of broader compatibility and performance? As it is, if symlinks are required, I'm not sure I can continue using pnpm without a viable deployment solution that works with ZIP files.

**Comment by zkochan** [comment] 2020-07-22 22:44
There is no way to avoid symlinks. Unless we will use Yarn's Plug'n'Play to override Node's resolution algorithm. (https://github.com/pnpm/pnpm/pull/1874)

What if a script would create the symlinks after unpacking the zip? Or the symlinks would be created on the startup of the app.

**Comment by dfee** [comment] 2020-07-22 23:13
for design inspiration you could look at Rush's [deploy manager](https://github.com/microsoft/rushstack/blob/c7be8f7f337209e010461b42ddf73fc03e21398b/apps/rush-lib/src/logic/deploy/DeployManager.ts#L130) which is a wrapper providing exactly that functionality.

**Comment by zkochan** [comment] 2020-07-22 23:30
> I want to add my +1 for this, as well. I am using pnpm via @microsoft/rush, which does have a deploy command. In theory, this works great, however it is symlinking all the node_modules from all projects into a common pnpm module store, and then symlinking just the direct dependencies into the app folders.

So the issue is that you zip the app folder which only contains the symlinks to the common store. So there are two issues:

1. symlinks are used
2. the actual modules are not in the app's node_modules, they are in another directory

cc @octogonz

**Comment by octogonz** [comment] 2020-07-23 03:18
I said basically the same thing: Eliminating the symlinks is not a good general solution to this problem. The symlinks serve an important purpose.

The .zip file format actually supports symlinks already.  Thus the best solution would be for Azure Web App "Run from Package" to correctly unzip these symlinks. That seems like a bit of a long shot, however, given their approach of mounting the .zip file as a read-only virtual folder.

So the next thought would be:  Why is "Run from Package" so important?  Could you find a different Azure deployment mechanism that doesn't have this limitation.  I'd expect there to be many options to choose from.

**Comment by Bessonov** [comment] 2020-07-24 20:27
We still use webpack to package the backend. For usage in multi-stage docker build (or in general on ci) it's possible to [replace symlinks with files](https://stackoverflow.com/questions/7167424/replace-all-symlinks-with-original) (not tested). Changed my upvote to downvote, because you can achieve it with other tools and I'm not sure that there is so much value in this request, but it adds complexity and maintaining costs.

**Comment by bdchauvette** [comment] 2020-07-25 03:33
I've been working on our deployment pattern a bit, and I'm also now thinking that because each org probably has some idiosyncratic deployment requirements, this particular feature is probably out of scope for pnpm itself.

The pattern I've come up with is basically:

- mount the repo into a container using Docker's experimental `RUN --mount` syntax
- run `pnpm install --filter $root --filter $deploy_package...`
  - copying the workspace to a temp directory using `git clone` for this helps make sure that you don't include any uncommited files, but it's not strictly necessary
- run `pnpm build --filter $deploy_package...`
- rsync the prod dependency graph to an output directory, excluding `node_modules`
- in another Dockerfile stage, `COPY` the output directory
- run `pnpm install --prod $deploy_package...`
  - it's probably possible to use `pnpm prune` in the previous Dockerfile stage for this, but TBH I haven't really tried it
- set `CMD` to `pnpm start --filter $deploy_package`

I think the only thing I'm unhappy with right now is that it seems difficult to find the workspace-only, production dependency graph of the package being deployed. That is, it might be totally possible, but I can't seem to find a way to get `pnpm recursive list` to output the full graph of only prod workspace packages. I'm working around this with a recursive shell function that calls `pnpm recursive exec -- cat package.json` and piping it into `jq` to find the deps.

If there were a way to do something like `pnpm recursive list --prod --workspace-only $deploy_package`, that would make things a lot simpler.

If pnpm were to provide some sort of deployment support, I think the only thing it might need to do is output the paths to all packages in the deployed package's prod dep graph. Users could then consume the package paths and use whatever tooling they want to prepare their final deployment.

As a nice to have, I think there could be a flag that runs `pnpm pack` on each package in the dep graph, so that if packages used e.g. `files` or `.npmignore` they could shave a few bytes off the final image by copying and extracting the tarballs instead of the full package directories.

**Comment by zkochan** [comment] 2020-08-04 23:58
@bdchauvette so you need something like `pnpm list --filter foo...` but only via non-dev dependencies. I guess we can support something like that. `--prod` might be not a good suit because it is currently used to list prod deps only.

**Comment by zefexdeveloper** [comment] 2020-08-05 13:28
Is there a GitHub repo with an example of using pnpm with a monorepo that can be deployed using circleci or any other ci/cd platform?

**Comment by zkochan** [comment] 2020-08-06 01:06
I created a separate tool that can create a dedicated lockfile for a project inside a workspace. Might be useful for when a single app should be released in isolation.

Install `pnpm add -g @pnpm/make-dedicated-lockfile`

Run `make-dedicated-lockfile` in the project that needs a lockfile.

**Comment by zefexdeveloper** [comment] 2020-08-06 16:36
@zkochan Sorry to bother you but I'm totally new to pnpm and also not a expert regarding deployment so I was wondering, what is the best way to deploy a monorepo? My project right now is using yarn workspaces, one package has next.js, the other one is nodejs with graphql an other things, there's also packages for common things and they are all using typescript as well...
I'm wondering how pnpm can help me with monorepo better than yarn specially regarding deployment. If you can share some experience, repository, article or anything that would help me understand it better I would appreciate. I can be Docker, DO, anything like that. I just need to understand how to deploy a monorepo better (there's a lack of articles about that).

**Comment by octogonz** [comment] 2020-08-06 19:43
@zefexdeveloper `rush deploy` will could this if you are using Rush with PNPM.  It's the same basic idea as `@pnpm/make-dedicated-lockfile`, just integrated into a workflow.

**Comment by zefexdeveloper** [comment] 2020-08-06 22:14
@octogonz I never heard of it, I will be reading that. Thank you very much. I really needed a light for that cause I was lost where to go haha. I hope it helps me and if you allow me to ping you to help if needed I'd appreciate a lot.

**Comment by zkochan** [comment] 2020-09-25 08:29
Regarding issues with symlinks.

I create a tool that can create a `.pnp.js` file for a project that uses pnpm: https://github.com/pnpm/pnpm/tree/master/packages/lockfile-to-pnp

If it works fine, we can add some new flag that will not create symlinks in node_modules and Plug'n'Play will handle all the resolutions instead.

**Comment by zkochan** [comment] 2020-10-04 15:08
Soon, pnpm will support Plug'n'Play out of the box, here's the issue for tracking: #2902

**Comment by zkochan** [comment] 2020-10-17 12:21
So to summarize.

1. In order to deploy a project from a workspace use [@pnpm/make-dedicated-lockfile](https://www.npmjs.com/package/@pnpm/make-dedicated-lockfile)
2. If the environment that you are deploying to doesn't work with symlinks well, or it does not support symlinks, then use then use Plug'n'Play, which is shipped with pnpm v5.9. Create the next `.npmrc` in the root of your project:
    ```
    node-linker=pnp
    symlink=false
    ```

**Closed by zkochan** 2020-10-17 12:21 UTC
Labels: area: monorepo, type: feature

**Comment by StarpTech** [comment] 2021-02-12 08:25
@zkochan We tried to use `@pnpm/make-dedicated-lockfile` but it doesn't understand the workspace. It tries to download workspace packages from the registry.

**Comment by electerious** [comment] 2021-04-01 14:08
Same issue as @StarpTech. `@pnpm/make-dedicated-lockfile` can't resolve workspace protocols. Running `make-dedicated-lockfile` in one of the monorepo packages reports `Error: Cannot resolve workspace protocol of dependency "@monorepo/api" because this dependency is not installed.`.

**Comment by JakeGinnivan** [comment] 2021-04-26 00:43
I may have missed something, but the sub project doesn't have it's own virtual store, so when the project is zipped up the transitive dependencies can't be resolved?

I've resorted to running these commands in the dist folder, is there an easier way?

```
# Lock file generated with @pnpm/make-dedicated-lockfile
cp ../../package.json ../../pnpm-lock.yaml ../../../../pnpm-workspace.yaml .
pnpm i
zip -rqy ../package.zip .
```

I think it likely is fine for those using docker because it is essentially treated as an isolated project for the install, but I can't stop it from discovering the workspace and using that virtual store.

**Comment by rdsedmundo** [comment] 2021-05-07 18:12
Running `make-dedicated-lockfile` for me doesn't recognize the workspaces packages and tries to download them from npm, as others have pointed here too. @zkochan should this be reopen?

```
 ERROR  GET https://registry.npmjs.org/@acme%2Flib-client: Not Found - 404
@acme/lib-client is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
```

**Comment by DesignByOnyx** [comment] 2021-05-11 19:07
I just wanted to point out that the issue with `make-dedicated-lockfile` is indeed failing on `workspace:` protocols and has been reported here: https://github.com/pnpm/pnpm/issues/1919. The big problem is this error happens in the [final](https://github.com/pnpm/pnpm/blob/main/packages/make-dedicated-lockfile/src/index.ts#L63-L69) step of the code, resulting in an adulterated package.json file with all `workspace:` protocols removed.

**Comment by zkochan** [comment] 2021-05-11 20:17
Please create new issues. If you want to have more general discussions, create discussions here: https://github.com/pnpm/pnpm/discussions

**Comment by xpluscal** [comment] 2022-02-15 05:08
@DesignByOnyx did you ever figure this issue out? thank you 🙏

**Comment by canadaduane** [comment] 2022-04-11 21:45
Is there documentation somewhere showing how to achieve monorepo deployment using the ideas from this thread that made their way into a concrete solution?

**Comment by zkochan** [comment] 2022-04-11 21:47
You can try the workaround that I described in this issue: https://github.com/pnpm/pnpm/issues/4378

**Comment by andrewmclagan** [comment] 2022-09-01 23:50
mono repo docker example / doc is lacking

**Comment by maelp** [comment] 2023-12-07 16:52
Hmmm in order to deploy to Cloud Functions, or Google App Engine, I'd like to be able from my **monorepo**:

- to build the project on my CI (working)
- to create a package which contains the built files, but also a pnpm-lock.yaml file **just for that package** so that on the Cloud machine, it can run a `pnpm install` using the correct versions, and install architecture-dependant packages (eg those using binaries)

for now everything is working except I don't see a way to create a "local pnpm-lock.yaml" for a single subpackage, what would be the correct way?

I guess I can play with those tools:

- https://github.com/pnpm/pnpm/blob/main/lockfile/prune-lockfile/src/index.ts
- https://github.com/pnpm/pnpm/blob/main/lockfile/filter-lockfile/src/filterLockfileByImporters.ts
- https://github.com/pnpm/pnpm/tree/main/lockfile/lockfile-file

but perhaps such a common requirement should be integrated in the `pnpm` command?

**Comment by DesignByOnyx** [comment] 2023-12-07 23:49
I recommend turborepo if you want a well-tested, fast, non-invasive, and docker-friendly pruning tool for any package manager (npm, yarn, pnpm). They create two separate folders, one with just package files, and then a separate folder for the full source and dependencies for the pruned project. This helps support the `COPY packages -> npm install -> COPY src` style of dockerfiles.

**Comment by maelp** [comment] 2023-12-07 23:50
I'm already using turborepo, but how would I create a local "pnpm-lock.yaml" just for a sub package?

**Comment by DesignByOnyx** [comment] 2023-12-08 00:24
I don't want to create too much of a conversation here, but I'll point to this line on the [turborepo docs](https://turbo.build/repo/docs/reference/command-line-reference/prune):

> A new pruned lockfile that only contains the pruned subset of the original root lockfile with the dependencies that are actually used by the workspaces in the pruned workspace.

So if you run `turbo prune <your-package> --docker`, then you should have a new top-level directory named `out` which will contain the lockfile you need.

NOTE: if this doesn't fulfill your needs, please open a question on StackOverflow and post it here so that this thread can stay on topic.
