### ISSUE TITLE
Missing peer warning even if package is listed in `peerDependencies`

### ISSUE THREAD

**Issue by baptisteArno** [pnpm/pnpm#5047] opened 2022-07-17 18:50 UTC
### Expected behavior:

In a package where `react` is defined in `peerDependencies`. If it has a react dependent package (`react-transition-group`, for example) as a dependency, it shouldn't warn me that `react` is a missing peer 

### Actual behavior:

I get the `missing peer react@"^15.5.4 || ^16.0.0 || ^17.0.0 || ^18.0.0"` warning

### To reproduce

1. Set `react` in `peerDependencies`
2. `pnpm i react-transition-group`
3. See warning

### Additional information:

 - `node -v` prints: v18.5.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment] 2022-07-20 00:50
It is a duplicate of #5028

**Closed by zkochan** 2022-07-20 00:50 UTC
Labels: type: bug
