### ISSUE TITLE
`pnpm i` should not install deps listed in `optionalDependency`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#766] opened 2017-05-11 10:50 UTC
When we changed `pnpm i` to automatically save deps this issue would have begun.

**Comment by zkochan** [comment] 2017-06-04 18:57
What do you mean? Is it the same as #759?

**Comment by vjpr** [comment] 2017-06-06 17:07
If I run `pnpm i fsevents` it will be added to `dependencies`, because it is essentially running `pnpm i -S fsevents`.

**Comment by zkochan** [comment] 2017-06-06 18:50
I see. This is a duplicate of #727

**Closed by zkochan** 2017-06-06 18:50 UTC
