### ISSUE TITLE
Add pnpm ci command as alias for pnpm i --frozen-lockfile

### ISSUE THREAD

**Issue by SWATOPLUS** [pnpm/pnpm#6335] opened 2023-03-31 11:57 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
As a user of pnpm I'd like to run package restore from lock-flie using `pnpm ci` command.
If lock-file corresponds to `package.json`, then restore packages.
If lock-file should be updated, then stop execution with unsuccessful exit code.
This will make pnpm more compatible with npm

**Describe the solution you'd like**
Implement `pnpm ci` as alias for `pnpm i --frozen-lockfile`

**Describe the drawbacks of your solution**
I don't see any drawbacks

**Describe alternatives you've considered**
I don't see any alternative solutions

**Comment by zkochan** [comment] 2023-03-31 13:34
Duplicate of https://github.com/pnpm/pnpm/issues/6100

**Closed by zkochan** 2023-03-31 13:34 UTC
Labels: type: feature
