### ISSUE TITLE
TARBALL_EXTRACT error while installing a dependency from GitHub having a slash in branch name

### ISSUE THREAD

**Issue by michaldudak** [pnpm/pnpm#7697] opened 2024-02-23 08:43 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

1. Create a package (can be empty) with the following manifest:
   ```json
   {
     "name": "pnpm-repro",
     "version": "1.0.0",
     "dependencies": {
       "@mui/monorepo": "https://github.com/michaldudak/material-ui.git#npm-publishing/markdown"
     }
   }
   ```
2. `pnpm i`

### Describe the Bug

The following errors are printed to the console:
```
 WARN  GET https://github.com/michaldudak/material-ui.git#npm-publishing/markdown error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://github.com/michaldudak/material-ui.git#npm-publishing/markdown error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://github.com/michaldudak/material-ui.git#npm-publishing/markdown": Error: Invalid checksum for TAR header at offset 0. Expected NaN, got 42982
```

### Expected Behavior

The package is installed without errors.

Note that installing `https://github.com/michaldudak/material-ui.git#markdown-package`, which points to the exact same commit succeeds. This leads me to believe there's an issue with resolving branches having a slash in their name. I confirmed this with another branch with a slash.

### Which Node.js version are you using?

20.9.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by michaldudak** [comment] 2024-02-23 08:53
I just found out that URL-encoding the branch name (`https://github.com/michaldudak/material-ui.git#npm-publishing%2Fmarkdown`) fixes the issue. I suppose a mention in the docs about it could be worth it.
Also having unencoded slash works in Yarn classic, so it may come as a surprise during a migration.

**Comment by zkochan** [comment] 2024-02-23 12:33
If it works with Yarn, then we should probably make it work too.

**Comment by zkochan** [comment] 2024-10-28 03:24
:ship: 9.12.3

**Comment by VladimirNT** [comment] 2024-10-28 13:57
> 🚢 9.12.3

Hello, I have marked this issue in the commit message as one that could be potentially fixed by the change, but after rechecking I can say it is most likely not related - #6991 should be marked there instead. 
Sorry for the confusion.

**Closed** 2024-11-18 02:02 UTC
Labels: type: bug

**Comment by SummonNight** [comment] 2024-12-04 03:56
I also encountered the same problem. Through my personal attempts, I found that it was caused by two aspects.

1. The version of PNPM used. The old version was specified as `"you-package" : "git+https://github.com/xxxx#tag"`.
2. The hash symbol (`#`) would cause problems in some PNPM versions.

Finally, I downgraded the version to pnpm@6.11.0 and node@16.14.0 and used the `git+https` method. In this way, it could support the hash symbol (`#`), and I was able to add and install dependencies normally and runs success.

Because, In Vite, when using relatively new versions of PNPM and in the Node environment, if I use `"you-package" : "https://github.com/xxxx#tag"` to install Element-Plus, the installation can succeed, but an error will be prompted when it runs finally:
```
[vite] Pre-transform error: Failed to load url /node_modules/.pnpm/element-plus@https+++xxx.com+yourProjectName+fork-element-plus-dist.git#5d07aa58426425e6dfd_gc5ouxduyhrdumn7s
llwvqepma/node_modules/element-plus/dist/index.css
```

**Comment by SummonNight** [comment] 2024-12-04 04:06
中文版本：

我也遇到了同样的问题，我个人尝试下来的发现是2个方面导致的：
1. 使用的PNPM版本，旧版本的是“you-package” : "git+https://github.com/xxxx#tag"
2. #号在比较新的PNPM版本中会导致element-plus的scss文件引用出现问题

我最后是将版本降低到6.x版本， node也降低到16.x版本，使用`git+https`的方式，就能支持#号，并添加和正常安装依赖了，也成功替换了原来官方的依赖包。
在此期间我曾经尝试在新版本的pnpm和node环境下使用`pnpm i element-plus https://gitee.com/xxx.git#tag`的方式， 虽然安装成功了，但是运行程序后又会有其它问题（element-plus的scss文件引用出现问题）：
` [vite] Pre-transform error: Failed to load url /node_modules/.pnpm/element-plus@https+++gitee.com+xxxx.git#5d07aa58426425e6dfd_gc5ouxduyhrdumn7s
llwvqepma/node_modules/element-plus/dist/index.css (resolved id: D:/workGit/xxxxx/node_modules/.pnpm/element-plus@https+++gitee.com+summonnight+fork-element-plus-dist.
git#5d07aa58426425e6dfd_gc5ouxduyhrdumn7sllwvqepma/node_modules/element-plus/dist/index.css). Does the file exist?`
