### ISSUE TITLE
--loglevel

### ISSUE THREAD

**Issue by jjangga0214** [pnpm/pnpm#2140] opened 2019-11-09 14:55 UTC
### pnpm version:
4.1.7

### Code to reproduce the issue:

```bash
pnpm install --loglevel error <package>
```

### Expected behavior:

Should install package.

### Actual behavior:

```
 ERROR  Unknown option 'loglevel'
```

### Additional information:

 - `node -v` prints: v12.6.0
 - Windows, OS X, or Linux?: Linux

**Comment by sz-cgt** [comment] 2019-11-19 21:44
While close this?  This bug still exists in 4.3.0

> [cgt-ilab@ldevawsweb0004 ilab]$ pnpm --version
4.3.0
[cgt-ilab@ldevawsweb0004 ilab]$ pnpm -d
 ERROR  Unknown option 'loglevel'
For help, run: pnpm help help

**Comment by zkochan** [comment] 2019-11-19 23:47
It is not a bug but rather a feature request

**Comment by frederikdekegel** [comment] 2020-04-01 13:34
Is there any chance this could be resolved soon?

As a Dev-Ops engineer, I want to introduce pnpm but the developers as spooked by the number of warnings that are generated with pnpm install associated of a nrwl angular project.

**Comment by zkochan** [comment] 2020-04-01 13:42
Yes, we can resolve it pretty easily. Just need to update [@pnpm/default-reporter](https://github.com/pnpm/pnpm/tree/master/packages/default-reporter)

**Closed** 2020-04-06 11:34 UTC
Labels: area: reporting, type: feature

**Comment by zkochan** [comment] 2020-04-06 18:18
:ship: 4.13.0-0
