### ISSUE TITLE
PNPM: incomplete downloads: no error messages

### ISSUE THREAD

**Issue by frederikdekegel** [pnpm/pnpm#3479] opened 2021-05-27 08:54 UTC
### pnpm version:
6.4.0 & 6.5.0

### Code to reproduce the issue:
pnpm install
.npmrc => loglevel=error

### Expected behavior:
If one or more downloads cannot complete, an error (message) is expected.

### Actual behavior:
If one or more downloads cannot complete, the command pnpm install just terminates.

### Additional information:
![image](https://user-images.githubusercontent.com/8667499/119796316-914f3500-bed9-11eb-9da5-f92ad7e07d2d.png)

The last download regarding font-awesome-pro did not complete but after some time the command pnpm install is just terminated without any error message. 

 - `node -v` prints: 14.17.0
 - Windows, macOS, or Linux?: Windows 10

**Comment by D4N14L** [comment] 2021-06-08 17:41
Also seeing this. Trying to get a debug log out of PNPM but it's pretty non-deterministic when this happens.

**Comment by zkochan** [comment] 2021-06-08 18:08
This was probably fixed by https://github.com/pnpm/pnpm/commit/bf1fe2d1de9dc1e1897d97c22c7bdc325740712a

The issues is described here https://github.com/pnpm/pnpm/commit/bf1fe2d1de9dc1e1897d97c22c7bdc325740712a

**Comment by D4N14L** [comment] 2021-06-09 19:52
This does appear to be the case. Just merged the new version into our local repo, will report back if the issue is still present. However, looking at the logs, this _should_ fix it. Thanks @zkochan

**Closed** 2021-06-09 19:59 UTC
Labels: type: bug
