### ISSUE TITLE
Fails to install using standalone script on windows

### ISSUE THREAD

**Issue by Jels02** [pnpm/pnpm#7423] opened 2023-12-15 00:26 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Reproduction steps

Use the installation command on windows as per https://pnpm.io/installation#on-windows in powershell.
Then try downloading the script and running directly. 

### Describe the Bug

The powershell script attempts to install the "8.13.0" version, instead of "8.12.1", due to the script fetching information for "@pnpm/exe" from npm - the current latest version for @pnpm/exe is 8.13.0, but there is no corresponding release on git.

### Expected Behavior

It should install correctly, to the latest version available on git.

### Which Node.js version are you using?

N/A

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by RoryO** [comment] 2023-12-15 05:26
This isn't just Windows, anything that uses @pnpm/exe to install pnpm fails. CI scripts, deploy scripts, and the like fail because 8.13 release is not on github. @zkochan please release 8.13 to github?

**Comment by igorakkerman** [comment] 2023-12-15 06:50
The root cause seems to be that upon a rollback of a release from GitHub, the version list is not updated in npm, that is, in  https://registry.npmjs.org/@pnpm/exe . IMO, the process of a release rollback should be fixed, not a single release.

**Comment by hyunbinseo** [comment] 2023-12-15 08:59
Applies to macOS as well. Leaving the 404 error message for search.

```shell
% curl -fsSL https://get.pnpm.io/install.sh | sh -
# curl: (22) The requested URL returned error: 404
# pnpm version '8.13.0' could not be found
```

**Comment by rottabonus** [comment] 2023-12-15 10:45
Also same result when installing with [latest node image](https://hub.docker.com/_/node/)

```bash
 $ wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
 curl: (22) The requested URL returned error: 404
 pnpm version '8.13.0' could not be found
 ````

**Comment by shufo** [comment] 2023-12-15 12:25
Same

```bash
 $  curl -fsSL https://get.pnpm.io/install.sh | sh -
curl: (22) The requested URL returned error: 404
pnpm version '8.13.0' could not be found

```

**Comment by shufo** [comment] 2023-12-15 12:30
@hyunbinseo @rottabonus 
To work around, you can specify latest release version.

```bash
 $  curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=8.12.1 sh -
==> Downloading pnpm binaries 8.12.1
```

**Comment by JesusPaz** [comment] 2023-12-15 15:47
@ntheanh201 solution does not work for me, I just use `npm install -g pnpm`

**Comment by ntheanh201** [comment] 2023-12-15 15:57
> @ntheanh201 solution does not work for me, I just use `npm install -g pnpm`

Can you show me the error message? I tested it with Linux

**Comment by JesusPaz** [comment] 2023-12-15 16:20
@ntheanh201 docker image: node:18-alpine
![image](https://github.com/pnpm/pnpm/assets/27715376/961f61df-7e60-4e5c-80e5-f0a85aab96a7)

**Comment by ntheanh201** [comment] 2023-12-15 16:26
> @ntheanh201 docker image: node:18-alpine ![image](https://private-user-images.githubusercontent.com/27715376/290877855-961f61df-7e60-4e5c-80e5-f0a85aab96a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc3MTQsIm5iZiI6MTcwMjY1NzQxNCwicGF0aCI6Ii8yNzcxNTM3Ni8yOTA4Nzc4NTUtOTYxZjYxZGYtN2U2MC00ZTVjLTgwZTUtZjBhODVhYWI5NmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMzE1NWE0ODczYzMzZjViNDcyMTkyNGU3YjY0YTU3YzZiZmNiNTUxNGVkOGEzZTQxNzMxMjVhNzE5YjgzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VYX1hbi3rhxjK3Lpz9olVpdHiNf0E3PO9yyRAmv5MoM)

Hmm, for me it looks like this
<img width="1248" alt="image" src="https://github.com/pnpm/pnpm/assets/29043139/711a0304-5145-41d0-812e-80f36092ab07">

**Comment by ntheanh201** [comment] 2023-12-15 16:27
> > @ntheanh201 docker image: node:18-alpine ![image](https://private-user-images.githubusercontent.com/27715376/290877855-961f61df-7e60-4e5c-80e5-f0a85aab96a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc3MTQsIm5iZiI6MTcwMjY1NzQxNCwicGF0aCI6Ii8yNzcxNTM3Ni8yOTA4Nzc4NTUtOTYxZjYxZGYtN2U2MC00ZTVjLTgwZTUtZjBhODVhYWI5NmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMzE1NWE0ODczYzMzZjViNDcyMTkyNGU3YjY0YTU3YzZiZmNiNTUxNGVkOGEzZTQxNzMxMjVhNzE5YjgzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VYX1hbi3rhxjK3Lpz9olVpdHiNf0E3PO9yyRAmv5MoM)
> 
> Hmm, for me it looks like this (with bash)<img alt="image" width="1248" src="https://private-user-images.githubusercontent.com/29043139/290879395-711a0304-5145-41d0-812e-80f36092ab07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc4ODUsIm5iZiI6MTcwMjY1NzU4NSwicGF0aCI6Ii8yOTA0MzEzOS8yOTA4NzkzOTUtNzExYTAzMDQtNTE0NS00MWQwLTgxMmUtODBmMzYwOTJhYjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjdkOTQ5ZjY4M2Y3ODQ2NmQxMjY5YjEwZTY1MGRhMGVmYWRhNmM1MTA0M2JmZmU2MjRiZGFhOGI1ZTgyMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hqJqO5pLFobjB7Ldb1h2UtsdUphLkuAdeAPMVW-ABY0">

with sh
<img width="1219" alt="image" src="https://github.com/pnpm/pnpm/assets/29043139/81cd33e4-ec9b-4526-8fb3-2120e8f95d90">

**Comment by zkochan** [comment] 2024-01-06 14:12
This happened because I have accidentally published pnpm from locally. I wanted to publish just the libraries but also published a new version for `@pnpm/exe` (as latest). I have updated the scripts so even if I someone will accidentally release a new version, it won't be latest. This should not happen again.

**Closed by zkochan** 2024-01-06 14:12 UTC
Labels: type: bug
