### ISSUE TITLE
pnpm install doesn't respect os and arch requirements in package.json

### ISSUE THREAD

**Issue by aquark** [pnpm/pnpm#2038] opened 2019-09-27 19:18 UTC
### Code to reproduce the issue:

On macOS: `pnpm install @ffmpeg-installer/ffmpeg`

### Expected behavior:

It installs only `@ffmpeg-installer/darwin-x64`

### Actual behavior:

It installs all the platform-specific packages, e.g. `@ffmpeg-installer/linux-arm64`, even though their `package.json` specifies a different `os` and `cpu`.

### Additional information:

 - `node -v` prints: `v10.16.0`
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment] 2019-10-22 22:19
It is very disappointing. Seems like the engine requirements are not included in the compressed metadata response returned by the registry.

This might be a change on the registry side, I think. It is a one-line change in pnpm codebase

https://github.com/pnpm/pnpm/blob/5b97c5f368a0c84f44b691409da35d447fb30416/packages/pnpm/src/createResolver.ts#L25

but it will make installations somewhat slower. We should probably ask npm why the registry is not returning these fields.

**Comment by nikoladev** [comment] 2019-10-28 10:24
> but it will make installations somewhat slower

Is it possible to check in the `package.json` if any of the requested fields are not part of the compressed metadata response (like for `os` and `cpu`)? Then we only need to set `fullMetadata` to `true` when needed.

**Comment by zkochan** [comment] 2019-10-28 22:32
I am not sure I understand. All the information we have about a package is its metadata. And we can only request the full or the nonfull version of the metadata

**Comment by nikoladev** [comment] 2019-10-29 12:06
My bad, nevermind. My assumption was based on a vague and incorrect understanding of how the packages are requested. I wrongly assumed that the `package.json` would be downloaded before the metadata.

**Comment by matthiasg** [comment] 2020-02-11 11:26
This is an issue with @microsoft/rush when trying to compile a webpack project which includes chokidar which in turn requires fsevents. fsevents fails to compile on windows and thus fails pnpm.

Using the readPackage hook and removing scripts does not help sadly. 

What else can I do to prevent the package from building ?

**Comment by zkochan** [comment] 2020-02-11 12:02
have you tried setting optional=false? I don't know how to do this with rush but you can set the optional=false pnpm setting

**Comment by matthiasg** [comment] 2020-02-12 07:43
I removed the root dependency after finding it and the problem is resolved for me for now. I am still confused as to why altering the packageJson did not have any effect.

**Comment by dpolivy** [comment] 2020-07-21 00:51
I think I'm hitting this same issue with `fsevents` on a Windows build (also with @microsoft/rush as the toolchain). It seems pnpm is creating a `.pnpm\node_modules\fsevents` link which points to `.pnpm\fsevents@2.1.3\node_modules\fsevents`, but the latter one doesn't exist because `fsevents` can't be installed on Windows. In this case, the source symlink shouldn't be created at all.

I'm wondering if I can use `pnpmfile.js` to work around this easily? The challenge is that the dependency seems to come from `mocha` -> `chokidar` -> `fsevents`, so it seems `pnpmfile.js` isn't called with any of these packages, just the main one which includes `mocha` as a devDependency. Is there another possible workaround here?

**Comment by bytroli** [comment] 2020-08-13 12:43
> It is very disappointing. Seems like the engine requirements are not included in the compressed metadata response returned by the registry.

I just checked and (at least for fsevents) the `fullMetadata=false` response contains os and engine requirements:
```
{
  "name": "fsevents",
  "versions": {
    "latest": {
      "name": "fsevents",
      "version": "2.1.3",
      "devDependencies": {
        "node-gyp": "^6.1.0"
      },
      "dist": {
        "integrity": "sha512-Auw9a4AxqWpa9GUfj370BMPzzyncfBABW8Mab7BGWBYDj4Isgq+cDKtx0i6u9jcX9pQDnswsaaOTgTmA5pEjuQ==",
        "shasum": "fb738703ae8d2f9fe900c33836ddebee8b97f23e",
        "tarball": "https://registry.npmjs.org/fsevents/-/fsevents-2.1.3.tgz",
        "fileCount": 6,
        "unpackedSize": 44861,
        "npm-signature": [Object],
      },
      "engines": {
        "node": "^8.16.0 || ^10.6.0 || >=11.0.0"
      },
      "os": [
        "darwin"
      ],
      "hasInstallScript": true
    }
  }
}
```
We have fsevents in the pnpm-lock.yaml marked as optional dependency but pnpm still tries to install the package on non-macOS platforms causing an (ignorable) error. Is this the intended behaviour when the lock file was created on a macOS platform and if yes can we somehow mitigate this without losing the optional dependency on platforms where applicable?

**Comment by milahu** [comment] 2020-09-26 13:48
> have you tried setting optional=false? I don't know how to do this with rush but you can set the optional=false pnpm setting

same problem with 
`pnpm install --no-optional @ampproject/rollup-plugin-closure-compiler`

pnpm version is 5.5.11

dependency graph

* rollup-plugin-closure-compiler
   * google-closure-compiler
      * google-closure-compiler-java
      * google-closure-compiler-linux (optional)
      * google-closure-compiler-osx (optional)
      * google-closure-compiler-windows (optional)

all optionals get downloaded, each around 12 MB

**Comment by zkochan** [comment] 2021-08-14 19:58
This is an annoying issue especially because I wanted to ship pnpm v7 using optional dependencies as well (see [@pnpm/beta package.json](https://github.com/pnpm/pnpm/blob/ea0c766067374c822b3106e91b69e4d4b22bba23/packages/beta/package.json))

The issue is that pnpm uses some information from the package archive when creating the lockfile:

https://github.com/pnpm/pnpm/blob/ea0c766067374c822b3106e91b69e4d4b22bba23/packages/resolve-dependencies/src/index.ts#L207-L215

Maybe we could assume that any package that has os/cpu fields needs a build? Or maybe we can sacrifice that `requiresBuild` field. This needs some investigation.

If we figure out how to create a lockfile with no information from the package archive, we can move the dependency compatibility check from here:

https://github.com/pnpm/pnpm/blob/ea0c766067374c822b3106e91b69e4d4b22bba23/packages/resolve-dependencies/src/resolveDependencies.ts#L755-L764

to `@pnpm/package-requester`, if the compatibility check fails, we just skip fetch here:

https://github.com/pnpm/pnpm/blob/ea0c766067374c822b3106e91b69e4d4b22bba23/packages/package-requester/src/packageRequester.ts#L191-L193

**Closed** 2021-08-16 23:33 UTC
Labels: type: bug

**Comment by zkochan** [comment] 2021-08-17 00:37
try 6.14.0-0
