### ISSUE TITLE
pnpm install fails with  ERR_PNPM_PREPARE_PKG_FAILURE

### ISSUE THREAD

**Issue by AbhinavMV** [pnpm/pnpm#5845] opened 2022-12-27 09:09 UTC
### Code to reproduce the issue: 
https://github.com/web3ui/web3uikit this is the mono repo on which I am facing the issue

### Expected behavior: 
`pnpm install` should install all dependencies without any error

### Actual behavior: 
`pnpm install` command fails with errors in GitHub action

![image](https://user-images.githubusercontent.com/35369843/209641976-d2cc635f-3c14-4783-98ba-6ee63583c37f.png)

### Additional information: 
I have solved the issue with hardcoding the pnpm version to 7.11.0

Github actions run for node version 14 and 16 for windows,macOS and linux
 - `node -v` prints: tried with 14 and 16
 - Windows, macOS, or Linux?: all

**Comment by inglkruiz** [comment] 2022-12-27 16:54
Using v7.19.0 still works for me

**Comment by AbhinavMV** [comment] 2022-12-27 17:08
yes, I saw this problem with v7.20.0 and reverted back to the last version I was sure it would work which is 7.11.0. Did not spend time testing other versions 🙂

Thanks for checking and letting me know @inglkruiz 🙌🏻

**Comment by zkochan** [comment] 2022-12-28 00:54
pnpm v7.20 runs the `prepublish` script to build any githosted dependencies (as requested in #5826). 

In your case, there is a githosted dependency, the ethereumjs-abi from https://github.com/ethereumjs/ethereumjs-abi
And the prepublish script of the package fails with this error:

![image](https://user-images.githubusercontent.com/1927579/209741154-6c237f73-0d78-4365-affd-3c8a0b449031.png)

**Comment by AbhinavMV** [comment] 2022-12-28 04:48
@zkochan  Thanks for letting me know. 
Is there a workaround to avoid this? or a way to fix this error in the repo? Since in my case everything was running perfectly before the new update.

**Comment by RoyRao2333** [comment] 2022-12-29 02:51
Getting this error too.

<img width="900" alt="image" src="https://user-images.githubusercontent.com/31413093/209896658-ef17b2e3-c6a8-4ae1-9fb3-4f11abc11951.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/31413093/209897171-f29dae1b-a045-4497-bff3-bb51c3eb3aa4.png">

Not sure where did `yarn` come from?

**Comment by zkochan** [comment] 2022-12-29 02:52
You have a git-hosted dependency that has a prepublishOnly script and uses yarn as a package manager.

Installing Yarn globally might fix the issue.

**Comment by RoyRao2333** [comment] 2022-12-29 05:34
> You have a git-hosted dependency that has a prepublishOnly script and uses yarn as a package manager.
> 
> Installing Yarn globally might fix the issue.

Thanks for the reply. :)

Yes, I already have Yarn installed globally, and still got this error...

<img width="135" alt="image" src="https://user-images.githubusercontent.com/31413093/209907602-1544a219-b05f-4882-8649-25e204a64bc2.png">

Anyway, hope this issue can be fixed somehow... 😊

**Comment by toniengelhardt** [comment] 2022-12-29 22:46
Also managed to resolve it by downgrading pnpm to 7.19.0, but a fix would be amazing. Also using `@wagmi/core` btw.

**Comment by dzek69** [comment] 2023-01-01 20:00
I got here from [this url](https://pullanswer.com/questions/installing-wagmi-with-pnpm-give-error-err_pnpm_prepare_pkg_failure) and there they claim that 7.21 fixes the issue for them, but for me post installs are still broken, so don't close this one yet I guess.

7.19 works.

**Closed** 2023-01-01 21:28 UTC
Labels: type: bug

**Comment by carlos-mta** [comment] 2023-06-08 12:14
This is still an issue for us, I'm using a git-hosted dependency with a `prePublishOnly` script and the output is the follwing:

```
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 18, reused 0, downloaded 0, added 0
Progress: resolved 22, reused 0, downloaded 0, added 0
Progress: resolved 26, reused 0, downloaded 7, added 0
Progress: resolved 31, reused 0, downloaded 16, added 0
Progress: resolved 31, reused 0, downloaded 19, added 0
Progress: resolved 31, reused 0, downloaded 23, added 0
Progress: resolved 31, reused 0, downloaded 25, added 0
Progress: resolved 31, reused 0, downloaded 29, added 0
Progress: resolved 31, reused 0, downloaded 30, added 0
Progress: resolved 31, reused 0, downloaded 31, added 0
 ERR_PNPM_PREPARE_PKG_FAILURE  Command failed with exit code 1: npm install
```
I downgraded to 7.19.0 but still failing.

**Comment by Dzhuneyt** [comment] 2023-06-08 12:16
@carlos-mta closed issues receive less exposure and are unlikely to be spotted by maintainers. I suggest you open a new issue with minimal reproducable example and link it to this one as further reference.

**Comment by jiangxiaoqiang** [comment] 2024-08-17 06:56
I switch to npm and it works.

**Comment by tmm1** [comment] 2024-11-11 00:18
prepublishOnly should no longer run during prepare as of https://github.com/pnpm/pnpm/commit/17d2ddb056052a0115e7392dfab0c075b523ab6e
