### ISSUE TITLE
Installing VSCode fails

### ISSUE THREAD

**Issue by corbinu** [pnpm/pnpm#833] opened 2017-06-30 20:02 UTC
### Code to reproduce the issue:

https://gist.github.com/corbinu/dff50cf047980b04832fe44de5c73807

### Expected behavior:
installs

### Actual behavior:
errors on install vscode-ripgrep

```
  registry.npmjs.org/vscode-ripgrep/0.0.12! module.js:487
  registry.npmjs.org/vscode-ripgrep/0.0.12!     throw err;
  registry.npmjs.org/vscode-ripgrep/0.0.12!     ^
  registry.npmjs.org/vscode-ripgrep/0.0.12! Error: Cannot find module 'github-releases'
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Function.Module._resolveFilename (module.js:485:15)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Function.Module._load (module.js:437:25)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Module.require (module.js:513:17)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at require (internal/module.js:11:18)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Object.<anonymous> (/Users/corbinu/Developer/vscode/node_modules/.registry.npmjs.org/vscode-ripgrep/0.0.12/node_modules/vscode-ripgrep/dist/download.js:7:16)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Module._compile (module.js:569:30)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Object.Module._extensions..js (module.js:580:10)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Module.load (module.js:503:32)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at tryModuleLoad (module.js:466:12)
  registry.npmjs.org/vscode-ripgrep/0.0.12!     at Function.Module._load (module.js:458:3)
```

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: macOS 10.12

**Comment by zkochan** [comment] 2017-06-30 20:25
The issue is in the [vscode-rigrep](https://github.com/roblourens/vscode-ripgrep) package. Its [postinstall script](https://github.com/roblourens/vscode-ripgrep/blob/master/dist/download.js) uses devDepdendencies. Obviously the dev deps are not installed.

It fails with npm as well, when installing only vscode-ripgrep https://gist.github.com/zkochan/9adfc3529a480d16fe39f66763ef820c

**Comment by corbinu** [comment] 2017-06-30 20:37
Interesting

**Comment by zkochan** [comment] 2017-07-10 09:28
@corbinu. I created an issue at [vscode-ripgrep](https://github.com/roblourens/vscode-ripgrep/issues/3). The author agreed that it has to be fixed in vscode-ripgrep

**Closed** 2017-07-10 12:40 UTC
Labels: wontfix (flat node_modules)
