### ISSUE TITLE
pnpm is not invoking readPackage for every dependency

### ISSUE THREAD

**Issue by kaiyoma** [pnpm/pnpm#4794] opened 2022-05-24 21:43 UTC
### Code to reproduce the issue:

For testing purposes, here is my `.pnpmfile.cjs`:

```
module.exports = {
  hooks: {
    readPackage,
  },
};

function readPackage(packageJson, context) {
  if (packageJson.name.includes('clean-css')) {
    context.log('FOUND IT');
    context.log('FOUND IT');
    context.log(JSON.stringify(packageJson, null, 2));
    context.log('FOUND IT');
    context.log('FOUND IT');
  }
}
```

When I run `rm pnpm-lock.yaml && pnpm install`, I never see this code executed, even though it should be, because I have multiple dependencies in the resulting lockfile with `"clean-css"` in the name:

```
 grep clean-css pnpm-lock.yaml
  /@types/clean-css/4.2.5:
      '@types/clean-css': 4.2.5
  /clean-css/4.2.4:
      clean-css: 4.2.4
```

I'm seeing this same problem with other dependencies too, like `@jest/console` and `parse5`, which is causing my dependencies to have mismatched versions in the lockfile.

### Expected behavior:

`readPackage` should be invoked for every dependency in the tree.

### Actual behavior:

Some dependencies are being skipped.

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Windows 10

**Comment by corbanvilla** [comment] 2022-07-27 17:21
Also running into this, did you have any luck resolving @kaiyoma ?

**Comment by kaiyoma** [comment] 2022-07-27 18:55
@corbanvilla No, I ended up abandoning the task that required this, but AFAIK it's still a bug.

**Comment by zkochan** [comment] 2022-08-14 09:23
Is the hook executed at all? Be aware that the `.pnpmfile.cjs` is only used when it is in the root of the workspace. So in the same directory where `pnpm-workspace.yaml`. If it is not in a workspace, then it will be executed in the root of the package.

**Comment by chengcyber** [comment] 2022-11-30 09:18
I run into the same case. I created a reproduce repo at https://github.com/chengcyber/pnpm-indirect-deps-pnpmfile

With specifying a `console.log` in `readPackage` in pnpmfile:

```
function readPackage(packageJson, context) {
  console.log(`>>> Processing "${packageJson.name}" from ${__filename}`);
  return packageJson;
}
```

At the first time of running `pnpm install`. `readPackage` is called for all dependencies:
![image](https://user-images.githubusercontent.com/16147702/204755294-18fe57c4-194d-4e27-b123-27544705729a.png)

At the second time of running `pnpm install` by `rm -rf pnpm-lock.yaml && pnpm install`, `readPackage` is called for some dependencies not all dependencies:
![image](https://user-images.githubusercontent.com/16147702/204755531-86159c62-559a-46dc-8ae3-0c0b934e0ea6.png)

**Comment by Timeless0911** [comment] 2022-12-13 04:00
As shown in the above example, I can traverse all packages in the process of local reproduction only if `pnpm-lock.yaml `and `node_modules` are deleted. Since deleting the lock file is a very unsafe thing. May I ask if there is a similar parameter to enforce all hooks during the execution of `pnpm install`？

**Comment by icy0307** [comment] 2023-06-30 04:59
I have the same problem. Not all packages get traversed but only the workspace packages.
This happens when` Lockfile is up to date, resolution step is skipped ` log shows up.
Only modify `package.json`, delete the lock file , and `[--resolution-only](https://pnpm.io/cli/install#--resolution-only)` that makes the lock file no longer "up to date"  can invoke every package.

However, this behavior compromises the original goal of `readPackage` hook: Being able to modify package's dependencies.
One of my team membesr introduces a sub-dependency with a fixed version number, and his branch doesn't have `.pnpmfile.cjs` file. He installed it first , so the lock has been fixed to his version. Then he rebase master with `.pnpmfile.cjs` that contains hook to fix sub-dependency with fixed version number. 
Nothing would happen, cause `pnpm` thinks Lockfile is update to date whereas it is not.
I know if lockfile is valid, there is no need to go through it every time.  

But As long as 'hook' file changes, lock file might not be updated anymore. it is just like  another `package.json`
Is there any mechanism that make the resolution step not skipped when  `.pnpmfile.cjs` changes?  Maybe, preserve some  `.pnpmfile.cjs` version or hash in lock file. 
When it doesn't match,  go through the resolution again.

As regard CI, packages should be installed with '--frozen-lockfile', and throw an error like [`ERR_PNPM_OUTDATED_LOCKFILE`](https://pnpm.io/errors#err_pnpm_outdated_lockfile)
( I tried to simulate this behavior with `pnpm i --frozen-lockfile --resolution-only`, lock file gets changed instead of throwing error)
@zkochan

**Comment by tjx666** [comment] 2023-08-22 07:33
I find that the readPakage hook only called on workspace package, will skip all none-worksapce packages. @zkochan

**Comment by zkochan** [comment] 2024-02-23 18:23
This is probably resolved by https://github.com/pnpm/pnpm/pull/7662

**Comment by chengcyber** [comment] 2024-06-08 04:53
Retested this issue with this reproduce repo: https://github.com/chengcyber/pnpm-indirect-deps-pnpmfile

pnpm@8.15.8 doesn't work
pnpm@9.2.0 works! 👍

By "work", it means:

The first time of running "pnpm install": `readPackage` went through all packages
And then making some changes in `.pnpmfile.cjs`, running `pnpm install` again, `readPackage` goes through all packages now.


<img width="634" alt="image" src="https://github.com/pnpm/pnpm/assets/16147702/64e08cdb-9bb8-478c-a555-52d0b0f04d52">

> The screenshot of running "pnpm install" after changing pnpmfile

**Comment by zkochan** [comment] 2024-06-08 22:02
Right, we have added a checksum of the pnpmfile content to the lockfile. So, if the content changes, the whole lockfile is reanalized.

**Closed by zkochan** 2024-06-08 22:02 UTC
Labels: type: bug
