### ISSUE TITLE
ENOENT: no such file or directory, copyfile

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#4997] opened 2022-07-08 19:50 UTC
Also having this issue after upgrading to v7. I have no idea how to reproduce it though... it works again by nuking the whole store and re-downloading everything.

```
 ENOENT  ENOENT: no such file or directory, copyfile '/Users/work/.pnpm-store/v3/files/68/fd2865a3cee2a68927ffed7c54667b1b3b03710b6a174ad45caa8e05f2e033b51e6d6f55ab22d8207f2fdb286c9dd057cb43171aa793ce9f180da8d7653e6e' -> '/Users/work/redacted/redacted/node_modules/.pnpm/fsevents@1.2.13/node_modules/_tmp_10595_695eb2b63757fc332de5b4c217d64f1d/build/.target.mk'
```

This is in MacOS by the way.

_Originally posted by @rdsedmundo in https://github.com/pnpm/pnpm/issues/3229#issuecomment-1149057063_

**Comment by rohanrajpal** [comment] 2022-07-09 14:50
Facing the same issue on MacOs, pruning & deleting node modules folder does not help either.

```
spur on  main [$⇡] is 📦 v1.0.0 via  v16.16.0 
❯ rm -rf node_modules/                                                                                                                                                                                                                                                                                          (base) 

spur on  main [$⇡] is 📦 v1.0.0 via  v16.16.0 took 4s 
❯ pnpm store prune                                                                                                                                                                                                                                                                                              (base) 
Removed all cached metadata files
Removed 446 files
Removed 25 packages

spur on  main [$⇡] is 📦 v1.0.0 via  v16.16.0 took 2s 
❯ pnpm i                                                                                                                                                                                                                                                                                                        (base) 
Scope: all 3 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +1363
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/rohanrajpal/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
 ENOENT  ENOENT: no such file or directory, copyfile '/Users/rohanrajpal/Library/pnpm/store/v3/files/5c/b4c2628002ae85883a99d1fa0f071eca141d4a8e18b78495114435ce759bc36665de4e25222e3691578b9627c08cb1bf7a41e9b4e36f145f98db92d27626ee-exec' -> '/Users/rohanrajpal/Documents/spurchat/code/spur/node_modules/.pnpm/sqlite3@5.0.8/node_modules/_tmp_57449_99adffdd7afc757e0d5808e1e80d95ff/node_modules/.bin/node-gyp'

pnpm: ENOENT: no such file or directory, copyfile '/Users/rohanrajpal/Library/pnpm/store/v3/files/5c/b4c2628002ae85883a99d1fa0f071eca141d4a8e18b78495114435ce759bc36665de4e25222e3691578b9627c08cb1bf7a41e9b4e36f145f98db92d27626ee-exec' -> '/Users/rohanrajpal/Documents/spurchat/code/spur/node_modules/.pnpm/sqlite3@5.0.8/node_modules/_tmp_57449_99adffdd7afc757e0d5808e1e80d95ff/node_modules/.bin/node-gyp'
Progress: resolved 1363, reused 708, downloaded 22, added 724
```

**Comment by zkochan** [comment] 2022-07-09 14:53
Is it consistently happening with `sqlite3@5.0.8`? Even if you remove the store completely?

**Comment by rohanrajpal** [comment] 2022-07-09 15:04
> Is it consistently happening with `sqlite3@5.0.8`? Even if you remove the store completely?

Completely wiped out pnpm & installed it via corepack this time, upgraded to 7.5.0 using `corepack prepare pnpm@7.5.0 --activate` & `pnpm i` worked. Tho I'm sure if I'd installed via the normal method it would have worked, most probably a store issue.

If by remove the store completely you mean `pnpm store prune` then yes its happening consistently, I also specifically tried to remove the mentioned store `/Users/rohanrajpal/Library/pnpm/store/v3/files/5c/` and it happened again.

Or is there a better way to completely remove the store?

**Comment by zkochan** [comment] 2022-07-09 15:07
OK, that is good. Then probably someone with a mac can investigate this.

**Comment by tianenpang** [comment] 2022-07-16 07:32
I got the same issue when install [`sharp`](https://www.npmjs.com/package/sharp) in Windows, tried `pnpm store prune` but no luck. BTW it works fine in WSL.

### Reproduce:

```bash
pnpm init

pnpm add sharp
```

### Logs:

```text
Windows:
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\xxx\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
WARN  The package linked to "node_modules\.pnpm\sharp@0.30.7\node_modules\sharp" had files with invalid names: lib\agent.js ......
pnpm: ENOENT: no such file or directory, copyfile 'C:\Users\xxx\AppData\Local\pnpm\store\v3\files\d1\263c03c238ae779abb226db2831d67193290b1811db7e8b4320d17c378a3dddced8129ff75c5753c304b031e0f7da2ace67b03997814b38415fe252ac3f6f8' -> 'C:\Users\xxx\Desktop\sharp-demo\node_modules\.pnpm\sharp@0.30.7\node_modules\_tmp_16932_6d39e7c272ccf220ac9d6e1deadaa934\node_modules.binprebuild-install'

WSL:
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/xxx/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/sharp@0.30.7/node_modules/sharp: Running install script, done in 4.9s
Progress: resolved 49, reused 27, downloaded 18, added 45, done

dependencies:
+ sharp 0.30.7
```

### Environment:

```text
  System:
    OS: Windows 10
    WSL: Ubuntu 20.04.4 LTS
  Binaries:
    pnpm: 7.5.1
    node: 16.15.1
```

**Comment by zkochan** [comment] 2022-07-16 21:13
I can't reproduce this issue on Windows.

**Comment by tianenpang** [comment] 2022-07-17 06:36
I removed all the global packages of `pnpm` manually and reinstalled it via PowerShell, it works now.

**Comment by supersabillon** [comment] 2022-07-18 18:15
We are seeing this same issue but can't reproduce locally, it only happens in our Github action using a linux runner. 

I have tried removing node-modules and pruning store before doing pnpm install and still same issue.

**Comment by mlucool** [comment] 2022-08-11 21:04
I am seeing this also on a built module (kerberos). I prune regularly, which I suspect could be related.

Any way for me to force it to reinstall one module?

**Comment by Cloud11PL** [comment] 2022-08-15 10:19
I have the same issue on MacOS, any fixes?

**Comment by arimus** [comment] 2022-08-15 18:39
FWIW, I ran into this with Sharp on OSX as well. Hadn't had any problems and then I couldn't stop the issue. Upgraded from 7.6.0 -> 7.9.0, did a `pnpm store prune` and then re-ran a `pnpm install` and it seems to have sorted things out.

Not sure why this started happening as nothing had changed on my side deps-wise or version wise to cause the issue. Very odd.

**Comment by rdss-dheuskel** [comment] 2022-08-18 21:06
im having this issue when running pnp install inside a container as well. 

the errors are not consistently in one package. the store is on the same mounted drive.

what i noticed is that for the erroring files there exists a file with different umask:
```
 ENOENT  ENOENT: no such file or directory, copyfile '/srv/www/html/.pnpm-store/v3/files/cf/83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e' -> '/srv/www/html/.pnpm-store/v3/tmp/_tmp_1446_914a3edbe32aadd65663b6becd4375e1/tests/Functional/CommandLine/FileFinders/fixtures/topFolder/folder/subFolder/allowedChangesFile'
```

for this example 

``` 
$ ls .pnpm-store/v3/files/cf/83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e*

-rw-r--r--   16 david  staff       0 Aug 18 22:56 83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
-rwxr-xr-x    1 david  staff       0 Aug 18 22:56 83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e-exec
```

**Comment by yangmingshan** [comment] 2022-08-24 09:46
I ran into this issue. My solution：

- rm pnpm-lock.yaml
- rm -rf node_modules
- rm -rf ~/Library/pnpm
- pnpm install

Then it works.

**Comment by cha-kos** [comment] 2022-08-29 16:10
ran into this on Mac M1 after `pnpm store prune`

fixed by removing the store folder with `rm -rf ~/Library/pnpm/store/v3/files/`

**Comment by MohamadKh75** [comment] 2022-10-02 13:43
Yep, i ran `pnpm store prune` too and then i have this problem
fixed by removing the store

**Comment by rdss-dheuskel** [comment] 2022-10-21 16:40
the issue still persists and is only fixable by forfeiting the advantage of linking by forcing hardcopies.

**Comment by kakserpom** [comment] 2022-10-26 15:19
I am having the same issue.

**Comment by mikehaertl** [comment] 2022-11-15 11:44
I also have seen this issue now twice on Linux. So it's not only MacOS.

**Comment by shellscape** [comment] 2022-11-16 18:49
@zkochan the fix by @cha-kos works in this scenario. I'd recommend that we expend the error message for this specific error with a hint on how to fix, or remove the offending file and attempt another install automatically.

**Comment by zkochan** [comment] 2022-11-16 22:18
I can reproduce this error if I set `verify-store-integrity` to `false` and I remove a file from the store.

As a temporary workaround, adding hints to the error message sounds good.

**Comment by shellscape** [comment] 2022-11-16 22:20
I think I ran into this because I ran a prune on the store the other day. I haven't had time to verify, but that's what I suspect.

**Comment by tgmarinho** [comment] 2022-11-18 16:18
> I ran into this issue. My solution：
> 
> * rm pnpm-lock.yaml
> * rm -rf node_modules
> * rm -rf ~/Library/pnpm
> * pnpm install
> 
> Then it works.

It's work! 

This https://github.com/pnpm/pnpm/issues/4997#issuecomment-1230527581 can work as well ! 

Thanks all

**Comment by conorzhong** [comment] 2022-11-22 07:37
I ran into this by(in a pnpm monorepo): 
```bash
rm -rf node_modules
pnpm store prune
pnpm i
```
env: apple m2, macOS 13.0

**Comment by SalahAdDin** [comment] 2022-11-28 22:23
> ran into this on Mac Silicon after `pnpm store prune`
> 
> fixed by removing the store folder with `rm -rf ~/Library/pnpm/store/v3/files/`

Yeah, this one!

**Comment by jeromehan** [comment] 2022-12-06 14:26
> Also having this issue after upgrading to v7. I have no idea how to reproduce it though... it works again by nuking the whole store and re-downloading everything.
> 
> ```
>  ENOENT  ENOENT: no such file or directory, copyfile '/Users/work/.pnpm-store/v3/files/68/fd2865a3cee2a68927ffed7c54667b1b3b03710b6a174ad45caa8e05f2e033b51e6d6f55ab22d8207f2fdb286c9dd057cb43171aa793ce9f180da8d7653e6e' -> '/Users/work/redacted/redacted/node_modules/.pnpm/fsevents@1.2.13/node_modules/_tmp_10595_695eb2b63757fc332de5b4c217d64f1d/build/.target.mk'
> ```
> 
> This is in MacOS by the way.
> 
> _Originally posted by @rdsedmundo in [#3229 (comment)](https://github.com/pnpm/pnpm/issues/3229#issuecomment-1149057063)_

`pnpm i --no-side-effects-cache ` can be solved。
side-effects-cache will be problems in some cases。
@zkochan

**Comment by unional** [comment] 2023-01-03 19:28
Happens to me too. After running `pnpm store prune`

```sh
pnpm store status
 ENOENT  ENOENT: no such file or directory, open '/Users/hwong/Library/pnpm/store/v3/files/e4/64fe91cb365951a356cefe6e86ad68290ee45834cb89028f3901e5b022a7b1f88df9ce4b7740e8a3e2c30f56d4e10a4ca7807145617591af808eb93979949f-index.json'
 ```

**Comment by darvesh** [comment] 2023-01-09 19:04
Happens to me too!

Apple M2.

**Comment by TomasHubelbauer** [comment] 2023-01-11 13:06
This happened to me as well as I think it was caused by me playing arround with `shamefully-hoist = true` in `.npmrc` and running `pnpm install` in a workspace which was already installed. Since to my knowledge toggling this option will affect how PNPM install its files, I think what happened was since the dependencies were already installed one way and I tried the other way, it broke the store somehow.

**Comment by pffigueiredo** [comment] 2023-01-13 14:41
> I can reproduce this error if I set `verify-store-integrity` to `false` and I remove a file from the store.
> 
> As a temporary workaround, adding hints to the error message sounds good.

Hey @zkochan ,  what's happening in my situation might help you to debug further, here it goes:

1. Everything was working fine on pnpm v6
2. Upgraded to pnpm v7 and started having this issue's error on a container (CI)

---
**CI STAGES**
1. [UPDATE_CACHE] I'm caching `pnpm` store to use in later stages, and when doing so, I'm running the following commands:
   - `pnpm config set store-dir ${CI_PROJECT_DIR}/.pnpm-store` (setting the store path)
   - `pnpm install --frozen-lockfile -r` (installing deps)
   - `pnpm store prune` (removing unused deps)
  1. [PROJECT_BUILD]  After updating the cache, I'm actually building the project and before doing that, I'm running:
       - `pnpm install --frozen-lockfile --no-verify-store-integrity -r` (which should take advantage of the previous cache)

---
**WORKAROUNDS**

So far, I was able to work around this with 2 different "solutions":
1. Not pruning the store on the "update-cache" stage
2. Removing the `--no-verify-store-integrity` from the install stage 

Does anything else comes to mind, or do you see any type of "conflicts" with the current setup?

**Comment by zkochan** [comment] 2023-01-15 01:13
I think I understand how the store can become corrupted by `pnpm store prune`. When we clear the store, we check the link attribute of the files. If nlink is 1, we assume that is not used anywhere, because no hard links are pointing to it. However, sometimes pnpm fails to create a hard link to the file in the store and it falls back to making a copy. 

I still don't understand though how could it fail without `verify-store-integrity=false`. As far as I understand, not everyone with the issue have disable store integrity verification.

**Comment by pffigueiredo** [comment] 2023-01-16 12:08
That must be it, I just tried to:
- add `side-effects-cache=false` to the `.npmrc` file and that also seems to fix the issue :green_circle: 

Thanks for looking into this :muscle:

**Closed** 2023-01-18 21:33 UTC
Labels: type: bug

**Comment by pchaganti** [comment] 2023-03-06 13:12
This is still happening with the latest version of 7.29.0. I am running in a container and pnpm install always errors out at some point with the "ENOENT: no such file or directory, copyfile" error. Same as @pffigueiredo above.

I have tried to remove the cache folder and node_modules and that doesnt help either.

```
node ➜ /workspaces/prabhakar/testapp (master) $ pnpm -v
7.29.0

node ➜ /workspaces/prabhakar/testapp (master) $ pnpm i
Scope: all 9 workspace projects
 WARN  GET https://registry.npmjs.org/ajv error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
ui                                       |  WARN  deprecated @aws-amplify/xr@4.0.15
ui                                       |  WARN  deprecated uuid@3.4.0
Downloading registry.npmjs.org/mapbox-gl/1.13.1: 6.84 MB/6.84 MB, done
Downloading registry.npmjs.org/react-icons/4.8.0: 15.7 MB/15.7 MB, done
ui                                       |  WARN  deprecated querystring@0.2.0
Packages: +1094
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /workspaces/prabhakar/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
 ENOENT  ENOENT: no such file or directory, copyfile '/workspaces/prabhakar/.pnpm-store/v3/files/7f/65c6403a23d93fb148e8259b012d6552ab3bff178f4a7d6a9d9cec0f60429fc1899e39b4bca8cc08afc75d9a7c7bfdb13fc372ca63c85eb22b0355eb4d6000' -> '/workspaces/prabhakar/testapp/node_modules/.pnpm/@aws-sdk+types@3.186.0/node_modules/@aws-sdk/_tmp_5505_c93a908b7e3177a2ec502d6603f68311/dist-cjs/logger.js'

pnpm: ENOENT: no such file or directory, copyfile '/workspaces/prabhakar/.pnpm-store/v3/files/7f/65c6403a23d93fb148e8259b012d6552ab3bff178f4a7d6a9d9cec0f60429fc1899e39b4bca8cc08afc75d9a7c7bfdb13fc372ca63c85eb22b0355eb4d6000' -> '/workspaces/prabhakar/testapp/node_modules/.pnpm/@aws-sdk+types@3.186.0/node_modules/@aws-sdk/_tmp_5505_c93a908b7e3177a2ec502d6603f68311/dist-cjs/logger.js'
Progress: resolved 1135, reused 709, downloaded 383, added 99
```

**Comment by devotox** [comment] 2023-06-19 00:45
This is happening on patches now

**Comment by zkochan** [comment] 2023-06-19 01:12
This issue was fixed. If you have the same error, see https://github.com/pnpm/pnpm/issues/5803 or https://github.com/pnpm/pnpm/issues/6187
