### ISSUE TITLE
The extend-node-path option does not appear to behave like false, on pnpm7

### ISSUE THREAD

**Issue by WhiteKiwi** [pnpm/pnpm#5285] opened 2022-08-31 09:47 UTC
I went through node-path issues at pnpm6. 
It was solved by giving the extend-node-path option to false.
During the pnpm7 migration, we encountered the same issue.

### pnpm version:
7.9.4

### Code to reproduce the issue:
When I exec `node_modules/.bin/jest`, then NODE_PATH is exported

### Expected behavior:
```diff
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

- if [ -z "$NODE_PATH" ]; then
-   export NODE_PATH="/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
- else
-   export NODE_PATH="$NODE_PATH:/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
- fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
fi
```

### Actual behavior:
```diff
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

+ if [ -z "$NODE_PATH" ]; then
+   export NODE_PATH="/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
+ else
+   export NODE_PATH="$NODE_PATH:/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
+ fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
fi
```

### Additional information:
 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: macOS

related pr: https://github.com/pnpm/pnpm/pull/4253

**Comment by WhiteKiwi** [comment] 2022-08-31 10:32
In monorepo

/node_modules
  - /.pnpm
    - /node_nodules
      - jest-cli@26
/packages
  - /foo
    - jest@28
  - /bar
    - jest@26

I tried run `pnpm exec jest -v` in /packages/foo, then jest 26 is printed.

**Comment by WhiteKiwi** [comment] 2022-08-31 11:10
https://github.com/pnpm/pnpm/pull/4513

**Comment by WhiteKiwi** [comment] 2022-08-31 11:22
I can solved this issue by giving the hoist options to false.
Is this the right solution? 🙇 

```
# .npmrc
hoist=false
```

**Comment by zkochan** [comment] 2022-08-31 23:18
This looks like a duplicate of #5176

**Closed** 2023-03-14 01:38 UTC
Labels: type: bug
