### ISSUE TITLE
`pnpm install` installs multiple copies of the same dependency at the same version

### ISSUE THREAD

**Issue by matthew-dean** [pnpm/pnpm#5585] opened 2022-11-03 19:03 UTC
### Expected behavior:
Matching dependencies with matching versions (or version ranges) resolve to one package.

### Actual behavior:
I just seemingly ran into [this PNPM bug](https://github.com/pnpm/pnpm/issues/2443), so I'm not sure why it's closed. I have identical references to `styled-components` as dependencies in a React Native app, and a shared component package, and they have a ThemeContext provider which is a singleton.

However, if I resolve sources for `styled-components`, one is resolving to `.../.pnpm/styled-components@5.3.6_react@18.1.0/node_modules/styled-components/native/dist/styled-components.native.cjs.js` and one is resolving to `.../.pnpm/styled-components@5.3.6_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/styled-components/native/dist/styled-components.native.cjs.js`

In fact, PNPM seems to install 5 copies of `styled-components` (probably 1 per reference?). When each one is resolved, they will all be creating different singletons for `ThemeContext`.

<img width="512" alt="Screen Shot 2022-11-03 at 12 16 37 PM" src="https://user-images.githubusercontent.com/414752/199813999-477516a4-4c06-4b67-9696-5f87e18f33d5.png">

I'm not sure why PNPM resolves node modules this way, but the premise of a monorepo is that matching packages won't get bundled twice, because they are matching dependencies. In this case, dependencies that are the same reference from two packages with the same version are two different dependencies! This defeats the purpose of a workspace package manager, does it not?

### Additional information:

 - `node -v` prints: v18.10.0
 - Windows, macOS, or Linux?: macOS

**Comment by matthew-dean** [comment] 2022-11-03 19:14
Also note, I don't see anything in [PNPM's documentation](https://pnpm.io/symlinked-node-modules-structure) that explains how or why this type of node resolution is happening. The docs seem to suggest that matching dependencies with matching versions will resolve to the same package. But as far as I can tell, this isn't the case, and PNPM is installing a copy per dependency reference, even if they match dependencies.

**Comment by lvqq** [comment] 2022-11-05 06:11
That's because `styled-component` has peerDependencies, refer: https://pnpm.io/how-peers-are-resolved

**Comment by zgriesinger** [comment] 2022-11-10 22:44
We have had a similar issue that was related to `optionalDependencies`

If you have one package being used with some optional dependencies and another instance in your mono repo with others you get two versions. Our workaround for now was to use the same optional dependencies everywhere we use the dependency. In this case it was `@nestjs/core`

**Comment by matthew-dean** [comment] 2022-11-25 20:53
@lvqq Wait... so the same package with the same version, and everything else the same versions, will still install different versions / copies of a module if it has a `peerDependencies` field? Is there a way to override this behavior?

**Comment by patroza** [comment] 2022-11-27 21:17
> We have had a similar issue that was related to `optionalDependencies`
> 
> If you have one package being used with some optional dependencies and another instance in your mono repo with others you get two versions.

Very painful stuff, stopped using optional and peerDependencies for now.
The worst part was trying to figure out what was going on. 
The second issue was that there's no built-in way to enforce single package version, or at least to error out on it.

This at least helps: https://github.com/pnpm/pnpm/issues/2713#issuecomment-1328341630

**Comment by matthew-dean** [comment] 2022-11-30 18:49
@patroza It's a nightmare. I'm getting all sorts of TypeScript errors in addition to `styled-components` singleton issues because PNPM is allowing each package and sub-package to install its own copy of `@types/react`, which, even though they are the same version, are different _references_, so TypeScript doesn't know that they are compatible types or can be substituted.

**Comment by patroza** [comment] 2022-11-30 19:05
Could pnpm overrides and [this setting](https://pnpm.io/package_json#pnpmpeerdependencyrulesallowany) help?

**Comment by matthew-dean** [comment] 2022-11-30 20:20
The solution I ultimately found was here: https://github.com/microsoft/TypeScript/issues/47663.

That is, I had two problems with PNPM dependencies. 
1. `styled-components` has exports that expect to be a singleton (specifically, an instance of React Context with `createContext`, which is the only way that React Context does / can work). Because they are duplicated, then referencing what _should_ be the same singleton (the same ID and version) fails. They are different initialized objects.
PNPM fails developer expectations here, which is that matching dependency versions of my required package (in this case, _exact_ matches) result in a single bundled version. Instead, PNPM decides that the dependency in the shared package _in my own monorepo_ does not match the dependency in the package importing it _again from my own monorepo_. Everything matches dependencies in terms of `package.json`, but multiple duplicates persist. Perhaps there are transitive peerDependencies that don't match, but how am I to know that or possibly manage it? Why can't PNPM manage this?
2. I solved the above problem by exporting a copy of this singleton from the shared package. _But_ TypeScript was still confused by the duplicates, insisting that matching `@types/` packages were not the same, and that types referenced by the shared package were not the same as types referenced by the consuming package.

**Comment by matthew-dean** [comment] 2022-11-30 20:22
@patroza 

Gist is [here](https://gist.github.com/matthew-dean/6a78ee73c06881cc3e789b88faf4ed20).

**Comment by patroza** [comment] 2022-12-01 05:47
@matthew-dean your lock actually looks very clean, without duplicates.
I only see `@types/react-dom` at various versions.
Are you running with `preserveSymlinks` in `tsconfig.json` ?

**Comment by patroza** [comment] 2022-12-01 08:23
@matthew-dean I think the workaround for you is to align the "dependencies" of each package that includes "styled-components", to include a fixed set of it's peer dependencies, like:
```
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0"
```

this should make only one version of styled-components appear. right now the variations you see are because for each different combination of the 3 mentioned (absence, presence, version etc), there will be a different styled-components instance.

**Comment by matthew-dean** [comment] 2022-12-01 16:50
Oh wow, so if the peerDependency is _missing_ in the dependency list, it makes another copy? That's...not super intuitive, even with the documentation. :/

**Comment by patroza** [comment] 2022-12-01 16:54
@matthew-dean totally. Im new to pnpm and while im quite for more correctness and tighten things up,
it seems pnpm goes a step too far..
Then again, there are just too many packages that require to be single instance in the tree, be it because of types, symbol or singleton state etc. A system for marking your package like that and detecting and mitigating this would definitely be a nice feat.

I don't know if the behaviour is recent, or has always been.

**Comment by Rafcin** [comment] 2022-12-02 03:09
Hi, so I had a stroke reading this feed, and I'm reconsidering many things now. 

So if I have a monorepo, and I have `apps` and `packages` right, suppose I create a Next app in `apps` that uses MUI. Now I plan to create multiple apps using MUI, so I move my theme and theme provider stuff to its own package, let's call it `ds`.  Will PNPM then have two different versions of MUI? I'm really lost here,  I'm having this styled-components issue with `@mui/styles` because it's essentially the same thing, and locally this works fine, but running on something like a awslinux2 machine I get this error, I don't get it. 

Should I just go back to yarn? a lot of my problems seem to stem from PNPM when it comes to deployments.

**Comment by innocenzi** [comment] 2023-01-11 18:47
If it helps anyone, I had to add `node-linker=hoisted` to `.npmrc` for the error to go away.

**Comment by zanminkian** [comment] 2023-01-12 15:34
Facing the same problem. So many npm package require one copy in the same app. 

I have a monorepo. `my-app`'s dependencies are `@nestjs/core`, `@nestjs/common` and `my-lib`. `my-lib`'s dependencies are `@nestjs/core` and `@nestjs/common`. `my-app` and `my-lib` use different copy of `@nestjs/core` and `@nestjs/common`. 

Really disappointed about this.

**Comment by zanminkian** [comment] 2023-01-12 19:09
Found an answer by author. That teach me how to avoid installing 2 copies at the same version.

**Comment by patroza** [comment] 2023-01-14 09:04
I'm currently using this inside my `.pnpmfile.cjs` to warn me of duplicate packages https://github.com/effect-ts-app/libs/blob/main/packages/pnpm-singleton/_src/plugin.ts
it's using a provisional `"singleton": true` expected in `package.json` of packages who should only exist once, or otherwise be provided a list of packages you want as singletons.

**Comment by sneko** [comment] 2023-02-18 14:39
Don't know if it can help someone here but here how I avoided deduplications of the same dependencies: https://github.com/pnpm/pnpm/discussions/6055#discussioncomment-5018827

**Comment by unional** [comment] 2023-02-28 18:32
FYI, still notice duplicate dependency with 7.28.0 and lockfile v6

In my case, there is a dup on `webpack`:

```
webpack@5.75.0
webpack@5.75.0_esbuild@0.16.17
```

This causes build to fail with `TypeError: The 'compilation' argument must be an instance of Compilation`

Tried adding overrides doesn't help:

```
{
  "pnpm": {
    "overrides": {
      "webpack": "^5.75.0"
    }
  }
}
```

**Comment by zkochan** [comment] 2023-03-03 11:53
closed by #6153

**Closed by zkochan** 2023-03-03 11:53 UTC
Labels: type: bug

**Comment by unional** [comment] 2023-04-28 15:59
This is still happening in 8.3.1

I'm suspecting if it has anything to do with `public-hoist-pattern[]`

Trying to update the project without it and see if that fixes the issue.

**Comment by zkochan** [comment] 2023-09-01 00:41
Is there a sample repository that showcases the issue? We use `@typescript-eslint` in the pnpm monorepo and have no issues.

**Comment by artemis-prime** [comment] 2024-03-12 16:08
Please reopen this.  It is clearly still happening.  This is core functionality!

**Comment by Brendonovich** [comment] 2024-03-19 04:31
I've made a reproduction of this happening in a way that affects us in https://github.com/pnpm/pnpm/issues/7809

**Comment by jbjhjm** [comment] 2024-05-22 10:57
@zkochan hi Zoltan, please review the latest posts in this thread.
The fix you've implemented in https://github.com/pnpm/pnpm/pull/6153 seems to work only partially.
The issue persists for multiple users, including me.
A reproduction is available one post above by @Brendonovich .

In our case, pnpm 9.1.2, webpack is installed twice with identical version, with hash difference being esbuild 0.20.1 / 0.20.2.
I was able to fix it by using package.pnpm.overrides + peerDependencyRules, but this is very unintuitive and I hope this behavior can be improved. (or, for DX, have info logged or available via a command that can shed some light on why pnpm added duplicate identical packages).

**Comment by unional** [comment] 2024-10-14 03:30
Also confirm it is still happening in 9.12.1
This is the cause of https://github.com/vitest-dev/vitest/issues/6674

Setting the following does not work:

```ini
dedupe-peer-dependents=true
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
public-hoist-pattern[]=*types*
public-hoist-pattern[]=*storybook*
public-hoist-pattern[]=*vitest*
```

I have to physically dedupe it by moving `vitest` and `storybook` packages to the workspace root.

**Comment by unional** [comment] 2024-10-16 18:29
> I have to physically dedupe it by moving `vitest` and `storybook` packages to the workspace root.

Note that sometimes force hoisting like this is not possible, e.g. when the dependencies are regular dependencies instead of dev deps.

**Comment by unional** [comment] 2024-10-17 07:12
@zkochan I managed to create a simple enough repro: https://github.com/repobuddy/storybook

Please check out the `pnpm-dedupe` branch.
